### ISSUE TITLE
Contenidos Control 1 

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2413/Syllabus-2021-1#1]
Hola, ¿Cuáles son los contenidos del control 1? ¿ Vamos a tener  que usar SQL?

**Comment by alanezz** [comment]
Hola,

Mañana en clases vamos a discutir la primera actividad, que tendrán cerca de dos semanas para hacer. Se trata de índices, que es la materia de la semana pasada. Van a tener que saber leer algunas consultas sencillas de SQL, pero lo veremos mañana.

**Comment by jagaldames** [comment]
Pero hoy no había clases :/ Lo discutiremos el miércoles y lo entregamos el viernes? eso dice el calendario al menos

**Comment by ValentinaAlvarezG** [comment]
Hola! perdón por lo anterior, hubo una confusión de repos. En el control 1 entra Álgebra relacional solamente (nada de SQL).
