### ISSUE TITLE
Entrega Control Siding

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2413/Syllabus-2021-1#10]
Hola, yo no soy estudiante de ingeniería entonces no tengo acceso a Siding.
¿Cómo puedo entregar el control?

**Comment by ValentinaAlvarezG** [comment]
Hola! tengo entendido que igual tienes acceso al siding con tus credenciales UC, puedes intentarlo? y nos avisas que pasa.

**Comment by enriquemolinare** [comment]
Intenté ingresar con mis credenciales UC (mail uc y contraseña)  pero no me funciona.

**Comment by JosefaPaz** [comment]
Hola! Intentaste sin añadir el @uc.cl?

**Comment by enriquemolinare** [comment]
Hola, si intenté inngresar sin el @uc.cl

**Comment by ironcadiz** [comment]
Hola! Voy a averiguar si te pueden dar acceso, en caso de que todavía no tengas de aquí a la hora de entrega del control puedes enviárselo por correo a  @ValentinaAlvarezG (vjalvarez@uc.cl)

**Comment by enriquemolinare** [comment]
EStoy hablando con el soporte tecnico de siding para crear unn cuenta. Pero todavía no la tengo, lo más probable es que lo envié al mail de valentina
