### ISSUE TITLE
Duda tablas evaluadas entrega 1

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2413/Syllabus-2021-1#100]
Hola. Existe una confusión respecto a la pauta y a lo dicho en otras issues. Para esta entrega se evaluara la creación de todas las tablas que aparecen en el esquema (junto al poblado de cada una)? O se evaluará tener las tablas creadas y pobladas que permitan únicamente realizar las primeras 3 consultas? 

Por ejemplo, si mi esquema tiene 10 tablas pero solo necesito 3 para hacer las 3 consultas que se piden, debería solo crear esas 3 tablas y poblarlas en el servidor.

Según lo que se entiende del enunciado, sería lo segundo, pero no queda muy claro.

**Comment by arpincheira** [comment]
Hola, la idea es la siguiente:

- **Todas las tablas deben poseer a lo menos un dato que corresponda a lo declarado en el esquema**
- Las tablas **relacionadas a las primeras 3 preguntas** deben poseer datos de tal forma que se puedan contestar las consultas propuestas de forma coherente. 

Espero que esto ayude a aclarar tu duda, recuerda que si no cumples el primer punto no puedes optar al puntaje completo del item "Tablas en el Servidor" descrito en la rúbrica de la entrega

**Comment by arpincheira** [comment]
Hola, acabo de actualizar aquello mencionado anteriormente, hemos llegado a la conclusión de que solo debes crear y poblar aquellas tablas necesarias para contestar las primeras 3 preguntas.

Saludos
