### ISSUE TITLE
Problemas conectandome al servidor

### ISSUE THREAD

**Issue by ElGarra** [IIC2413/Syllabus-2021-1#101]
Hola! Estoy intentando conectarme al servidor y me aparece este mensaje en la consola. Podrian ayudarme por favor?
![Captura de pantalla de 2021-04-12 15-18-31](https://user-images.githubusercontent.com/69603943/114449123-67001d00-9ba2-11eb-9c94-c8067533f1b8.png)

pd: tambien intente sin el comando sudo

**Comment by cmp831** [comment]
Hola, si es la primera vez que estas intentando conectar al servidor usando ese computador, debes poner `yes` en la consola cuando te pregunta por `Are you sure you want to continue connecting`

**Comment by ElGarra** [comment]
Hola! Ese era el problema. Muchas gracias!
