### ISSUE TITLE
Strings para Álgebra Relacional

### ISSUE THREAD

**Issue by cristobal-larach** [IIC2413/Syllabus-2021-1#102]
Existe algún operador en álgebra relacional similar a los "%" que se ponen en los strings de SQL para indicar la posibilidad de una cadena de letras cualquiera?

**Comment by arpincheira** [comment]
Hola, no, no existe un operador que te permita hacer aquello que quieres, yo te recomendaría buscar una forma alternativa, puede darse que necesites reconsiderar estructura de los datos de la tabla de tu esquema para poder hacer lo que quieres.

**Comment by cristobal-larach** [comment]
Ok! 
¿Álgebra relacional considera fechas como un tipo específico de datos? En ese caso, ¿Es posible comparar fechas con operadores como <, >, >=, <= ?

**Comment by arpincheira** [comment]
Hola, efectivamente puedes realizar comparaciones entre fechas en álgebra relacional.
