### ISSUE TITLE
Relación vehículo-unidad

### ISSUE THREAD

**Issue by tatanramos** [IIC2413/Syllabus-2021-1#103]
Hola! en la consulta 2 de los grupos pares, tenemos una duda respecto a cómo relacionar un vehículo a cierta unidad, ya que al menos en el enunciado, no existe explícitamente un atributo en la tabla "vehículos" que indique a que unidad pertenece cada uno.
Podríamos añadir un atributo extra, que sería la unidad a la que pertenece cada vehículo? En caso de que no, podríamos ocupar la tabla "despachos"? Ya que en esta última aparece la patente de un vehículo asociado a una dirección de origen de la unidad, sin embargo, en principio decidimos no ocuparla porque en caso de que un vehículo no este realizando un despacho, este no aparecería en esa tabla, pero no por eso no pertenecería a una unidad.

**Comment by arpincheira** [comment]
Hola, tal y como dice el enunciado, cada unidad mantiene un conjunto de vehículos, es decir, si puedes relacionar el vehículo con dicha unidad.
