### ISSUE TITLE
Entrega 1, Grupos Pares: Almacenamiento de datos en otras tablas

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2413/Syllabus-2021-1#104]
Hola. Tengo una duda con respecto a como podemos almacenar los distintos datos con los que se trabajará durante el proyecto.

Mi duda es si necesariamente todos los datos que se mencionan en cada apartado del enunciado (Unidades, Vehiculos, etc...) deben ir en una tabla con ese nombre, o si es  posible almacenar esos datos en distintas tablas.

Por ejemplo, en el enunciado se dice que con respecto a las **Unidades** es necesario conocer su id, dirección y comunas a donde se hace despacho. Podría modelarse de tal forma que parte de esa información quede almacenada en una _Tabla 1_, y otra parte en una _Tabla 2_?

**Comment by arpincheira** [comment]
Hola, tu puedes modelar los datos como creas más efectivo en lo que respecta esta entrega. Esta semana deberían ver como pueden crear ese tipo de subdivisiones para poder mantener el esquema de base de datos lo más atomizado posible.

Un ejemplo de modelación podría ser, por ejemplo, la subdivisión en una tabla con información únicamente de la unidad y otra con información "geográfica". Recuerda de todas formas que, si vas a hacer subdivisiones o cosas por el estilo, sería ideal que indicaras los supuestos por los cuales crees que es necesario hacer dichas subdivisiones y así poder entregarte un feedback más completo en lo que respecta a la entrega
