### ISSUE TITLE
Problema al probar instalación de postgreSQL

### ISSUE THREAD

**Issue by kalarconvl** [IIC2413/Syllabus-2021-1#105]
Hola! Instalé postgrSQL y no tuve problema. Seguí todos los pasos de instalación de la página y el último me funcionó bien. Pero cuando intento hacer la prueba que indican en la wiki me sale lo de la foto. Traté con lo sugerido en la issue #85 y me sale siempre lo mismo:

![Símbolo del sistema 12-04-2021 18_28_34](https://user-images.githubusercontent.com/68581172/114470517-092cfe80-9bbd-11eb-96a3-15da369a5bf3.png)

¿Qué puedo hacer?

**Comment by cmp831** [comment]
Hola, lo que sale en la issue #85 corresponde a comandos de Linux. En Windows si instalaste usando el instalador, el servicio debería estar funcionando directamente. 

Lo más probable es que no haz agregado al PATH de windows los programas de Postgres, te recomiendo ver esta [respuesta de StackOverflow](https://stackoverflow.com/a/61759364/9351545) para guiarte. Dependiendo de la version que instalaste, quizas tendrás que modificar la carpeta del path.
