### ISSUE TITLE
Problema al conectar servidor con SSH en vscode 

### ISSUE THREAD

**Issue by kalarconvl** [IIC2413/Syllabus-2021-1#106]
Hola! Estoy siguiendo los pasos de la ayudantía 1: instalé la extensión de VSCode "Remote - SSH", agregué el host y ahora quiero conectar la ventana al host, pero me sale el siguiente error:

1. tengo abierta la página que me salió al agregar el servidor:
![1](https://user-images.githubusercontent.com/68581172/114471069-febf3480-9bbd-11eb-9858-c1768125684a.png)

2. Aprieto las flechitas de abajo a la izquierda y pongo Connect window to host:
![2](https://user-images.githubusercontent.com/68581172/114471079-0383e880-9bbe-11eb-81fa-29cf8b5ea0d3.png)

3. Me pide seleccionar entre linux, windows y macOS ni idea por qué (?), como tengo windows aprieto windows:
![3](https://user-images.githubusercontent.com/68581172/114471091-07176f80-9bbe-11eb-80ef-7be595297b36.png)

4. Me pide la contraseña del grupo, esta ya la cambiamos con mi compañero así que pongo la nueva:
![4](https://user-images.githubusercontent.com/68581172/114471102-0a126000-9bbe-11eb-9a72-b9b5ded9f221.png)

5. Me tira error:
![5](https://user-images.githubusercontent.com/68581172/114471111-0ed71400-9bbe-11eb-967a-f8e6ee63498e.png)

¿Qué hice mal?

**Comment by miguel-mrtnez** [comment]
Hola, prueba seleccionando la opción **linux**, ya que se te solicita el sistema operativo **del servidor**. Podría también estar fallando la contraseña: al momento de ingresarla, ¿te cierra la conexión inmediatamente o te vuelve a solicitar la contraseña un par de veces más antes de rechazar? Por último, si nada de lo anterior resulta, intenta ingresar con *user*: `grupo999` (modificando el archivo *config* que muestras en la primera imagen), que tiene contraseña 'grupo999'. 

Cuéntanos qué resulta, ¡mucho éxito!
