### ISSUE TITLE
Problema con ruta de la entrega 1

### ISSUE THREAD

**Issue by Natydlb** [IIC2413/Syllabus-2021-1#107]
![Captura de Pantalla 2021-04-12 a la(s) 21 48 10](https://user-images.githubusercontent.com/62019255/114484983-21ab1200-9bd9-11eb-9443-a156b4fa3c73.png)

Hola, seguimos los pasos de la ayudantía para hacer el primer pull pero este no quedo en la carpeta "Entrega1" como se pide, si no que quedo afuera, como se ve en el pantallazo, como podría arreglarlo?

**Comment by miguel-mrtnez** [comment]
Hola, en el repositorio de tu computador puedes mover `BBDD_entrega_1.pdf ` a la carpeta que corresponde, hacer *add*, *commit* y *push* de los cambios y luego, en el servidor, hacer *pull*. Deberías visualizar los cambios luego de eso.

**Comment by Natydlb** [comment]
Tendría entonces que crear una carpeta en el repositorio? Es necesario
crear esa carpeta?

**Comment by miguel-mrtnez** [comment]
Hola, la carpeta `Entrega1` sí tiene que estar creada en el servidor, y debe contener en su interior a `BBDD_entrega_1.pdf` . La gracia de trabajar con un repositorio en el servidor es que puedes dejar los archivos y carpetas en el repositorio de tu computador **tal cual quieres que queden en el servidor**, pushear estos cambios, pullearlos desde el servidor y queda todo listo.

Si tienes dudas de cómo funciona **Git** o el servidor del curso, te recomiendo mucho asistir mañana a la sesión de resolución de dudas en **Discord**, que estará precisamente orientada a la **Entrega 1**.
