### ISSUE TITLE
Calificación del personal administrativo

### ISSUE THREAD

**Issue by Gustav2000** [IIC2413/Syllabus-2021-1#108]
Hola, una pregunta. La **calificación** del personal administrativo es un _str_ que puede ser por ejemplo: jefe, gerente, etc.?

Gracias de antemano.

**Comment by arpincheira** [comment]
Buena pregunta, dado que no queda claro en el enunciado pueden hacer supuestos al respecto(decir que lo interpretaron de tal manera porque....), es decir, va a ser igualmente válido el decir que son int o varchar.

**Comment by Gustav2000** [comment]
Yaa, muchas gracias!!
