### ISSUE TITLE
Duda sobre esquema

### ISSUE THREAD

**Issue by Zeva04** [IIC2413/Syllabus-2021-1#109]
Hola! Tengo una duda de la Entrega 1 donde nos piden: "Construir un esquema (preliminar, no será evaluado) que contenga sólo las tablas y los nombres de los atributos." Esto significa que ¿Tenemos que construir bosquejos de las tablas con sus respectivos atributos, como por ejemplo las que se encuentran en el enunciado del Control 1? o, ¿Hay que hacer un esquema con flechas con las relaciones entre estas además de sus atributos?

¡Gracias!

**Comment by arpincheira** [comment]
Hola, es más que nada lo primero, si quieres ver un ejemplo te recomiendo ver la issue #84 en donde se habla del formato solicitado para esta entrega.
