### ISSUE TITLE
Consulta RelaX

### ISSUE THREAD

**Issue by victorllagos** [IIC2413/Syllabus-2021-1#11]
Haciendo la guía 1 me veo en la necesidad de duplicar una relación para cruzarla consigo mismo, sin embargo cuando lo hago me pasa esto.

(1) Se queda con los mismos nombres de atributo que en la original por lo que no me permite cruzarla.
(2) No me permite cruzarla con la original porque esta se "borra" para efectos del sistema.

Siempre es uno de los 2 problemas. ¿Cómo puedo solucionarlo?

**Comment by JosefaPaz** [comment]
¡Hola!

Si por ejemplo quieres hacer una copia de la tabla `Tour`, es importante que le pongas otro nombre como `Tour2` para que al hacer consultas se entienda qué tabla quieres acceder.
Por otro lado, cuando quieras cruzarlas según un atributo recuerda que siempre puedes indicarlo como `Tour.tid` y `Tour2.tid`, solucionando tu problema (1) ya que estás indicándole al programa Relax cuál es la tabla a la que debe acceder.

Sobre el problema (2), me parece que este debe ser un error del sistema, por lo que si para ti la consulta te hace sentido en el papel, no te preocupes y confía en esa respuesta, ya que la página Relax no es perfecta y a veces tiene estos errores pequeños. De todas formas, con el párrafo anterior se te solucionaría el problema (1) y deberías poder probarlo ^^.

Éxito! 😄

**Comment by victorllagos** [comment]
Muchas gracias @JosefaPaz !! veré como me va
