### ISSUE TITLE
Duda vehículos-unidad

### ISSUE THREAD

**Issue by ftocornal** [IIC2413/Syllabus-2021-1#110]
Hola, tenemos una duda  ¿puede un vehículo ser parte de más de una unidad?, por ejemplo, estar en la flota de vehículos de la unidad 1 y en la flota de vehículos de la unidad 2.
Gracias!

**Comment by amparostevens** [comment]
Hola!  Ya que no se especifica en el enunciado, pueden realizar ese supuesto. 
Eso si, recuerden dejar por escrito todos los supuestos que hagan para que no hayan dudas al corregir!
