### ISSUE TITLE
Duda direcciones y comunas

### ISSUE THREAD

**Issue by Constanzape** [IIC2413/Syllabus-2021-1#111]
Hola, puedo asumir que existe una base de datos que asocie las direcciones con comunas? 
En base a esto podría crear una tabla que relacione la dirección con su comuna respectiva? 
Gracias de antemano!

**Comment by amparostevens** [comment]
Hola! Se contestó tu duda en  #42 y #51
Pero si te quedan dudas comenta esta issue
