### ISSUE TITLE
archivos ocultos

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2413/Syllabus-2021-1#112]
Hola, importa mucho si borré los archivos ocultos que venían en el servidor?

**Comment by mariovaldesa** [comment]
Se me subieron sin querer a mi repositorio y los eliminé desde ahi.

**Comment by arpincheira** [comment]
Hola, a priori no importan, de todas formas me gustaría que me indicaras tu número de grupo para tenerlo en consideración si es que hay algún problema en esta entrega o en entregas posteriores
