### ISSUE TITLE
Error psycopg2

### ISSUE THREAD

**Issue by JDomingoSilva** [IIC2413/Syllabus-2021-1#113]
Hola, estoy teniendo problemas con el uso de psycopg2. En el connect, dijeron que la línea de password se deja vacía por defecto, y traté de hacer eso, pero la consola dió error de "no password supplied", solamente se me ocurre que el user puede estar mal puesto, pero he probado todo: superuser, el nombre de mi sistema, mi nombre de usuario, etc.

**Comment by cmp831** [comment]
Hola, la contraseña que se debe poner corresponde a la contraseña de la base de datos.

**Comment by JDomingoSilva** [comment]
También probé poniendo esa contraseña, que no funcionó... ahi simplemente daba error de autentificación (también probé con otras contraseñas)

**Comment by cmp831** [comment]
Desde qué ambiente (local, servidor) estás tratando de conectar a qué bases de datos? Puede ser que falta configurar los permisos en la base de datos

**Comment by JDomingoSilva** [comment]
localmente creé una base de datos de prueba, en el fondo lo que hice fue seguir los pasos de la guia de instalación de postgresql y psycopg2, y en el paso del código de python me quedé estancado

**Comment by cmp831** [comment]
Ya perfecto, entonces quizas puedes probar alguna de estas [respuestas](https://stackoverflow.com/a/12721095) para resetear la contraseña de la base de datos del usuario que quieres usar

**Comment by JDomingoSilva** [comment]
gracias!
