### ISSUE TITLE
Métodos de conserva

### ISSUE THREAD

**Issue by pedrobeckerj** [IIC2413/Syllabus-2021-1#114]
Hola, en la guía (para los impares) se nos dice que los productos comestibles tienen tres tipos: congelados, frescos y en conserva. Para los congelados nos piden detallar el peso y para los frescos el tiempo, pero para los en conserva piden "el método de conservación", pero no sé bien a que se refieren. Deberíamos inventarlos?

**Comment by amparostevens** [comment]
Hola! No es necesario que los inventen, simplemente tengan en cuenta que existen diferentes métodos y son una característica del producto. Ustedes deben decidir qué tipo de dato es y justificar su elección pensando en la forma más correcta de modelación.

**Comment by pedrobeckerj** [comment]
Gracias!

**Comment by pedrobeckerj** [comment]
Gracias!
