### ISSUE TITLE
Comando SQL MAX cuando hay valores iguales

### ISSUE THREAD

**Issue by FlorenciaSciaraffia** [IIC2413/Syllabus-2021-1#115]
Hola! Cuando uno utiliza el comando MAX y hay dos valores máximos iguales, este retorna uno o ambos? En caso que retorne uno, cual podría ser un comando para que retorne ambos?

**Comment by cmp831** [comment]
Hola, la función `MAX` de SQL es una función escalar, retorna el valor máximo en vez de registros. En caso donde quieres usar ese valor para buscar los registros con ese valor, puedes usar una consulta anidada del siguiente estilo:

```sql
SELECT * FROM Table
WHERE value = (SELECT MAX(value) FROM Table);
```
