### ISSUE TITLE
Flujo de trabajo con git

### ISSUE THREAD

**Issue by Gustav2000** [IIC2413/Syllabus-2021-1#116]
Hola, ya entendí la forma de utilizar este flujo de trabajo
![image](https://user-images.githubusercontent.com/62355739/114765132-cb51e680-9d32-11eb-81fa-8f32b51df810.png)

Pero me gustaría saber que tan recomendable es usar extensiones de VSC para trabajar directamente desde el servidor?, de modo de evitar tener que hacer el pull desde el repositorio local del servidor cada vez que tengamos que actualizar algo. En caso de hacer esto el repositorio remoto de git prácticamente no se utilizaría.

En caso de que se pueda trabajar exclusivamente desde el repositorio local del servidor, podemos crear más carpetas adicionales a la de la Entrega1 (para tener archivos de prueba y trabajar en ellos)?

**Comment by miguel-mrtnez** [comment]
Hola, ciertamente que en esta entrega el manejo de archivos con **Git** es escaso, ya que solo se les pide entregar un `.pdf` en cierta carpeta, pero puede que para las próximas entregas, que tienen que ver con alimentar una página web con su base de datos, esta herramienta les sirva para organizarse entre los miembros del equipo.

Sí está permitido crear más archivos y carpetas, siempre y cuando se entregue el archivo en la carpeta que se les indica en el enunciado. De todas maneras, trata, por favor, de mantener todo ordenado :smile:

**Comment by Gustav2000** [comment]
Okaa, muchas gracias!!!
