### ISSUE TITLE
Problema al importar tablas desde csv

### ISSUE THREAD

**Issue by jonanortizvega** [IIC2413/Syllabus-2021-1#118]
Hola!
Creamos los csv para cada tabla en el servidor, pero al intentar importarlas tuvimos el siguiente error:
![Screenshot 2021-04-14 191942](https://user-images.githubusercontent.com/61998074/114792738-e6365200-9d56-11eb-88b9-1742391b07f5.png)
¿Qué se debe hacer para lograr importar las tablas desde csv correctamente?
De antemano, muchas gracias
Saludos

**Comment by miguel-mrtnez** [comment]
Hola, la relación Comunas **debe estar creada** al momento de ejecutar `\COPY`. Recuerda también que todos los comandos en postgres deben terminar con un punto y coma ; 

Dicho esto, para esta entrega, como no se requiere poblar las tablas con un gran volumen de datos, tal vez te resulte más conveniente ingresar manualmente las tuplas con el comando `INSERT INTO`. Mucho éxito y cuéntanos cómo te fue.

**Comment by sofiaolmedos** [comment]
@miguel-mrtnez no habíamos puesto el ; al crear las relaciones. Mcuhas gracias por la ayuda!
