### ISSUE TITLE
Error Consulta en Relax

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2413/Syllabus-2021-1#12]
Hola, estoy intentando hacer un consulta para extraer las montañas cuya calificación sea Munro. Estoy usando la misma notación que uno usaría a mano pero me tira error
No sé que estoy haciendo mal o si se debe hacer algo diferente en relax?

[EDIT]

**Comment by victorllagos** [comment]
No sé si entre alumnos se puede responder, pido disculpas si estoy incumpliendo alguna norma y si me pueden avisar sino para borrar el comentario. El error va en la comilla en vez de usar " usa ' por lo menos cuando tuve ese problema así me funcionó bien.

**Comment by arpincheira** [comment]
Hola, no hay problema en responder dicha duda @victorllagos, de hecho agradezco mucho tu disposición.

@enriquemolinare ojo con publicar imágenes involucradas con una posible resolución del control, si quieres hacer consultas de ese estilo te recomiendo poner otros datos de ejemplo.

**Comment by enriquemolinare** [comment]
> Hola, no hay problema en responder dicha duda @victorllagos, de hecho agradezco mucho tu disposición.
> 
> @enriquemolinare ojo con publicar imágenes involucradas con una posible resolución del control, si quieres hacer consultas de ese estilo te recomiendo poner otros datos de ejemplo

**Comment by enriquemolinare** [comment]
perfecto, lo voy hacer a la próxima
