### ISSUE TITLE
Entrega 0, Grupo par, Despachos

### ISSUE THREAD

**Issue by Huasito-Appel** [IIC2413/Syllabus-2021-1#120]
Hola, respecto a los despachos no me queda claro si al direccion de destino es algo asi como "calle p sherman wallaby 42 sidney" o es la comuna hacia la que se despacha, en vista de la consulta numero 3 que debemos realizar.
Creo que debemos tener atributos con ambos, pero capaz para esta entrega puedo tener como supuesto que las direcciones son las comunas hacia donde va.

**Comment by miguel-mrtnez** [comment]
Hola, creo que la issue #58 puede ayudarte bastante. Saludos.

**Comment by Huasito-Appel** [comment]
Toda la razon, se me paso la issue
