### ISSUE TITLE
Duda direcciones de despacho y unidades entrega pares

### ISSUE THREAD

**Issue by drosselot** [IIC2413/Syllabus-2021-1#121]
Hola! En el enunciado de las grupos pares se pide que las unidades, y los despachos tengan direcciones y que las unidades tengan comunas, pero en ninguna parte dice que las direcciones tengan comunas (solo sale en el enunciado de tríos). Mi duda es si nosotros debemos asociarlas también. Si es así, es necesario entonces que las comunas de la unidad del vehículo de un despacho tenga relación con el origen y destino del despacho?

**Comment by arpincheira** [comment]
Hola tu puedes asumir que las direcciones están asociadas a comunas perfectamente de la forma en la que indicas como en la forma en la que se encuentran asociadas por el enunciado del otro tipo de grupo. Lo importante es que justifiques el motivo por el cual las asociaste de uno o de otro modo.
