### ISSUE TITLE
Licencia repartidor y vehículo

### ISSUE THREAD

**Issue by drosselot** [IIC2413/Syllabus-2021-1#122]
Hola! Cuando llenemos los datos de las tablas debemos hacer que los repartidores con un tipo de licencia deben estar designados a esos tipo de vehículos o da lo mismo?

**Comment by arpincheira** [comment]
Idealmente deberían estar asociados a ese tipo de vehículo. En el caso de que no lo hayas hecho así  te recomendaría indicar el motivo por el cual podría llegar a pasar esto y añadir una justificación o explicación  para que, al momento de corregir, los ayudantes sean capaces de saber de antemano que esto sucede y que no es un error de inconsistencia.

**Comment by drosselot** [comment]
Vale gracias! Quería saber también si es necesario que los repartidores estén designados a los vehículos de la misma unidad?
