### ISSUE TITLE
Uso de bool

### ISSUE THREAD

**Issue by victorllagos** [IIC2413/Syllabus-2021-1#123]
Hola! Estaba pensando que una relación podría hacerse más fácil si usara algo del tipo True/False, sin embargo en las slides del curso no hay nada parecido en la parte de Tipos de Datos. Buscando información de sql encontré lo del tipo de dato Bit. Es permitido usar algo de este estilo?.

Dejo la página donde encontré la información explicada de una manera bastante sencilla.
[https://parzibyte.me/blog/2019/05/22/tipo-booleano-sql-server/](url)

Gracias de antemano

**Comment by miguel-mrtnez** [comment]
Hola, está permitido que utilicen todos los data types que postgres tiene para ofrecer. Ahora ojo, el artículo al que te refieres habla de un data type propio de **SQL Server**, que es un **DBMS** distinto a **PostgreSQL**, por lo que no está disponible. En el siguiente [link](https://www.postgresql.org/docs/9.5/datatype-boolean.html#:~:text=PostgreSQL%20provides%20the%20standard%20SQL,by%20the%20SQL%20null%20value.&text=Boolean%20constants%20can%20be%20represented,TRUE,%20FALSE,%20and%20NULL.) puedes encontrar información respecto al data type **BOOLEAN**, que creo, es lo que estás buscando.

**Comment by victorllagos** [comment]
@miguel-mrtnez muchas gracias!!
