### ISSUE TITLE
Problemas al copiar archivos CSV 

### ISSUE THREAD

**Issue by Flvilches** [IIC2413/Syllabus-2021-1#124]
Hola!
He estado intentando copiar los archivos _csv_ a la base de datos siguiendo los ejemplos dados en el Wiki y en la ayudantía, pero dice que no existe el archivo o el directorio. He colocado los archivos de distintas maneras (En carpetas, en la carpeta principal, etc.) pero aún así dice que el directorio no existe.
Ya vi el issue #44 y el #95, pero no he podido solucionar dicho problema.
Gracias de antemano! :)

**Comment by miguel-mrtnez** [comment]
Hola, el comando `\COPY` es propio de postgres, y si el error que te arroja es como "*directory not found*", significa que estás tratando de ejecutarlo en la consola, antes de entrar a postgres con el comando `psql`. Una vez adentro, recuerda que todos los comandos deben terminar con punto y coma **;** . Si continúan los errores, por favor adjunta capturas para intentar ayudarte mejor, y si lo solucionas, cuéntanos. ¡Ánimo!

**Comment by sreitze** [comment]
Hola! estoy teniendo el mismo error. Adjunto pantallazo
![image](https://user-images.githubusercontent.com/69603335/114912973-a0c56380-9dee-11eb-9daf-eab15e04b760.png)

**Comment by Flvilches** [comment]
Es el mismo problema que tengo yo, de hecho, tus distintos intentos cambiando la escritura del path tambien los hice. Decidí finalmente ingresarlos a mano, ya que no encontre solución.

**Comment by cmp831** [comment]
Les recomiendo que revisen este [articulo](https://www.geeksforgeeks.org/absolute-relative-pathnames-unix/) o esta [respuesta ](https://askubuntu.com/a/607476) sobre los distintos tipos de rutas que pueden usar en Linux. 

@sreitze para tu caso, creo que borrando la barra `/` al inicio de la ruta podría hacer funcionar tu comando.

**Comment by sreitze** [comment]
Oka lo intentare, gracias.

**Comment by sreitze** [comment]
Efectivamente funcionó @cmp831 gracias.
