### ISSUE TITLE
Fechas de csv a pqsl

### ISSUE THREAD

**Issue by sreitze** [IIC2413/Syllabus-2021-1#129]
Hola, estoy teniendo un problema al importar mi archivo productos.csv, que tiene un atributo "fecha de expiración" (date). No estoy seguro si el problema es el formato en el que tengo la fecha en csv, que es por ejemplo, "2021-08-09". Estaba preguntandome si hay que poner la fecha con comillas o sin en el csv, para luego importarlo en psql. Gracias de antemano.

**Comment by arpincheira** [comment]
Hola, acabo de probar importar  con y sin comillas y en ambos casos me funcionó correctamente al interior del servidor, en una de esas podría ser otro el motivo por el cual te está surgiendo dicho error.
