### ISSUE TITLE
Duda Solución Guia 1/Control

### ISSUE THREAD

**Issue by SantinoDaloy** [IIC2413/Syllabus-2021-1#13]
Hola, En la solución de la guía 1, en varias preguntas hacen natural join entre Tour, SeVisita y Vinas. Mi duda es si se asume que el natural join se va a hacer por los atributos que tienen en común que en este caso son vid y tid. Porque también existe un tercer atributo en común que es "nombre". ¿Qué pasa con este atributo al momento de usar natural join?

**Comment by ValentinaAlvarezG** [comment]
Hola! en estricto rigor, se debería explicitar en el segundo join por cual atributo.

**Comment by ValentinaAlvarezG** [comment]
Pero para darte una explicación más detallada:

Si tienes dos relaciones R(a,b) y S(a,b) al hacer un natural join vas a hacer R.a = S.a y R.b = S.b, lo que en el caso de la guía serían los atributos vid y nombre.

En la pauta lo pusimos así no más solo para simplificar un poco, pero en estricto rigor sí debería tenerlo.

Espero haberte aclarado!

**Comment by SantinoDaloy** [comment]
perfecto, muchas gracias!
