### ISSUE TITLE
Formato directorios servidor con clonacion de repo.

### ISSUE THREAD

**Issue by Huasito-Appel** [IIC2413/Syllabus-2021-1#131]
Hola! decidimos clonar nuestro repo personal en el servidor para acceder a los archivos, por lo que nuestros direcctorios en el servidor son algo asi
~/repo/Entrega1/files y carpetas
~/Sites
planeamos para futuras entregas tener
~/repo/Entrega1/files y carpetas
~/repo/Entrega2/files y carpetas
esto conflictua con la rubrica pero nos parece mas comodo tanto para estas como futuras entregas.
Queremos saber si lo podemos dejar asi o nos tenemos que  adherir a la rubrica, en donde tendriamos algo asi
~/Entrega1/repo/files
para futuras entregas eliminar la carpeta entrega 1 y tener
 ~/Entrega2/repo/carpetas y files

**Comment by arpincheira** [comment]
Hola, el formato que indicas si va a generar problemas al momento de hacer la recolección de entregas y no cumpliría con el lo enunciado. Yo les recomiendo hacer lo segundo, por último  clonar un repositorio al interior de cada carpeta, pero encuentro que podría ser bastante tedioso y consumiría bastantes recursos del servidor por lo que no lo encuentro una buena práctica(aunque les podría servir para esta primera entrega). Es por esto que les enseñamos la segunda forma de hacerlo(inicializando y configurando el repositorio), se que es medio tedioso la primera vez, pero se realiza una única vez(para que lo consideren en posteriores entregas).
