### ISSUE TITLE
Duda consultas 3 y 6, grupos impares

### ISSUE THREAD

**Issue by goyo20** [IIC2413/Syllabus-2021-1#132]
En la consulta 3 cuando dice: "todas las tiendas que venden al menos un producto no comestible", ¿debemos considerar las compras hechas en cada tienda?

De igual manera en la consulta 6, ¿se refiere a la tienda que ha registrado más ventas de productos comestibles?

**Comment by arpincheira** [comment]
Hola, creo que eso puede haber sido un mini error de enunciado, pues debería decir:
"todas las tiendas que **vendan** al menos un producto no comestible"
Con este cambio se da a entender que, cada tienda que tenga al menos un producto no comestible en su inventario debería quedar registrada en dicha pregunta. 

Por otro lado, cuando se dice "ha registrado", tiene que ver con el historial de ventas de la tienda.
