### ISSUE TITLE
Contraseña y acceso a servidor por parte de ayudantes

### ISSUE THREAD

**Issue by nfragav** [IIC2413/Syllabus-2021-1#133]
Hola! Quería preguntar si nos pedirán nuestras contraseñas del servidor pronto para poder corregir nuestra Entrega 1. Pregunto porque estamos ad portas de la entrega y al parecer no hay ningún lugar donde hayamos tenido que ingresar la clave para que los ayudantes tengan acceso a ella y puedan corregirnos. Asimismo, tengo esta preocupación sobre la clave de la base de datos (cuando uno tipea `psql`). Gracias de antemano!

**Comment by arpincheira** [comment]
Hola, no es necesario que nos den sus contraseñas, nosotros tenemos un método alternativo para poder acceder a dicha información el cual no requiere de sus credenciales.
