### ISSUE TITLE
Duda sobre los valores nulos en el algebra relacional

### ISSUE THREAD

**Issue by Kevinnevik** [IIC2413/Syllabus-2021-1#134]
Hola tengo una duda sobre si en la selección del algebra relacional (sigma), se puede poner una condición de que un atributo sea distinto de null, es decir, de un valor nulo.

**Comment by arpincheira** [comment]
Hola, por lo que tengo entendido no, no podrías hacer eso pero podrías jugar con los operadores de tal forma de quedarte con tablas sin valores nulos
