### ISSUE TITLE
Duda sobre despachos y comunas

### ISSUE THREAD

**Issue by Araos827** [IIC2413/Syllabus-2021-1#135]
Podemos poner como supuesto que las unidades se encuentran dentro de la comuna donde hacen los despachos? O bien, puede una misma unidad hacer despachos a mas de una comuna?

**Comment by arpincheira** [comment]
Hola, ese supuesto chocaría con lo propuesto por el enunciado, donde se da a entender que una unidad realiza despachos a una o más comunas.
