### ISSUE TITLE
Trabajo con DataGrip

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2413/Syllabus-2021-1#137]
Hola!
Alumnos de otros semestres nos recomendaron mucho usar DataGrip para trabajar con las bases de datos y el servidor. Ya tenemos  todo instalado y obtuvimos licencias de estudiantes, pero no podemos lograr descubrir cómo conectar un proyecto en DataGrip con el servidor del ramo, alguien sabrá cómo se hace esto?
Es un poco por conveniencia que queremos trabajar con DataGrip, así que si nadie sabe está bien 😅 
Gracias!

**Comment by cmp831** [comment]
Hola,
Puedes agregar la base de datos como un `Data Source`  en la pestaña de database dentro de DataGrip, recuerda seleccionar Postgres para usarlo con el servidor del curso.
![image](https://user-images.githubusercontent.com/22181800/115087660-908bb200-9edc-11eb-8d6a-d91106ed16a3.png)

Luego debes ingresar el hostname que seria `codd.ing.puc.cl`, el usuario de su servidor, la contraseña del usuario, y finalmente el nombre de la base de datos de su grupo.
![image](https://user-images.githubusercontent.com/22181800/115087727-b913ac00-9edc-11eb-906e-b8513aede376.png)
Usando el `Test connection` pueden probar la coneccion.
