### ISSUE TITLE
Duda sobre dependencias

### ISSUE THREAD

**Issue by domingo2000** [IIC2413/Syllabus-2021-1#138]
Hola, tengo una duda con la materia vista en clases, no entiendo si es que puedo o no usar un ID de una relación con parámetro en una dependencia. Por ejemplo si yo tengo lo siguiente 
`Personas(id, rut, nombre, sexo, edad)`
¿Puedo usar el id como  `id -> rut, nombre, sexo, edad` ?
Por otro lado, si en el mismo caso tengo  que las personas tienen sombreros. y pueden tener varios sombreros, y hago una relacion
'SombrerosPersonas(pid, sombrero)', como haría las dependencias en esa relación?, puesto que si hago
 `pid, sombrero -> pid, sombrero` quedaría como una dependencia trivial y no sabría como cumplir con la definición de BCNF vista en clases.

**Comment by ValentinaAlvarezG** [comment]
Hola! 
Sobre lo primero, si tienes ``Personas(id, rut, nombre, sexo, edad)``, no va a estar en BCNF, ya que ``id`` va a ser tu pk, pero también vas a tener la dependencia no trivial  ``rut --> nombre, sexo, edad`` y ``rut`` no es la pk, cachai?

Ahora, sobre lo segundo de los sombreros, vas a tener la dependencia trivial y eso si es condición para que esté en BCNF así que todo ok.

**Comment by domingo2000** [comment]
Hola, entonces me surge la duda de como puedo implementar una surrogate key cumplienfo bcnf, puesto que leyendo este post que es como un caso parecido
https://stackoverflow.com/questions/16503620/bcnf-with-one-surrogate-key-and-two-unique-keys
Le responden que como id y ssn (rut en mi caso) son los dos unicos seguiría estando el bcnf, a lo que voy es que podría yo definir rut y id como primary key por separado para que me cumplan bcnf, o tengo que si o si eliminar el id y dejar el rut como natural key, puesto que prefiero de gran manera tener id como primary key.

**Comment by ValentinaAlvarezG** [comment]
La próxima clase el profe va a hablar un poco sobre esto al inicio para aclarar dudas. Pero creo que en todo caso tendrías que tener ``id`` como llave y ``rut`` también como llave. Igual la idea es que no se sobrecompliquen, sigan a su corazón ❤️  y sigan las clases jajajaja

**Comment by domingo2000** [comment]
Hola, leyendo harto para aclarar la duda, (y porque mi corazón me dice que no hago nada malo al usar un user_id y el rut al mismo tiempo), me surge una duda. ¿Es lo mismo una super key que una primary key?, leyendo este artículo  https://www.geeksforgeeks.org/difference-between-primary-key-and-super-key/ entiendo que la super_key es aquella que define todos los otros atributos. En este caso
`rut -> nombre, id`
`id -> nombre, rut` 
Por lo tanto ambas serían una super key, pero arbitrariamente yo elijo una como primary key. Con eso dicho, BCNF requiere que los atributos de la izquiera de la dependencia sean super key o primary key??

**Comment by DomagojVrgoc** [comment]
Cómo dijimos en clases: surrogate keys te rompen bcnf **al introducirlos durante la modelación**. En terminos de modelar tu caso de uso, quieres hacer la cosa la más simple posible. Una buena explicación puedes encontrar en: https://dba.stackexchange.com/questions/16554/what-normal-form-does-a-surrogate-key-violate En el link la respuesta selecionada está mala, pero si sigues leyendo te explican qué las surrogate keys se introducen de manera arbitraria efectivamente, y no tienen nada qué ver con **modelación**. No hay nada malo en introducirlas, pero cómo dijimos en las clases, tienes qué preocuparte qué tu aplicación no rompe la condición qué quieres imponer. 

En tu ejemplo :
rut -> nombre, id
id -> nombre, rut
No hay problemas. Acuérdate de la definición de BCNF qué usamos nosotros: X->A está bien si X es una **llave** (ver los slides). No necesariamente una llave primaria. Cómo rut es una llave en tu caso estás bien.

**Comment by DomagojVrgoc** [comment]
> 
> 
> Hola, leyendo harto para aclarar la duda, (y porque mi corazón me dice que no hago nada malo al usar un user_id y el rut al mismo tiempo), me surge una duda. ¿Es lo mismo una super key que una primary key?, leyendo este artículo https://www.geeksforgeeks.org/difference-between-primary-key-and-super-key/ entiendo que la super_key es aquella que define todos los otros atributos. En este caso (simplificando los otros atributos)
> `rut -> nombre, id`
> `id -> nombre, rut`
> Por lo tanto ambas serían una super key, pero arbitrariamente yo elijo una como primary key. Con eso dicho, BCNF requiere que los atributos de la izquiera de la dependencia sean super key o primary key??

En breve, aquí tiene qué ser una super key cómo especificas. En los slides lo tuvimos mal escrito originalmente, pero ahora lo arreglamos, y agregamos un ejemplo para agregar.
