### ISSUE TITLE
Datos Erroneos Plano_covertura.csv

### ISSUE THREAD

**Issue by domingo2000** [IIC2413/Syllabus-2021-1#139]
Hola, resulta que procesando los datos del plano de cobertura me di cuenta que hay una dirección que está mal ingresada, que corresponde al id 78, almacen lacio, donde la dirección aparece como 307307 en vez de 307, para que lo arreglen y otros grupos no tengan problema.

**Comment by arpincheira** [comment]
Hola, efectivamente es un error que se soluciona tal como dices(lo había visto anteriormente  pero aparentemente se me fue guardar los cambios del archivo). 

Muchas gracias por el aviso
