### ISSUE TITLE
Crear nueva relacion Relax

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2413/Syllabus-2021-1#14]
Hola, me gustaría crear una nueva relación en Relax a partir de una relación antigua de la misma forma que se hace en notación. Sin embargo no me resulta y me tira a error.
* La condición no me tira error
![DUDA 2](https://user-images.githubusercontent.com/69764237/112528330-c5e02c80-8d82-11eb-9324-b0720cc0fdfc.PNG)

**Comment by JosefaPaz** [comment]
¡Hola!

Si pones el mouse encima de rho te muestra cómo es la notación en Relax para renombrar una relación o una columna, por lo que no estoy segura que en el programa se puedan crear nuevas relaciones. Te recomedaría hacer esa pregunta a mano, o al menos la parte de crear una nueva relacion!
