### ISSUE TITLE
Duda id Productos datos entregados

### ISSUE THREAD

**Issue by domingo2000** [IIC2413/Syllabus-2021-1#140]
Hola, tengo una duda, resulta que viendo los datos entregados me di cuenta de que para distintas tiendas un producto con el mismo id puede ser un producto distinto. Por esto me gustría unificar todos los productos y hacer que el id sea unico para cada producto. ¿Puedo hacerlo? ¿O debo  seguir almacenando la información que me dice el id del producto específico para cada tienda? Ejemplo
Datos entregados

| id | Nombre    | tid |
|----|-----------|-----|
| 22 | teclado   | 34  |
| 22 | televisor | 51  |
| 22 | teclado   | 60  |
<br /> 
Datos procesados Productos unificado:

| id | Nombre    |
|----|-----------|
| 21 | teclado   | 
| 22 | televisor |

Igualmente guardaría que productos pertenecen a cada tienda, lo unico que no sabría es que id específico le tiene asignada la tienda a un producto.

**Comment by arpincheira** [comment]
Hola, debes asumir que el nombre del producto(pues es lo único que cambia para productos del mismo id) es aquel del primer producto que aparece con dicho id(siguiendo el orden del archivo que les entregamos). Pronto vamos a subir la versión actualizada de dicho archivo.

Nuevamente muchas gracias por avisar sobre dicho error.
