### ISSUE TITLE
Duda sobre modelo E/R

### ISSUE THREAD

**Issue by JoMarchant** [IIC2413/Syllabus-2021-1#141]
Hola,

En el enunciado se pide "ilustrar las entidades, asociaciones y cardinalidades" del modelo E/R, tengo dos dudas:

1. **¿Las asociaciones son lo mismo que relaciones?**
2. **¿Es necesario que estén todos los atributos de cada entidad?**

Gracias de antemano!

**Comment by arpincheira** [comment]
Hola, la respuesta a tu primera pregunta es sí, con asociaciones nos referimos a relaciones. Con lo que respecta a tu segunda pregunta, efectivamente es necesario que agreguen todos los atributos en cada entidad, para poder lograr esto te recomiendo que veas las solución de la guía de diseño, la cual puedes encontrar [aquí](https://github.com/IIC2413/Syllabus-2021-1/blob/main/Gu%C3%ADas/Gu%C3%ADa4%20-%20Diseño_Solucion.pdf)
