### ISSUE TITLE
Duda sobre compras (grupo impar)

### ISSUE THREAD

**Issue by pacristi** [IIC2413/Syllabus-2021-1#142]
Hola,
En el enunciado de la entrega 1 se indica que una compra pertenece a solo una tienda pero en los datos entregados ```compras.csv``` no existe la columna de la tienda.

**¿Deberíamos considerar entonces que una compra pueda ser realizada a muchas tiendas distintas?**

Muchas gracias!!

**Comment by arpincheira** [comment]
Hola, efectivamente la idea es lograr modelar lo primero pero se nos pudo haber pasado un poco la mano en lo que respecta a la dificultad del preprocesamiento de los datos para poder obtener dicha información(la relación entre compra y tienda), probablemente hoy en la tarde hagamos una dicho csv con el objetivo de poder facilitarles un poco más dicho trabajo(la idea tampoco es que se enfoquen solamente en preprocesar los datos pues no se busca evaluar precisamente eso en esta entrega).
