### ISSUE TITLE
Duda sobre datos de compras

### ISSUE THREAD

**Issue by domingo2000** [IIC2413/Syllabus-2021-1#143]
Hola, me surge una duda a la hora de leer los datos de compra, y es que en el archivo `compras.csv` se se tienen las siguientes tuplas 
| id  | comprador | direccion | producto | cantidad |
|-----|-----------|-----------|----------|----------|
| 223 | 26        | 607       | 393      | 3        |
| 223 | 26        | 607       | 393      | 4        |
<br>
Y no entiendo como interpretarlos, pues para mi que el id de la compra debería ser unico para cada compra, y como se tienen varios productos entonces se tiene una relacion entre productos y compras, haciendose una tabla con primary key (id_compra, id_producto), pero en este caso se repiten ambos valores y solo cambia la cantidad. Están erroneos los datos o se puede tener el mismo producto varias veces distintas en la misma compra, o debo yo sumar las cantidades al procesar los datos?

**Comment by arpincheira** [comment]
Hola, la idea original es que en el preprocesamiento de datos sumen las cantidades de productos repetidos al interior de una misma compra, de lo contrario  su base de datos presentaría inconsistencias gracias a los datos que expones en esta issue.

**Comment by domingo2000** [comment]
Ok gracias!
