### ISSUE TITLE
Duda Sobre LLaves Foráneas

### ISSUE THREAD

**Issue by domingo2000** [IIC2413/Syllabus-2021-1#144]
Hola, me surge una duda, que pasa si tengo un atributo que es foraneo en ambas tablas, me explico, la relación
`Tienda(id, jefe)` Tiene un jefe, y la relación `Trabajadores(id, nombre, tid)` representa quienes trabajan en que tienda, para la tabla de tiendas el jefe debe existir en los trabajadores, por otro lado para la tabla de trabajadores debe existir la tienda  para tid por lo tanto también es foránea. Esto resulta que a la hora de insertar un dato no pueda hacerlo, puesto que es foranea en ambas tablas, por lo que no puedo meter las tiendas sin jefe ni los jefes sin tienda. Como se soluciona esto, tengo algún problema de ambiguedas o es otro tipo de problema, debería sacarla la foreign key a la tienda y dejar que se pueda tener un jefe que no está reflejado en el personal?

**Comment by arpincheira** [comment]
Hola, en primer lugar te solicito que no compartas información sobre tu resolución de la entrega por las issues. Ahora, en lo que respecta a tu duda, postgres te permite añadir ciertas restricciones en las tablas luego de haberlas creado, te recomiendo buscar más información al respecto en [este link](https://www.postgresql.org/docs/9.1/sql-altertable.html)

**Comment by domingo2000** [comment]
Ok seré mas cuidadoso a la hora de preguntar :grimacing:. Gracias por la respuesta!
