### ISSUE TITLE
Duda solución guía de diseño

### ISSUE THREAD

**Issue by mc-cari** [IIC2413/Syllabus-2021-1#145]
Hola, porque no se definieron tablas para las relaciones en el esquema ER por ejemplo en la relación Está_en, o en que caso son necesarias?

**Comment by ValentinaAlvarezG** [comment]
Hola! lo que pasa es que ``Está_en`` es una relación 1:N así que no es necesario hacer una tabla intermedio, en cambio en ``ObraDeArte`` se define el ``lid`` en que está. En general haces una tabla intermedia cuando tienes relaciones N:N.

**Comment by mc-cari** [comment]
Ok, gracias!
