### ISSUE TITLE
Duda Consulta 6 del Control 2

### ISSUE THREAD

**Issue by JoMarchant** [IIC2413/Syllabus-2021-1#149]
Hola!

Me surgió una duda respecto a la consulta 6, cuando dice "productos que tengan el mismo nombre":
![image](https://user-images.githubusercontent.com/69648244/116483487-2d433d80-a855-11eb-98fd-9f503f630947.png)

 ¿Se refiere a ```name``` de la tabla ```Products```? , ¿o el nombre completo con ```name_suffix``` de la tabla ```Variants```?

Muchas gracias :)

**Comment by ValentinaAlvarezG** [comment]
Hola, se refiere a ``name`` de ``Products``.
