### ISSUE TITLE
Duda solución pregunta 3 - Guía 1

### ISSUE THREAD

**Issue by Gustav2000** [IIC2413/Syllabus-2021-1#15]
Hola, la pregunta 3 dice: **Encuentre los tours que visitan al menos 2 viñas**
Resulta que al final, al hacer una proyección (pi), nos quedamos con solo los _tid_, sin embargo estos perfectamente podrían estar repetidos varias veces. O no importa si es que los nombres de las viñas se repiten en el resultado final.

Ej: 
| SV1.tid | SV1.vid | SV2.tid | SV2.vid |
|---------|---------|---------|---------|
| 3  | 5 | 3 | 2 |
| 3  | 5 | 3 | 1 |
| 3  | 5 | 3 | 4 |
| ...|...|...|...|

Y luego al hacer la proyección nos quedaría varias veces el número 3.

**Comment by ValentinaAlvarezG** [comment]
Hola! en álgebra relacional no hay duplicados, por lo que, por ejemplo, al hacer la proyección de SV1.tid en esa tabla que muestras, se eliminan los duplicados y te quedaría solo el 3.

**Comment by Gustav2000** [comment]
Ohhh buenísimo, gracias.
