### ISSUE TITLE
[Control 2] Esquema de la base de datos parece ser incorrecto

### ISSUE THREAD

**Issue by benjavicente** [IIC2413/Syllabus-2021-1#150]
En el archivo de `metadata.md` se especifica que:

> ## Bills
> Ventas de cada tienda.
> 
> * **`created_at(date  not null)`: Fecha de creación.**

pero al correr la consulta:

```sql
SELECT DISTINCT typeof(created_at) FROM Bills;
```

se obtiene que

```txt
typeof(created_at)
--
text
```

por lo que el tipo de `created_at` no calza con lo especificado.

---

### Edit 
Agrego que también se especifica que

> ## Variants
> Variantes de un producto, es decir distintas versiones, por ejemplo distinto color o edición.
> 
> * `is_master(varchar not null)`: **Booleano (varchar con valores `True` o `False`)** que representa si es que esta es la variable "master" del producto, es decir la principal o por defecto.

La consulta para ver que valores tiene es

```sql
SELECT DISTINCT is_master FROM Variants;
```
y retorna

```txt
is_master
--
true
false
```
 por lo que los valores no son `True` o `False`, si no que `'true'` y `'false'`.

**Comment by ValentinaAlvarezG** [comment]
Hola! no afecta en nada, lo que pasa es que parece que sqlite3 guarda las fechas como strings, pero las consultas funcionan igual como las hemos visto en clases y en el semestre en general, así que no debería ser problema.

**Comment by benjavicente** [comment]
Parece que no necesariamente se guardan como strings, de hecho, llegue a [esta pregunta que estaba el la misma situación que yo](https://stackoverflow.com/questions/650480/get-month-from-datetime-in-sqlite), donde se trataba de usar una función para obtener la fecha (año y mes) y se obtenía un `None`, probablemente porque la fecha ya estaba en el formato de string.

**Comment by ValentinaAlvarezG** [comment]
Mi punto es, no importa si no es de tipo date, aunque sea texto igual puedes hacer las consultas que te pedimos relacionadas con la fecha.

**Comment by dpacevedo** [comment]
Hola! En este sentido, si sqlite3 guarda las fechas como string no nos servirían los tips de la pregunta 13, o debemos convertirlas a formato date para poder usarlos?

Gracias de antemano! :sunflower:

**Comment by ValentinaAlvarezG** [comment]
Tranqui, según yo funciona igual! tu dale no más y úsalo como si fuera date.

**Comment by domingo2000** [comment]
Hola respecto a esto mismo, leyendo foros decía que si uno usaba LIKE para buscar fechas en vez de funciones implementadas en la DBMS como MONTH resulta que se hace mucho mas ineficiente la consulta porque itera por todos los valores buscando el match de la expresión regular en vez de moverse por los indexes de fechas, por lo que me pregunto como se haría en este caso para consultar por fechas especificas dado que como dice @benjavicente más arriba, al usar la funcion strfdate de sqlite en este caso devuelve None al evaluarla sobre una fecha porque al parecer no están en formato fecha sinó que string.

**Comment by ValentinaAlvarezG** [comment]
Hola! no te compliques tanto, prueba con lo que es más intuitivo.

**Comment by Jamesmoreno21** [comment]
Hola! Respecto a los datos booleanos, tengo el problema de que sólo los puedo operar como strings, como el "true" y "false", por ejemplo, para el caso de "is_master" . Al poner = TRUE o = FALSE no me lo distingue como bool. Probé con los strings y si funciona, entonces no sé cómo dejarlo para la evaluación o si comentar esto. Gracias de antemano

**Comment by Jamesmoreno21** [comment]
Yaa, muchas gracias!
