### ISSUE TITLE
[control 2] Duda consulta 7

### ISSUE THREAD

**Issue by nicogrecod18** [IIC2413/Syllabus-2021-1#151]
Hola, me surgió una duda en la consulta 7, en donde nos piden la cantidad de unidades vendidas de cada producto en cada tienda.
Influye el status de la compra en cada venta ? Es decir, debemos considerar aquellas ventas en que su status es deleted o awaiting payment ?
Gracias de antemano

**Comment by ValentinaAlvarezG** [comment]
Hola! no influye, da lo mismo el status que tenga

**Comment by nicogrecod18** [comment]
Gracias !!
