### ISSUE TITLE
Duda setup Control 2

### ISSUE THREAD

**Issue by tcouso** [IIC2413/Syllabus-2021-1#152]
Hola!

Estoy teniendo problemas con el setup del control 2. Al parecer se están cargando bien la extensión sql y la base de datos, pero cuanto ejecuto la consulta de prueba me sale el siguiente error:
`* sqlite:///tu_shop_mini.db
(sqlite3.OperationalError) no such table: Bills
[SQL: SELECT COUNT(*) FROM Bills]`
Googlé un poco y no encontré  una respuesta que clarificara por qué podría pasar esto, por lo que agradezco mucho cualquier ayuda.

Saludos!

**Comment by tcouso** [comment]
Al final logré resolverlo por mi cuenta importando la base de datos desde mi computador a colab. Igual dejo el issue por si a alguien llegara a servirle. 

Saludos!

**Comment by ValentinaAlvarezG** [comment]
Bacan!

**Comment by pabloalvarez67** [comment]
Yo tengo ahora el mismo problema. Ayer pude trabajar perfecto pero hoy no puedo.
Intenté borrando la base de datos de collab y luego subirla denuevo, pero me sigue levantando el mismo error.

**Comment by ValentinaAlvarezG** [comment]
Si no me equivoco, deberías correr de nuevo las celdas que tenían: ``%load_ext sql`` y ``%sql sqlite:///tu_shop_mini.db`` no sé si lo hiciste.

**Comment by pabloalvarez67** [comment]
> Si no me equivoco, deberías correr de nuevo las celdas que tenían: `%load_ext sql` y `%sql sqlite:///tu_shop_mini.db` no sé si lo hiciste.

SI, siempre lo hago!

**Comment by ValentinaAlvarezG** [comment]
Y te tira este error:  ``sqlite:///tu_shop_mini.db (sqlite3.OperationalError) no such table: Bills [SQL: SELECT COUNT(*) FROM Bills]``  ???

**Comment by pabloalvarez67** [comment]
> Y te tira este error: `sqlite:///tu_shop_mini.db (sqlite3.OperationalError) no such table: Bills [SQL: SELECT COUNT(*) FROM Bills]` ???

Ese mismo error.

**Comment by ValentinaAlvarezG** [comment]
Quizás en algún momento corriste ``%sql sqlite:///tu_shop_mini.db`` esta celda sin que estuviera en colab el archivo  .db? porque en ese caso se te crea esa base de datos vacía entonces quizás por eso te dice que no encuentra la tabla. Fíjate bien que el .db que esté arriba en colab sea el que les subimos y corre de nuevo las dos celdas que te dije.

**Comment by tcouso** [comment]
> > Y te tira este error: `sqlite:///tu_shop_mini.db (sqlite3.OperationalError) no such table: Bills [SQL: SELECT COUNT(*) FROM Bills]` ???
> 
> Ese mismo error.

Me pasó lo mismo ahora que ingresé nuevamente, al parecer colab borra los archivos que uno sube cuando reinicia la consola. Pude corregirlo reiniciando el entorno de ejecución y asegurándome que la ruta de la base de datos estuviera correcta (cuando la subí nuevamente usé otro directorio sin fijarme, de modo que la primera vez que intenté abrirla no funcionó). Puedes asegurarte que la ruta es la correcta copiándola directamente desde el archivo de la base de datos que subiste (botón derecho y luego click en "copiar ruta de acceso"). No sé si ya lo resolviste, pero lo comento por si te sirviera. 

Saludos!
