### ISSUE TITLE
Duda Consulta 8 del Control 2

### ISSUE THREAD

**Issue by JoMarchant** [IIC2413/Syllabus-2021-1#153]
Hola!

Tengo varias dudas respecto a la consulta 8:

![image](https://user-images.githubusercontent.com/69648244/116492398-2a067c80-a86a-11eb-8f60-caea84c1ad68.png)

* ¿Se piden las ventas de todos los meses marzo?
* Cuando dice "(en $$$)", ¿se refiere a agregar ```$``` al final del numero?
* ¿En que orden se ponen las ventas?

Gracias de antemano :)

**Comment by ValentinaAlvarezG** [comment]
Hola!,
Sobre lo primero, si te fijas las fechas van desde mayo del 2020 a abril 2021, así que en realidad son las ventas de marzo 2021. Lo segundo, no, solo era para aclarar que estamos hablando de dinero. Tercero, dado que no se especifica, se asume ascendente.

**Comment by MaxWhiting** [comment]
Hola tengo otra duda de esa misma consulta, debemos mostrar el total de ventas para cada tienda(sumar todas las ventas de esa tienda en marzo)? o cada venta especifica que se realizo en cada tienda?

**Comment by ValentinaAlvarezG** [comment]
La idea es que sea el total de ventas para cada tienda (y bueno, en marzo).

**Comment by denisseleiva** [comment]
Holaa me sumo a esta duda, si es el total de ventas para cada tienda, no habría orden o si? Yo lo había pensado como que había que mostrar todas las ventas para cada tienda una por una, y de ahí ordenarlas (según monto supongo)

**Comment by ValentinaAlvarezG** [comment]
Mmmm si hay orden, por ejemplo si la tienda 1 vendió en total 1000 y la tienda 2 vendió en total 2000, primero pones la tienda 1 y luego la 2, porque eso sería en orden ascendente según ventas.

**Comment by denisseleiva** [comment]
Ahhh yaya entiendo perfect, gracias!!!!!

**Comment by nicogrecod18** [comment]
Los precios en billvariants ya tienen aplicado el descuento ? o debemos aplicarlo para calcular las ventas totales ?

**Comment by ValentinaAlvarezG** [comment]
Al momento de hacer la consulta tienes que tú aplicarle el descuento al precio.

**Comment by CamilaArgomedo** [comment]
¡Hola! tengo una duda en esta misma consulta ¿Debo entregar solo una columna con los valores? ¿o debo indicar a que tienda corresponden también en otra columna? Si es así, ¿Basta con id o debo indicar el nombre?

**Comment by ValentinaAlvarezG** [comment]
Hola! deberías tener una columna con  la tienda, ojalá con el nombre.
