### ISSUE TITLE
Duda Bills y BillVariants

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2413/Syllabus-2021-1#155]
Hola. Tengo una confusión respecto a estas dos tablas. En Bills aparecen todas las ordenes de compra (con cualquier tipo de status) y en BillVariants aparecen todas las que efectivamente ya se realizaron? No entiendo muy bien la diferencia. También el created_by de cada una debería ser el mismo por orden?

**Comment by ironcadiz** [comment]
Hola, BillVariants representa las distintas variantes que fueron incluidas en una venta (Bill). En otras palabras la tabla representa una relación N:N entre Bills y Variants (una venta puede incluir n variantes distintas y una variante se puede haber vendido n veces).

**Comment by fmitjans** [comment]
Entonces cuando nos piden analizar ventas por fechas ¿Usamos las de BillVariants o la de Bills? ¿O da lo mismo?

**Comment by ironcadiz** [comment]
La de `Bills`
