### ISSUE TITLE
[Control 2] Duda Consulta 12

### ISSUE THREAD

**Issue by fedezang** [IIC2413/Syllabus-2021-1#156]
Hola!
Quería saber si en la consulta, cuando se pide que un cliente haya comprado antes de abril, se refieren a que haya comprado antes de abril del 2021, o de cualquier año?
Gracias!

**Comment by ValentinaAlvarezG** [comment]
Hola! lo consideramos antes de abril 2021.

**Comment by fedezang** [comment]
Perfecto gracias!
Tengo una duda similar para las otras consultas,
Alguna piden ventas en marzo de 2021 y otras solo dicen marzo.
Todas se refieren a marzo del mismo año?

**Comment by ValentinaAlvarezG** [comment]
Si, considera en general  siempre 2021.

**Comment by IgnaciaJ** [comment]
Hola! Una duda con esta misma consulta el porcentaje lo consideramos en el total de clientes o solo los que compraron en el mes de abril? Por otro lado se debe ver el estado de las compras o no es necesario?

**Comment by ValentinaAlvarezG** [comment]
Es sobre el total de clientes. El estado de la compra da lo mismo.

**Comment by Jamesmoreno21** [comment]
Una consulta sobre el porcentaje del total de clientes frecuente, es sobre el total de clientes en todos los periodos? (frecuentes abril/todos) o se refiere a los frecuentes en relación al total hasta el final de abril? (frecuentes abril/totales hasta final de abril)

Gracias de antemano!

**Comment by ValentinaAlvarezG** [comment]
Hola! creo que eso es parte de lo que deberían ver ustedes.
