### ISSUE TITLE
[Control 2] Duda consulta 10

### ISSUE THREAD

**Issue by acastill20** [IIC2413/Syllabus-2021-1#157]
La consulta es la siguiente: 10. El nombre y precio de la variante con el precio más caro. 
Mi pregunta es, cuando hablan de variante en esta consulta, debemos tomar todas las variantes o solo las que tienen is_master = false.
Lo otro, si es que hay más de una con el mismo precio más caro, muestro ambas, solo 1 o da lo mismo?

**Comment by ValentinaAlvarezG** [comment]
Sobre lo primero, no necesariamente ``is_master = false``. Sobre lo segundo, si hay dos que cumplen con ser la más cara, deberías mostrar las 2.

Otra cosa, no entiendo porque en el nombre de la issue pusiste que tenías una duda con la consulta 8, si tu consulta es sobre la 10 jajaja.
