### ISSUE TITLE
Duda con el status de una venta

### ISSUE THREAD

**Issue by Francisco5674** [IIC2413/Syllabus-2021-1#158]
Hola a todos!
Mi duda esta en que ¿si debemos tomar en cuenta a una variante como vendida solo cuando se encuentra en la tabla BillsVariants o además debemos chequear que la Bill correspondiente tenga un status que verifique que la venta se logró?, por ejemplo ¿una venta que tenga estado "deleted" o "awainting payment" técnicamente no se ha vendido, o las tomo en cuenta de todas formas?

**Comment by ValentinaAlvarezG** [comment]
Hola, hablé un poco de esto en la issue #151, da lo mismo el estado de la venta a menos que en el enunciado de la pregunta salga de forma explicita.

**Comment by Francisco5674** [comment]
Bkn gracias
