### ISSUE TITLE
Duda contenido Control 1

### ISSUE THREAD

**Issue by JoMarchant** [IIC2413/Syllabus-2021-1#16]
Hola! Tengo una duda respecto a un operador ¿Está bien usar conjunciones en el condicional de un "Join"? 
Ejemplo:
![image](https://user-images.githubusercontent.com/69648244/112536114-d3e67b00-8d8b-11eb-9708-5409cef1f14c.png)

**Comment by ValentinaAlvarezG** [comment]
Hola! si, no hay problema con usar conjunciones en el join.
