### ISSUE TITLE
Duda productos Distintos control

### ISSUE THREAD

**Issue by domingo2000** [IIC2413/Syllabus-2021-1#160]
Hola, me surge una duda en las consultas que tienen que ver con los productos, consideramos que un producto con el nombre igual es el mismo producto para todas las consultas o solamente para la consulta 6. Por ejemplo en la consulta 7 que piden la cantidad de productos vendidos, si fuera 
| id_tienda | id_producto | nombre_producto | cantidad |
|-----------|-------------|-----------------|----------|
| 0         | 1           | Civilization V  | 1        |
| 0         | 2           | Civilization V  | 3        |
<br> 
Los tomo como el mismo producto o los tomo como dos productos diferentes??

**Comment by ValentinaAlvarezG** [comment]
Hola!, en esta pregunta (la 7) se consideran diferentes.
