### ISSUE TITLE
[Control 2] Duda Consulta 9

### ISSUE THREAD

**Issue by CrisBerriosL** [IIC2413/Syllabus-2021-1#161]
Hola! La consulta 9 indica lo siguiente:

``Los ids de las variantes que no han tenido ninguna venta en marzo y tienen stock disponible.``

Mi duda es, ¿se refiere a variantes que no han tenido ventas en marzo de 2021? ¿O se refiere a cualquier marzo de cualquier año?

**Comment by ValentinaAlvarezG** [comment]
Hola! ventas de marzo de 2021

**Comment by rmena1** [comment]
Hola! en esta misma consulta, son las variantes que no han tenido ventas en ninguna tienda y que tengan stock en alguna tienda? o tenemos que dar el resultado por cada tienda? Esto suponiendo que pueden haber 2 o más tiendas que vendan la misma variante.

**Comment by ValentinaAlvarezG** [comment]
Hola! lo primero que dijiste.

**Comment by rmena1** [comment]
Gracias!

**Comment by dedmu5** [comment]
> Hola! ventas de marzo de 2021

Hola, tengo que aplicar la misma interpretación para la pregunta 8 entonces? Porque también me dicen de marzo solamente, pero no se si de cualquier año

**Comment by ValentinaAlvarezG** [comment]
Hola, para todo considera 2021 no más.
