### ISSUE TITLE
Duda Consulta 2 con el formato de las fechas

### ISSUE THREAD

**Issue by mpbosnic** [IIC2413/Syllabus-2021-1#163]
Hola!

En la consulta 2, ¿podemos retornar la fecha de creación sin el indicador de zona horaria? Por ejemplo, si tengo el string "2021-03-01 21:46:34 -0300" ¿puedo retornarlo en UTC como "2021-03-02 00:46:34" ?

Gracias!

**Comment by ValentinaAlvarezG** [comment]
Puedes, da lo mismo en verdad si lo retornas o no con la zona horaria. Pero supongo que es más simple si lo retornas con, pero da lo mismo.

**Comment by mpbosnic** [comment]
Gracias!

**Comment by mpbosnic** [comment]
¿Debemos considerar el comienzo y final de meses en UTC también? Creo que esto influye en el resultado de las consultas. Por ejemplo, si considero las ventas en Marzo, el resultado es distinto dependiendo si considero esa diferencia horaria.

**Comment by ValentinaAlvarezG** [comment]
Mmm da un poco lo mismo, onda cuando hagas las comparaciones correspondientes preocúpate de que sea Marzo de 2021 no más

**Comment by mpbosnic** [comment]
Gracias, te pasaste
