### ISSUE TITLE
[control 2] Consulta 4 

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2413/Syllabus-2021-1#164]
En la consulta 4 me entrega resultados que son duplicados. En dicho caso lo debo dejar así ya que cada fila pertenece a una variante diferente o lo debiese agrupar para eliminar los duplicados?

**Comment by ValentinaAlvarezG** [comment]
Duplicados de que? de filas enteras? o solo del nombre de la variante? Si cada fila es de una variante distinta está bien.

**Comment by enriquemolinare** [comment]
Cuando hago la consulta 4 me entrega filas enteras duplicadas. Sin embargo, revisé los id.variants de cada fila y son todos distintos. Por lo que cada fila es una variante diferente

**Comment by ValentinaAlvarezG** [comment]
Entonces todo ok.
