### ISSUE TITLE
[Control 2] Duda Consulta 14

### ISSUE THREAD

**Issue by mc-cari** [IIC2413/Syllabus-2021-1#165]
Hola, qué es lo que hay que contar en la consulta? cantidad de productos vendidos, ganancias, ventas(boletas)?

**Comment by ValentinaAlvarezG** [comment]
Hola! No te puedo dar tanto detalle sobre esto, pero tienes que saber cuantas **ventas** se hicieron.

**Comment by mc-cari** [comment]
Vale, gracias.
