### ISSUE TITLE
Duda Unclustered Hashed Indexes con índice diferente al filtro

### ISSUE THREAD

**Issue by AAVP** [IIC2413/Syllabus-2021-1#166]
En la clase sobre almacenamiento e índices aprendimos a cómo calcular el costo I/O en un Hash Index Unclustered con un índice que podía ser o no la llave primaria. Sin embargo, en tales casos siempre se evaluaron consultas usando como filtro el mismo atributo que se usaba como índice (por ejemplo, si el hash índex unclustered creaba buckets a partir de un índice A, en los ejemplos de la clase evaluaban una consulta con A mayor, igual o menor a un valor).
Ahora, para el control 2 no solamente se pide hacer ese tipo de cálculos, sino que también me piden calcular el costo con un Hash Index Unclustered formado con un atributo A (en este caso el promedio) pero evaluando una consulta que filtra por un atributo B (el id o el nombre por ejemplo). Entonces, cómo se hace para calcular los costos I/O en esos casos?

**Comment by ValentinaAlvarezG** [comment]
Hola! aquí lo que tendrías que pensar es ¿qué pasa si quieres filtar por un atributo b, pero tienes tu bd indexada por el atributo a? no te puedo dar la respuesta porque es parte de lo que tienes que saber para el control, pero piensa en eso. En la guía se da el caso por ejemplo de que no tienes ningún índice :eyes: y tienes que hacer todas las consultas :eyes: solo eso diré.

**Comment by nicogrecod18** [comment]
entonces tendríamos que  calcular el valor esperado de tuplas ?

**Comment by ValentinaAlvarezG** [comment]
tienes que calcular el costo I/O igual que como se hace en la guía

**Comment by mpbosnic** [comment]
Hola! Creo que me confundí con la respuesta a esta issue. En el control nos piden evaluar las consultas con cada índice a disposición (hash y B+ tree). Entonces, por lo que entiendo, en ningún caso tendríamos que evaluar el caso en que no tengamos índices o no? (incluso si este puede ser más eficiente)

**Comment by mpbosnic** [comment]
Sisi. Para confirmar entonces, cuando me piden evaluar una consulta con un índice, debo usar este índice sí o sí verdad? Por ejemplo, si me piden usar índice hash pero esto resulta menos eficiente que hacer la consulta sin índice, ¿de todas formas tengo que poner el costo de hash verdad?

**Comment by ValentinaAlvarezG** [comment]
Si po, primero las evalúas con solo un índice (independiente de si es eficiente para esa consulta o no) y luego considerando solo el otro.
