### ISSUE TITLE
Duda eficiencia del Hush Index

### ISSUE THREAD

**Issue by Francisco5674** [IIC2413/Syllabus-2021-1#167]
Hola a todos
Mi problema es con respecto a la eficiencia del hush index, digo, a pesar de ser una buen Index, ¿es posible que algunos casos sea más deficiente simplemente revisar todas las paginas del disco verdad? a lo que me refiero, ¿no siempre es cierto que reduces el costo de una consulta a través de un hush? ¿puede exister un caso donde los buckets sean relativamente pocos, o que existan demasiadas overflow pages, tanto así, que es más fácil simplemente consultar todas las paginas del disco?

**Comment by DomagojVrgoc** [comment]
Si, es posible.

La guía qué hicimos sirve para ilustrar estas cosas. Cómo dijimos en las clases, un índice es cómo una interfáz a la cual la base de datos pregunta ciertas tuplas, y puede servir en algunos casos, y no servir en otros.

Por ejemplo, si yo tengo un índice hash sobre el atributo A, y hago una busqueda de tuplas con A = 25, lo más probable es qué me vaya bien (índice hash se luce para este tipo de consultas). Ojo qué en el caso qupe A sea una llave, la búsqueda es super eficiente (1 o 2 páginas). Si A no es llave, puede ser qué exista muchas tuplas con A = 25 (por ejemplo si A guarda la edad de usuarios), y allá el costo puede ser mayor que 1 o 2 (en el peor de los casos es el número de tuplas qu´q tienen A = 25).

Por el otro lado, tengo índice hash por A, y quiero hacer una búsqueda por el valor del B, mi índice efectivamente no sirve para nada (i.e. tengo qupe recorrer todas las tuplas en este caso).

Con las consultas de rango la cosa anda peor por lo general. I.e. si necesito 25 <= A <= 50, necesito preguntar a mi índice por todos los valore intermedios.
