### ISSUE TITLE
Problema con operador de consulta 4

### ISSUE THREAD

**Issue by totaurt** [IIC2413/Syllabus-2021-1#168]
Holaa! Tengo un problema al utilizar || para concatenar, cada vez que corro el código se me pega el Jupyter Notebook y no puedo avanzar con la consulta:(

**Comment by AAVP** [comment]
Sé que no es una solución a tu problema, pero mientras podrías ir probando el mismo código en un Google Colab, tal como lo han recomendado los ayudantes!

**Comment by ValentinaAlvarezG** [comment]
Eso :c pucha no sé porque jupyter se te quedará pegado, pero colab siempre es opción.

**Comment by totaurt** [comment]
Bueno, gracias igual a ambos:) lo intentaré de nuevo cuando me cambie a Google Colab

**Comment by totaurt** [comment]
Holaa! lo intenté y no me funciona ni en Google Colab ni en Jupyter Notebook (antes estaba en Visual Studio, me equivoqué). No sé qué puede estar pasando, por favor si me pueden ayudar

**Comment by ValentinaAlvarezG** [comment]
Me puedes dar más info? onda que error te tira?

**Comment by totaurt** [comment]
No me da ningún error. En las tres me sale Done y luego el programa dice estar corriendo el código y se cae. No sé si puedo enviarte el código por interno, porque quizá lo esté definiendo mal

**Comment by ValentinaAlvarezG** [comment]
Eeeem mandame una foto con la parte donde se cae a vjalvarez@uc.cl
