### ISSUE TITLE
[Control 2] Duda con Productos y Variantes

### ISSUE THREAD

**Issue by margavicunas** [IIC2413/Syllabus-2021-1#169]
Hola! 
No me queda claro si puede haber un producto que no tenga variante, porque, si es así, ¿cuál esquema indica cuál producto se compró? ¿no debería haber un BillProducts en ese caso? 

Gracias!

**Comment by ValentinaAlvarezG** [comment]
Recuerda que la tabla de variantes tiene `is_master`.

**Comment by margavicunas** [comment]
Pero es que por qué tendría que ingresar un producto a Variants si no tiene variantes? Me hace sentido ingresarlo cuando sí tiene variantes porque un producto al tener variantes se convierte en "variante madre", pero cuando no tiene no veo por qué agregarlo :(

**Comment by ValentinaAlvarezG** [comment]
O sea es que así es el esquema que les pasamos. Variantes guarda la referencia a qué producto corresponde y te dice si es que es el default (master) o no. Mmm si lo ves en un diagrama ER vas a tener la entidad Producto y la entidad Variante y lo que pasa es que es una relación 1:N donde un Producto puede tener N variantes y cada Variante corresponde a un solo producto. y Variantes se relaciona con Bills en una relación N:N.

**Comment by margavicunas** [comment]
Gracias!! jiji
