### ISSUE TITLE
[Control] Duda Consulta 10 

### ISSUE THREAD

**Issue by nicolecll** [IIC2413/Syllabus-2021-1#171]
Hola, en la consulta 10 dice 'El nombre y precio de la variante con el precio más caro' sin embargo las variantes no tienen un nombre como tal, solo un sufijo. Cuando dice nombre se refiere al nombre del producto del cual es variante?

**Comment by ValentinaAlvarezG** [comment]
Hola!, tendría que ser el nombre del producto más el sufijo de la variante.
