### ISSUE TITLE
Duda "venta" Consulta 14

### ISSUE THREAD

**Issue by mpbosnic** [IIC2413/Syllabus-2021-1#175]
Hola!

¿Qué se entiende por una venta? Por ejemplo, si la tienda emite una boleta (Bill) con 20 productos (BillVariants), ¿esto cuenta como una venta o como 20?

Gracias!

**Comment by ValentinaAlvarezG** [comment]
Hola! si emite una boleta (una Bill) eso es **una** venta, independiente de cuantos productos tenga.

**Comment by mpbosnic** [comment]
Gracias!
