### ISSUE TITLE
Consulta 8 y 11

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2413/Syllabus-2021-1#176]
Hola, en el caso que las tiendas no tengan ventas en marzo, es necesario agregarlas en la lista con su valor 0 o se puede asumir que al no estar en la lista es porque tienen ventas iguales a 0.

Saludos

**Comment by ValentinaAlvarezG** [comment]
Hola, probablemente si la tienda no tuvo ventas no te va a salir, porque no hay una bill asociada, así que tranqui, no es necesario que salga.

**Comment by chineseJack564** [comment]
Hola,
En estos 2 consultas, consideramos el valor de una venta como la suma de todos las BillsVarints quienes tienen el mismo bill_id?
O asumimos una venta como cada BillsVarints con id distinto?

**Comment by ValentinaAlvarezG** [comment]
Hola! creo que no puedo responder tu pregunta, es demasiado específica.  Solo recuerda que en la 8 debes entregar el nombre de cada tienda junto con el valor de sus ventas, y en la 11 cada tienda junto con el valor promedio de sus ventas. Según el esquema entregado y el detalle que se encuentra en ``metadata.md`` debes distinguir cuales usar.

**Comment by sbvillalobosm** [comment]
> Hola! creo que no puedo responder tu pregunta, es demasiado específica. Solo recuerda que en la 8 debes entregar el nombre de cada tienda junto con el valor de sus ventas, y en la 11 cada tienda junto con el valor promedio de sus ventas. Según el esquema entregado y el detalle que se encuentra en `metadata.md` debes distinguir cuales usar.

Hola! Con respecto a esto, en la 8 se espera el **total** de ventas de cada tienda en el mes de marzo (como un solo valor para cada tienda) o tenemos que mostrar **cada una** de las ventas en el mes de marzo de cada tienda?

**Comment by ValentinaAlvarezG** [comment]
Hola! el total de cada tienda.
