### ISSUE TITLE
Consulta precios productos

### ISSUE THREAD

**Issue by nicolaszanni** [IIC2413/Syllabus-2021-1#177]
Hoa, me di cuenta que en los productos que efectivamente tienen variantes, el producto master posee un precio de 1, ¿ A qué se debe esto?. Y otra pregunta: ¿Se puede el producto sin variante aunque lo tenga, por ejemplo vender un Far cry, sin necesariamente vender un Far Cry 4 o Far Cry 5?

**Comment by ValentinaAlvarezG** [comment]
Hola! sobre lo primero da lo mismo en verdad, coincidencia. Sobre lo segundo, siempre es la variante la que se vende, así que ahí depende de cual sea el nombre del producto y cual es el sufijo.
