### ISSUE TITLE
Consulta 11

### ISSUE THREAD

**Issue by Natydlb** [IIC2413/Syllabus-2021-1#178]
Hola! en la 11 el valor promedio de venta se calcula con los descuentos asociados a cada compra?

**Comment by ValentinaAlvarezG** [comment]
Hola! si, tienes que aplicarle los descuentos

**Comment by camirojasguajardo** [comment]
> 
> 
> Hola! si, tienes que aplicarle los descuentos

Hola! una consulta, en el archivo metadata, se indica que BillVariants.price es el "Precio de la variante al momento de concretarse la venta.", o sea que este precio incluye el descuento? en tanto el precio con descuento era el precio al momento de la venta

**Comment by ValentinaAlvarezG** [comment]
Hola! no, no incluye el descuento. El precio de BillVariants es el precio de la variante al momento de la compra, que puede ser diferente al del producto. Aparte de eso tienes el tema del descuento que se lo tienes que aplicar.

**Comment by camirojasguajardo** [comment]
Gracias por la respuesta!
