### ISSUE TITLE
Consulta 12

### ISSUE THREAD

**Issue by allisonaguilar** [IIC2413/Syllabus-2021-1#179]
Hola! En la consulta 12 me surge la duda si las condiciones deben cumplirse para la misma tienda o no. Es decir, si se debe buscar a los clientes que compraron antes de abril en la tienda X y vuelvan a comprar en abril en la tienda X, o solo basta con que compren en ambos periodos en cualquier tienda.

Gracias!

**Comment by ValentinaAlvarezG** [comment]
Hola! no tiene que cumplirse para la misma tienda, es en general no más.
