### ISSUE TITLE
Duda enunciado pregunta 6 control

### ISSUE THREAD

**Issue by Huasito-Appel** [IIC2413/Syllabus-2021-1#18]
Hola, no tengo muy claro que sucede con las consultas(proyeccion) en caso de que existan 2  elementos con el mismo atributo, como es el caso de 2 grahams de diferente nombre y misma altura, siendo ambos el "mas alto".
Por lo que para resolverlo estoy asumiendo que esto no sucede. Esta bien asumir esto o debo corregir mi formulacion de la consulta?

**Comment by DomagojVrgoc** [comment]
Esto si puede ocurrir.

Piensa si tu solución detectará estos casos.

Si no, quizás tienes un error en la elaboración.
