### ISSUE TITLE
Parte 2: Indices

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2413/Syllabus-2021-1#181]
No entiendo la asignación de puntajes. Si bien cada pregunta vale 0.1 puntos. Solo nos preguntan el costo de 5 consultas. Entonces el total sería 0.5 y no 1 punto.
Quizás en cada consulta hay que sacar el costo de ambas formas ?  
Lo otro, se debe calcular el costo I/O tal como lo hicimos en la guía o el costo logaritmico?

**Comment by ValentinaAlvarezG** [comment]
Hola! en uno de los comentarios de la issue #166 hable un poco sobre esto.
