### ISSUE TITLE
[Control 2] Consulta 7

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2413/Syllabus-2021-1#182]
Hola! tengo una duda sobre lo que me piden en el enunciado, ¿debo calcular el total de productos vendidos por tienda o calcular el total por producto de cada tienda?

Gracias :)

**Comment by ValentinaAlvarezG** [comment]
Hola! la idea es que digas algo como en esta tienda 'x', el producto 'y' se vendió en cantidad 'z', no sé si ahí se entiende mejor.

**Comment by Margarita-Paz** [comment]
sii, gracias!
