### ISSUE TITLE
Consulta 7 del control 2

### ISSUE THREAD

**Issue by CamilaArgomedo** [IIC2413/Syllabus-2021-1#183]
esta consulta dice: "La cantidad de unidades vendidas de cada producto en cada tienda." ¿Debo entregar **una** columna con la cantidad solicitada con una fila por cada tienda? ¿o debo especificar también el nombre de la tienda? ¿o diferenciar por cada producto?

**Comment by ValentinaAlvarezG** [comment]
Hola! creo que lo que preguntas lo acabo de responder en la issue #182, avísame si es que no quedó claro de eso.
