### ISSUE TITLE
[CONTROL 2] Uso de ORDER BY sin ser mencionado

### ISSUE THREAD

**Issue by Jimnora** [IIC2413/Syllabus-2021-1#184]
Hola! En el caso que quiera ordenar una tabla simplemente para que sea mas legible, es posible hacerlo?
Provocaría problemas al momento de revisar los resultados?

**Comment by ValentinaAlvarezG** [comment]
Hola! mmm no hay problema con eso, puedes ordenarla si quieres. Ojo que si en alguna consulta te piden ordenar, debes hacerlo según lo que se indica en esa consulta.
