### ISSUE TITLE
Parte 2 Control 2

### ISSUE THREAD

**Issue by drosselot** [IIC2413/Syllabus-2021-1#185]
Hola. para la parte 2 asumimos que todo esta repartido uniformemente?

**Comment by ValentinaAlvarezG** [comment]
Hola! hay una parte que dice "En el Hash Index cada página contiene 1,000 punteros a las páginas del disco, y hay 32 buckets (uno para cada promedio). **Las notas son distribuidas de manera uniforme** .....", no sé si eso responde tu pregunta.

**Comment by chineseJack564** [comment]
Hola, Contestamos la parte 2 en el mismo notebook?

**Comment by ValentinaAlvarezG** [comment]
Hola! sí, ahí ven ustedes como les acomoda más responderlo. Recuerden que los notebook tienen la opción de agregar celdas de tipo markdown, así que ahí pueden escribir texto. (Cuando agregan una celda nueva pueden cambiarle el tipo de celda de código a markdown)
![image](https://user-images.githubusercontent.com/26123660/116789313-40842200-aa7c-11eb-9cee-fe1689b1857c.png)

Una buena opción es hacer una tablita con los resultados (como la respuesta de la guía de índices). Aquí dejo un [link](https://rpubs.com/Juve_Campos/tablasRMarkdown) donde sale como hacer tablas en markdown, es muy fácil.

**Comment by drosselot** [comment]
Gracias! No lo había visto
