### ISSUE TITLE
Diferencia entre BillVariants.price y Variants.price

### ISSUE THREAD

**Issue by ftocornal** [IIC2413/Syllabus-2021-1#186]
Hola! cual es la diferencia entre BillVariants.price y Variants.price?

**Comment by ValentinaAlvarezG** [comment]
Hola!
Lo que pasa es que cuando se hace una compra, la variante está a un precio "x" pero ese precio puede cambiar después , y el registro de a cuánto se vendió en el pasado no puede perderse por temas contables. Espero eso lo aclare un poco.
