### ISSUE TITLE
[CONTROL 2] Duda fechas Consultas 9, 11, 12

### ISSUE THREAD

**Issue by festelle** [IIC2413/Syllabus-2021-1#187]
En la consulta 12 se pide filtar según fecha  ("El porcentaje del total de clientes que fueron recurrentes en el mes de abril"). No me queda claro si puedo asumir que es del año 2021 o tengo que calcular el porcentaje de recurrencia para cada mes de abril de cada año.

En la consulta 8 tampoco se especifica si es solo para el año 2021 ("El valor de las ventas de cada tienda en marzo (en $$$), ordenadas por ventas"), tengo que tomar todos los meses de marzo sin importar el año o solo el de 2021?

Además, en la consulta 9 se pide: "ids de las variantes que no han tenido ninguna venta en marzo y tienen stock disponible". Ese marzo se refiere solo al 2021 o a marzo de todos año? 

Por último, en la consulta 11 se pide "El valor promedio de venta de cada tienda en marzo ". Tengo la misma duda. Tengo que tomar solo el marzo del 2021 o el mes de marzo de todos los años que están en la base de datos?

Como en otras consultas especifican el año, me tiene confundido si estas se tienen que aplicar para todos los años o no

**Comment by ValentinaAlvarezG** [comment]
Hola! considera solo el año 2021 para todas las consultas.

**Comment by festelle** [comment]
Ok, gracias!
