### ISSUE TITLE
Duda Solucion guia 1

### ISSUE THREAD

**Issue by Huasito-Appel** [IIC2413/Syllabus-2021-1#19]
En clases vimos que al momento de utilizar el operador join teniamos que aplicarle restricciones a las tablas, sin embargo en las respuestas de la guia, como la 2 por ejemplo, se utiliza el operador sobre las tablas sin aplicarle las restricciones. Esto no me quedo muy claro

**Comment by ValentinaAlvarezG** [comment]
Hola! quizás esta issue #13 responda tu pregunta.

**Comment by Huasito-Appel** [comment]
Si gracias, asumo para el control debemos seguir el "estricto rigor" o podemos simplicar tambien?

**Comment by ValentinaAlvarezG** [comment]
Deberían seguir el estricto rigor 😬
