### ISSUE TITLE
[Control 2] Usar función MONTH y YEAR

### ISSUE THREAD

**Issue by dedmu5** [IIC2413/Syllabus-2021-1#192]
Hola, el uninciado dice que hay que entregar El valor de las ventas de cada tienda en marzo (en $$$), ordenadas por ventas. Lo de ordenadas por ventas es por precio en ventas o cantidad de copias vendidas?

**Comment by ValentinaAlvarezG** [comment]
Hola, como dice el enunciado, valor de ventas y ($$$) significa precio, no cantidad.
