### ISSUE TITLE
Overflow pages y Hash Index Unclustered

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2413/Syllabus-2021-1#193]
Hola! Tengo una duda en la parte 2 del control, aunque creo que va más relacionado a materia. No entiendo cómo se calcula el I/O en el caso de tener una relación indexada en un atributo que no sea primary key. Mis intuiciones conceptuales son:

1. Se tiene una cantidad fija de buckets, cada uno asociado a una página que tiene tuplas. Pero si excedo la cantidad de tuplas por página debería tener una overflow page para ese bucket. ¿o me equivoco de concepto? ¿es eso una overflow page? Suponiendo lo anterior,  ¿la cantidad de overflow pages depende estrictamente de las tuplas que necesite almacenar? además, en el caso de tener overflow pages, ¿debo tener punteros que me indiquen esto no? o ¿son como las hojas finales de los árboles que se relacionan entre ellas?
2.En el caso de ser unclustered y tener muuchas tuplas, una hoja debe tener una cantidad de punteros definida que hayan en él,  ¿para cada puntero existe una tupla con el valor del bucket cierto? y si tengo una cantidad menor de tuplas por hoja que de punteros por hoja, ¿haabría una inconsistencia? o necesariamente necesito más hojas para representar el bucket?  (esto son las Overflow pages quizás?)
3. Para el cálculo de I/O que vimos en clases para este indexamiento sin llave primaria, sale una fórmula al final para igualdad de un atributo, pero no la entiendo completamente, por ejemplos, sé que aquí sale ir al bucket en primera instancia (1), luego considera las overflow pages (en el ejemplo no hay cierto?) y por último la cantidad de punteros (2) y luego suma todo, que debería ser 3. ¿Está bien cómo lo pienso o no?
![imagen](https://user-images.githubusercontent.com/59210922/116798527-4dc20080-aabe-11eb-843b-da5c5a8ea5d0.png)

Gracias de antemano!

**Comment by DomagojVrgoc** [comment]
Son muchas preguntas, así qué voy uno por uno.

TLDR: el número de páginas es: #tuplas con este valor de la llave + #páginas del índice (incluyendo los overflow pages).

Aquí vamos ahora:
- "Se tiene una cantidad fija de buckets, cada uno asociado a una página que tiene tuplas. Pero si excedo la cantidad de tuplas por página debería tener una overflow page para ese bucket. ¿o me equivoco de concepto? ¿es eso una overflow page?" Si allá se forma una overflow page. Ojo qué las páginas del índice quardan tuplas (para un índice clustered), o punteros (para un índice unclustered, cómo en la ímagen arriba).
- "Suponiendo lo anterior, ¿la cantidad de overflow pages depende estrictamente de las tuplas que necesite almacenar?" Precisamente. Si tu función de hash pone muchas tuplas al mismo casillero, esto genera overflow pages.
-  "además, en el caso de tener overflow pages, ¿debo tener punteros que me indiquen esto no? o ¿son como las hojas finales de los árboles que se relacionan entre ellas?" Son conectadas una con la otra. Efectivamente, si tu casillero tine una página principal, y 3 overflow pages, puedes asumir qué al aceder al casillero, puedes conseguir las 4 páginas sin hacer nada extra.
- "En el caso de ser unclustered y tener muuchas tuplas, una hoja debe tener una cantidad de punteros definida que hayan en él, ¿para cada puntero existe una tupla con el valor del bucket cierto?" En un índice hash no hay hojas. Son overflow pages. Pero sí, una página tiene el tamaño fijo, y te cabe una cantidad fija de punteros adentro. En el enunciado este parámetro llamaos M. Si el atributo sobre cual está indexando es una llave, existe una tupla con este valor, pero cuando el índice no es una llave (cómo en el enunciado), puede haber muchas tuplas con este valor. El bucket del índice contiene todas, cada una con su puntero. Puede ser qué incluso un valor te causa overflow pages por esto, y para cada tupla tienes qué conseguir la página a cual te apunta. Importante para entender: si R(a,b) tiene la llave a, y estamos indexando por b, puedo tener tuplas (1,X), (2,X), (3,X), y todas tengo qué poder recuperar con mi ínice. 
-  "y si tengo una cantidad menor de tuplas por hoja que de punteros por hoja, ¿haabría una inconsistencia? o necesariamente necesito más hojas para representar el bucket? (esto son las Overflow pages quizás?)"No hay inconsistencia. Mira issue #198.
- "Para el cálculo de I/O que vimos en clases para este indexamiento sin llave primaria, sale una fórmula al final para igualdad de un atributo, pero no la entiendo completamente, por ejemplos, sé que aquí sale ir al bucket en primera instancia (1), luego considera las overflow pages (en el ejemplo no hay cierto?) y por último la cantidad de punteros (2) y luego suma todo, que debería ser 3. ¿Está bien cómo lo pienso o no?" así es.

Efectivamente tu lógica es la siguiente:
- primero busco las páginas del índice. Pare esto necesito el casillero, y su página principal + todos los potenciales overflow pages. 
- Si tengo TUP tuplas con el valor del atributo cual estoy buscando, el índice me da puntero a página qué contiene cada una. Entonces necesito recuperar estas TUP páginas igual.

Ojo qué este cálculo aplica solo para índice hash unclustered.

**Comment by Jamesmoreno21** [comment]
Muchas gracias! Se me aclaró bastante.
