### ISSUE TITLE
[CONTROL 2] Duda formato tiempo (pregunta 8)

### ISSUE THREAD

**Issue by Benjaescobar** [IIC2413/Syllabus-2021-1#196]
Holaaa! estaba haciendo la pregunta 8 del control y me di cuenta que dependiendo de el formato de tiempo que ocupaba el resultado de las tablas cambiaba. Los formatos que ocupe fueron 'YYYY-MM-DDTHH:MM:SS.SSS' y 'YYYY-MM-DD HH:MM:SS.SSS'. Me preguntaba cuál era el que debería usar y porque existe esta diferencia en los cálculos. Graciasss

**Comment by ValentinaAlvarezG** [comment]
Hola, la verdad basta con que uses 'yyyy-mm-dd'

**Comment by Flvilches** [comment]
Hola! Uniéndome a la pregunta. si no tomo en cuenta la hora ( de la forma 'YYYY-MM-DD'), salen menos valores que si considero la hora (de la forma 'YYYY-MM-DD HH:MM:SS.SSS'), no sería un problema eso?. Gracias de antemano!

**Comment by ValentinaAlvarezG** [comment]
Hola! no importa, consideren solo 'YYYY-MM-DD'

**Comment by RafaelEdwards** [comment]
Hola @ValentinaAlvarezG! 
Si ya hice todas las consultas considerando la hora, debería cambiarlas o da lo mismo?
Gracias

**Comment by ValentinaAlvarezG** [comment]
Déjalo así no más
