### ISSUE TITLE
[Control 2] Parte 2 - Significado de id como primary key

### ISSUE THREAD

**Issue by dfloreaa** [IIC2413/Syllabus-2021-1#197]
Hola!
En la Parte 2 al definirnos la relación, nos dicen que el id será la _primary key_, esto significa que al armar un hash index unclustered sobre el promedio, también tenemos en memoria un hash index clustered sobre el id? O no es relevante para la forma en que armamos el hash index el hecho de que el id sea la llave primaria?
Muchas gracias de antemano ☺

**Comment by ValentinaAlvarezG** [comment]
Hola, no es relavente. En el fondo primero haz los cálculos para todas las consultas considerando el B+tree clustered sobre id y luego los cálculos de las 5 consultas usando el  hash index unclustered sobre el promedio.

**Comment by dfloreaa** [comment]
Muchas gracias! :))))
