### ISSUE TITLE
[Control 2] Parte 2 - Respecto al número de punteros

### ISSUE THREAD

**Issue by dfloreaa** [IIC2413/Syllabus-2021-1#198]
Hola!
Tenía otra duda respecto al número de punteros por página en el hash index, resulta que entiendo que existen menos tuplas que punteros para cada página, será este un error del enunciado o efectivamente pueden haber más punteros que tuplas en cada página? En ese caso al hacer una consulta se toma como número total de punteros aquellos que revisa por tuplas (que serían el número de tuplas) o bien el número de punteros por el bucket?
Muchas gracias :)))

**Comment by DomagojVrgoc** [comment]
Si tu índice es clustered va a guardar tuplas. Si tu índice es unclustered va a guardad punteros.

Por ejemplo, si tengo la relación R(a,b,c,d,e,f,g), y la indexo por el atributo a, una página del índice va a guardar lo siguiente:
- Para clustered tuplas enteras, por ejemplo (1,2,3,4,5,6,7)
- Para unclustered valor del atributo indexado, más el puntero a la página con las tuplas, por ejemplo (1,p776)

Cómo la segunda entrada es más chica, te caben más por una página (acuerdate qué las páginas tienen un tamaño fijo).

Ojo qué para el índice unclustered, tú también guardas las páginas con las tuplas enteras en el disco. Entonces en un índice unclustered existen dos tipos de las páginas: las del índice, qué guardan punteros, y las páginas con las tuplas mismas. Las páginas del índice te dicen dónde en el disco buscar la tupla.

En tu pregunta: "En ese caso al hacer una consulta se toma como número total de punteros aquellos que revisa por tuplas (que serían el número de tuplas) o bien el número de punteros por el bucket?", es lo primero. Quiero decir: si la página del índice te dice tengo 7 tuplas con el valor a=25, tienes qué seguir los 7 punteros qupe te devuelve.
