### ISSUE TITLE
Control 2 - Consulta 3

### ISSUE THREAD

**Issue by kalarconvl** [IIC2413/Syllabus-2021-1#199]
Hola! Tenemos que eliminar mails repetidos? O sea, si ´´´omanrique@buendia.es´´´ compró más de 1 vez, lo dejo repetido o solo 1 vez?

**Comment by Skablop** [comment]
Hola, 
La consulta te pide los mails de aquellas personas que compraron al menos una vez durante el período indicado, por lo que no es necesario que aparezca el mail repetido según la cantidad de compras.

Saludos.

**Comment by kalarconvl** [comment]
Pero entonces podemos asumir que los mails son únicos (2 personas distintas no pueden tener el mismo mail)?

**Comment by ValentinaAlvarezG** [comment]
Hola! sí son únicos.
