### ISSUE TITLE
Duda consulta 4, Guía 1

### ISSUE THREAD

**Issue by tcouso** [IIC2413/Syllabus-2021-1#20]
## Duda consulta 4, Guía 1

Hola!

Tengo algunas dudas con respecto a la interpretación que debemos dar a algunas consultas requeridas. Por ejemplo, en la siguiente consulta:

"Encuentre los nombres de los tours que visitan una viña de la Quinta Región, y una viña de la Décima Región"
  
yo interpreté que debía encontrar los __tours que visitan solo una viña de la V región y solo una viña de la X región__. Sin embargo, según lo que entendí del solucionario, la consulta correcta encontraba un __tour que visitaba a lo menos una viña de la V región y a lo menos una viña de la X región__. No estoy seguro de si el enunciado es ambiguo o me perdí en alguna parte, de modo que agradezco cualquier aclaración.

Saludos!

Tomás

**Comment by DomagojVrgoc** [comment]
La intención fue: el tour visita **al menos** una viña de la V región, y **al menos** una viña de la X región.

**Comment by tcouso** [comment]
> La intención fue: el tour visita **al menos** una viña de la V región, y **al menos** una viña de la X región.

Perfecto, gracias por la clarificación!
