### ISSUE TITLE
[Control 2] índices juntos o por separado

### ISSUE THREAD

**Issue by sopadeoliva** [IIC2413/Syllabus-2021-1#209]
No me quedó claro si hay que ver el ejercicio como si tuvieramos simultáneamente dos índices para atributos distintos, o primero el caso 1 de tener B+ para el id (haciendo consultas tanto para id como para otros atributos) y después hacer un caso 2 donde tenemos el hash index del promedio.

**Comment by ValentinaAlvarezG** [comment]
Hola! creo que lo respondí en la issue #197

**Comment by sopadeoliva** [comment]
gracias! ahí creo que entendí mejor. Pero igual me queda la duda (porque no sé si vimos el ejemplo explícito en clases) de qué pasa cuando indexamos un atributo pero consultamos sobre otro. Simplemente trabajamos el atributo sin index? o las tuplas se acceden a través del otro atributo sí indexado de alguna forma primero?

**Comment by ValentinaAlvarezG** [comment]
Es más o menos lo que se hizo en la guía. Y piensa que si indexas por un atributo y consultas por el otro, es parecido a lo que pasa cuando no tienes ningún índice en verdad.

**Comment by sopadeoliva** [comment]
ok, gracias :)
