### ISSUE TITLE
Pregunta sobre Natural Join

### ISSUE THREAD

**Issue by Gustav2000** [IIC2413/Syllabus-2021-1#21]
Hola, me gustaría saber si se puede usar **Natural Join** para unir las 3 tablas que aparecen en el control (al igual que como se muestra en la pauta de la Guía 1) para reducir un poco de espacio ya que o si no queda demasiada información. Sin embargo, al ver los Natural Join que usan en la Guía 1, no entiendo por qué esto está bien siendo que en algunos casos juntan 2 tablas que luego se juntan con una tercera teniendo coincidencia de nombres de más de un atributo. A continuación me explico:

Primero se hace Natural Join entre **SeVisita** y **Viñas** (a esta tabla la llamaré **TABLA1**) y luego lo anterior se une mediante un join con **Tours**, en este paso **Tours** tiene el atributo _tid_ y _nombres_ que coinciden con los nombres de los atributos de la **TABLA1** que también son _tid_ y _nombres_. A lo que voy es que no existía un único atributo igual al momento de hacer el JOIN, sino que habían 2 atributos con el mismo nombre.

Espero que se entienda a que me refiero.

**Comment by ValentinaAlvarezG** [comment]
Hola, quizás la issue #13 solucione tu duda.

**Comment by Gustav2000** [comment]
Sí, muchas gracias.
