### ISSUE TITLE
Consulta 13

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2413/Syllabus-2021-1#210]
Hola! Que uso la función LAG (que si debería soportar SQLite), pero cuando lo corro en Colab me dice que no tiene esa función. ¿Que puedo hacer para que me corra (ej: actualizar sqlite en Colab)? O sí no, ¿que otra función puedo usar para hacer lo mismo que LAG?
PD: LAG te da el resultado de la misma columna pero de la fila anterior

**Comment by ValentinaAlvarezG** [comment]
Para responder las consultas de la guía la verdad es que no se necesita nada tan rebuscado fuera de lo que se ve  en clases (para las consultas se necesita lo básico de SQL y consultas de agregación). Nunca he usado LAG y no sé cómo podrías usarlo en colab. Mi recomendación es que busques otra manera de hacer la consulta.
