### ISSUE TITLE
Distribución de puntos Control 2

### ISSUE THREAD

**Issue by kalarconvl** [IIC2413/Syllabus-2021-1#211]
Hola!! 
Según el enunciado, la primera parte tiene 5 puntos y la segunda 1 punto. Pero no aparece el puntaje de la consulta 14 y sumando los puntos de las primeras 13 consultas:
1) 0.3
2) 0.3
3) 0.3
4) 0.3
5) 0.3
6) 0.4
7) 0.4
8) 0.4
9) 0.4
10) 0.4
11) 0.5
12) 0.5
13) 0.5

Me da 5 puntos, entonces hay un bonus por hacer la 14 o algo así?

**Comment by ValentinaAlvarezG** [comment]
Hola! en el enunciado dice que hay preguntas que son opcionales.  Antes de la 11 dice "De las siguientes 4 consultas solo debes hacer 3. Si haces las 4 no te revisaremos la última"

**Comment by kalarconvl** [comment]
Ahhh no había visto esoo muchas gracias!!
