### ISSUE TITLE
Consulta 10

### ISSUE THREAD

**Issue by ian-fell** [IIC2413/Syllabus-2021-1#213]
Hola!
Al empezar a hacer la consulta 10 mi computador me arroja problema con la sintaxis de la consulta. Literal copié lo que aparece en las slides del curso para obtener los precios que no son los más caros, y me tira problemas. Adjunta está la imagen para ver si el error lo tengo yo, o si es algo mas. Además, probé ambas consultas por separado, y funcionan, pero al aplicar el ANY me tira el error :(
<img width="821" alt="Screen Shot 2021-05-02 at 19 47 29" src="https://user-images.githubusercontent.com/62180167/116831817-84ebec80-ab66-11eb-9436-a4f11692477b.png">

**Comment by ValentinaAlvarezG** [comment]
Hola! ``ANY`` no funciona en sqlite, hay otras formas de hacer la consulta en todo caso. Por otro lado, no deberías pegar tu respuesta en una issue!
