### ISSUE TITLE
[Control 2] Parte 2: Hash Index

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2413/Syllabus-2021-1#214]
Hola! Tengo unas dudas puntuales para la parte del Hash Index U que agradecería si me pudieran ayudar.

1. ¿En un bucket no puede haber tuplas repetidas cierto? Por ejemplo si tengo T tuplas en total y tengo K tuplas asociadas a la llave de un bucket, luego cada página soporta P tuplas, por ende tengo T/P páginas en total, pero si K > T/P, tendría a lo más T/P punteros ( 1 por página) no K (1 por tupla) ¿cierto? donde un puntero me apuntaría a una página de tuplas que podría tener más de 1 con el valor llave del bucket.
2. No logro dimensionar cuál es el peor caso de búsqueda al filtrar por promedio, se me viene a la mente que podría ser que en que en cada bucket se me apunten todas las páginas, pero eso sólo me hace sentido para un tipo de consultas, pero para otras me parecería extraño porque si tengo que revisar más de un bucket, con revisar uno habría accedido a todas las páginas y ya no necesitaría cargar más, o me estoy mal? (Esto lo hago pensando en que las páginas de tuplas están al 100% de su capacidad).

Gracias de antemano!

**Comment by DomagojVrgoc** [comment]
1. Recuerda qué en un índice hash unclustered tienes K/M páginas con los punteros y no con las tuplas, dónde M es el número de punteros qué caben en una página. Las tuplas se guardan por separado en el disco en K/P páginas, si caben P tuplas por página (ver los slides o uno de los tres videos qupe tenemos sobre esto).  Siempre tienes número de punteros = número de tuplas qué hacen el match con tu llave de búsqueda. 
2. La pregunta qué tienes qupe responder es cúantas veces tengo qué ir a recuperar a una página con la tupla (y no con los punteros).

Ver los issues #198, #193, y # 167 para explicaciones similares.
