### ISSUE TITLE
[Control 2] Parte 2 Explicación del cálculo de I/O

### ISSUE THREAD

**Issue by Gustav2000** [IIC2413/Syllabus-2021-1#217]
Hola, en la parte 2 es necesario redactar la expliación de cómo llegamos al cálculo de I/O como aparece en la solución de la guía de índices, o está bien si colocamos solamente el cálculo?
Gracias.

**Comment by ValentinaAlvarezG** [comment]
Hola! no es necesaria la explicación, basta con los valores.

**Comment by Gustav2000** [comment]
Súper, muchas gracias
