### ISSUE TITLE
[Control 2] Parte 2, Hash index unclustered sobre el promedio

### ISSUE THREAD

**Issue by Gustav2000** [IIC2413/Syllabus-2021-1#218]
Hola, en la parte 2, el hash index unclustered **sobre el promedio** tengo dudas con respecto al par (X, puntero) que está contenido dentro de cada bucket. El X corresponde a la PRIMARY KEY o al promedio?

**Comment by DomagojVrgoc** [comment]
Promedio.

**Comment by Gustav2000** [comment]
Gracias

**Comment by DomagojVrgoc** [comment]
En realidad es un poco más complicado. 

El par (X,puntero) tiene X = promedio (la llave de búsqueda), pero el par (X, puntero) me dice dónde encontrar la tupla de la cuál estoy hablando. Otra manera de verlo es pensar qué para un X, en el bucket encuentro los punteros a páginas con todas las tuplas con este valor de X.

**Comment by Gustav2000** [comment]
Sii, muchas gracias profe.
