### ISSUE TITLE
[Control 2] No entiendo como se distribuyen los punteros en el hash index

### ISSUE THREAD

**Issue by dedmu5** [IIC2413/Syllabus-2021-1#219]
Tengo las siguientes dudas:
1- ¿En un hash index puede haber punteros repetidos? Por ejemplo:
![image](https://user-images.githubusercontent.com/65060602/116948480-6ad90980-ac4d-11eb-9cfd-f61ad294f9ae.png)
Notar que hay dos punteros (5,p1)
2- ¿Hay un puntero por cada tupla guardada o un puntero por cada página del disco indexada? ¿O ninguna de las anteriores?

**Comment by DomagojVrgoc** [comment]
Para cada tupla guardada.
