### ISSUE TITLE
Formato Entrega Control 1

### ISSUE THREAD

**Issue by jagaldames** [IIC2413/Syllabus-2021-1#22]
Hola! Hice todo mi control por RelaX y quiero saber si puedo poner "pantallazos" de mi código en el pdf como entregable o si tengo que pasarlo a texto en LaTeX para seguir la sintáxis vista en cátedra.

Gracias!

**Comment by jagaldames** [comment]
Por ejemplo algo así: 
![image](https://user-images.githubusercontent.com/17708598/112553653-ab6a7b00-8da3-11eb-96dc-7900c60757a7.png)

Es mi código de la actividad

**Comment by arpincheira** [comment]
Hola, no hay problema que añadas de tu código en el pdf, lo importante es que el documento entregado sea legible y que quede claro a que pregunta corresponde cada una de tus respuestas
