### ISSUE TITLE
[Control 2] duda sobre el peor caso del b+ tree clustered

### ISSUE THREAD

**Issue by dedmu5** [IIC2413/Syllabus-2021-1#220]
**En el peor de los casos**, cuando quiero recorrer toda la relacion en un el b+ tree clustered con H hojas, con H impar:
1- considero que la primera hoja a la que llego es la está primera/última (teniendo H-1 hojas a la derecha o izquierda) 
2- considero que llego a la hoja de al medio (teniendo (H - 1)/2 a la derecha y (H-1)/2 a la izquierda)

Según yo el peor caso sería el 2, ya que para recorrer toda la relación tendría que moverme más que H, pero quizás no es así como funciona

**Comment by DomagojVrgoc** [comment]
H es normalmente la altura del árbol.

Pero si tienes H **hojas**, el costo es (H - 1)+ h, dónde h es la altura. Primero bajas a la primera o la última hoja (esto te ya da una hoja), y de allá recorres todas usando la propiedad qué están ligadas.
