### ISSUE TITLE
Problema de postgre con caracteres especiales 

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2413/Syllabus-2021-1#221]
Hola, en una clase o ayudantía dijeron que no había problemas en postgre con las tildes o Ñ's, sin embargo, al exportar desde csv me arroja este error `ERROR:  invalid byte sequence for encoding "UTF8": 0xf1 0xed 0x61 0x20`  en esta dirección `Compañía de Jesús N°1625`.  Puedo simplemente reemplazar todos los caracteres especiales por letras? lo pregunto por si tienen un sistema automatizado y podría detectarlo incorrecto

**Comment by pbyoma** [comment]
Hola,
Si, no es problema que reemplacen los caracteres especiales
