### ISSUE TITLE
[Entrega 2] Usuarios y direcciones

### ISSUE THREAD

**Issue by amahns1** [IIC2413/Syllabus-2021-1#222]
Hola!

Quería preguntar si podemos asumir que dos usuarios distintos no pueden tener direcciones en común.
¿Es así, o se puede dar que distintos usuarios compartan una ubicación?

Muchas gracias :)

**Comment by arpincheira** [comment]
Hola, podría ocurrir perfectamente que dos usuarios vivan en la misma casa así que no, **no pueden asumir que dos usuarios distintos no puedan tener direcciones en común.**
