### ISSUE TITLE
Duda primary key / BCNF / 3NF

### ISSUE THREAD

**Issue by jtconcha** [IIC2413/Syllabus-2021-1#223]
Hola! En el caso de tener una relación con un id y un atributo único (como un rut por ejemplo) ¿Ambas deben ser la primary key? me surge la duda porque si es que no se le coloca restricción al atributo único, podría pasar que existan tuplas con ids distintos pero mismo atributo.

Y lo otro, como existen dos atributos únicos dentro de la relación, con el id se pueden obtener el resto de los atributos, pero con el atributo único también se debería poder obtener el resto de atributos y el id, entonces ¿Estaría en BCNF o 3NF?

**Comment by ValentinaAlvarezG** [comment]
Hola! quizás los comentarios de esta issue #138 te aclaren.

**Comment by jtconcha** [comment]
Sii eso era! no había visto esa issue, muchas gracias!
