### ISSUE TITLE
Duda modelar llaves BCNF

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2413/Syllabus-2021-1#225]
Hola! Tengo una duda muy puntual que es que si se tiene una dependencia funcional A->B, donde para BCNF se pide que A sea(n) llave(s), al modelar esta(s) llave(s) se refiere a que sea(n) PRIMARY KEY?

Gracias de antemano!

**Comment by arpincheira** [comment]
Hola, efectivamente se pide eso, muestras las dependencias (LLAVE)  ->(Atributos) y una justificación sobre la elección del modelo en el que expliques que efectivamente la llave elegida permite cumplir lo solicitado
