### ISSUE TITLE
Columna direccion

### ISSUE THREAD

**Issue by PDominguezW** [IIC2413/Syllabus-2021-1#226]
En el exel que nos dan con la informacion de las Unidades, en la columna de direccion, los datos aparecen como numeros. ¿Que representan esos numeros? Pensaba que era la numeracion en la calle, pero no estoy seguro. Gracias de antemano.

**Comment by arpincheira** [comment]
Hay un zip con datos generales que posee la información de las direcciones junto a las comunas(los números son ids que se referencian en estos datos)
