### ISSUE TITLE
[Entrega 2][Modelo]

### ISSUE THREAD

**Issue by Huasito-Appel** [IIC2413/Syllabus-2021-1#227]
Hola! para normalizar nuestro modelo, es todo el modelo en 3NF o BCNF, o puedo hacer un remix entre ambos?

**Comment by arpincheira** [comment]
La idea es que se adhieran a uno de estos modelos y que no hagan una mezcla de ambos. De todas formas les recomiendo fuertemente justificar el motivo por el que creen que su modelo está en 3NF o BCNF.
