### ISSUE TITLE
[Entrega 2][Pares]Posibles errores en los datos

### ISSUE THREAD

**Issue by Pablo-Carrasco** [IIC2413/Syllabus-2021-1#228]
Hola! Estaba trabajando en los archivos csv para la entrega y me encontré con estos datos que creo que tienen errores:

- Hay personas en `personalV2.csv` que cambian su edad, es decir, tienen mismo id, rut y sexo, pero su edad cambia, como por ejemplo en la persona con id 811.
- Hay vehículos en `vehiculos.csv` que no pertenecen a ninguna categoría, es decir, no tienen atributos para ser de carga, de cadena fría o de productos frescos, como por ejemplo el vehículo con id 17.

Agradecería que me aclararan si estos datos son errores o tenemos que trabajar con ellos.

**Comment by Pablo-Carrasco** [comment]
Muchas gracias por darte el tiempo de contestar  
Me quedó todo claro :ok_hand:

**Comment by Huasito-Appel** [comment]
hola, solo para confirmar, dps de eliminar las filas en que todo era igual pero cambiaba la edad en la tabla personal me quedan 825 filas. Esta bien?
