### ISSUE TITLE
Duda con tabla de unidades

### ISSUE THREAD

**Issue by Natydlb** [IIC2413/Syllabus-2021-1#229]
Hola! Tengo una duda, en la tabla de unidades vi que sucede lo siguiente:
![WhatsApp Image 2021-05-10 at 19 16 50](https://user-images.githubusercontent.com/62019255/117735869-64eea580-b1c4-11eb-836b-4c08eac46b82.jpeg)

Me preguntaba si al dejar la tabla con repetición de unidades pero a distintas direcciones es un forma optima de trabajar la tabla? Porque si es que sintetizo la tabla para que me quede solo una fila por unidad podría perder información

**Comment by arpincheira** [comment]
Hola, recuerda que existe algo denominado "plan de cobertura"(comunas a las que presta servicios una determinada unidad), puede que esa repetición esté relacionada con dicho concepto. Espero que esta **pista** haya aclarado tu duda

**Comment by Francisco5674** [comment]
Pero, siguiendo con el tema, aquí tengo un drama, puesto que si las unidades pueden cubrir las necesidades de ciertas comunas, entonces cada comuna tiene una sola unidad que la atiende, pero cada unidad puede atender varias comunas, sin embargo, aunque sea así, por que estaría la comuna que se cubre referenciándose de esa forma tan burda, ¿no sería mejor que existiera una tabla de comunas y cada una referencie el id de la unidad que la atiende?

**Comment by arpincheira** [comment]
Hola, no se de donde sacaste que cada comuna tiene una sola unidad que la atiende... no puedo decir nada más pero recuerda que existen tablas intermedias que se pueden crear para cierto tipo de relaciones... espero que eso te ayude
