### ISSUE TITLE
Tipo Respuestas Control 1

### ISSUE THREAD

**Issue by fedezang** [IIC2413/Syllabus-2021-1#23]
Hola!
Quería saber si para las consultas del control 1 basta con colocar el álgebra de cada una, o es necesario explicar cómo se realiza la consulta (en palabras).
Gracias de antemano

**Comment by ValentinaAlvarezG** [comment]
Hola, basta con la consulta en álgebra, pero si escribes una explicación ayudarás más al ayudante que te corrige a entender tu respuesta.
