### ISSUE TITLE
Duda dependencias e ids

### ISSUE THREAD

**Issue by margavicunas** [IIC2413/Syllabus-2021-1#231]
Hola!
Me surgió la duda de cómo entran los ids a la hora de identificar dependencias funcionales. Por ejemplo, en clases vimos que `rut --> nombre` , pero, si quisiéramos que el rut no fuera primary key en nuestro esquema (a pesar de ser llave natural) y más bien agregáramos un id, cómo se analizarían las dependencias? Tipo ` id --> rut --> nombre` o ` id, rut --> nombre` ? 
Me complica un poco cómo insertar los ids en el análisis de las dependencias funcionales :c

Gracias y disculpas por molestar en semana de receso!

**Comment by arpincheira** [comment]
Hola, te recomiendo ver la issue #138
