### ISSUE TITLE
Duda con las comunas de cobertura de las unidades

### ISSUE THREAD

**Issue by Francisco5674** [IIC2413/Syllabus-2021-1#232]
Hola
Tengo una duda con respecto al csv que nos dieron para completar la tabla de unidades, es decir, nosotros sabemos que las unidades tienen cobertura, pero esta no corresponde a una relación entre la tabla de unidades y un "tabla de comunas", más bien es el resultado de la consulta que busca las comunas de todos los despachos efectuados por los vehículos de esa unidad verdad?

**Comment by vikicontardo** [comment]
> Hola, te recomiendo investigar sobre las denominadas 'tablas intermedias", pueden ser útiles al momento de modelar relaciones n es a n

Hola @arpincheira con respecto a eso, con mi compañera de proyecto no nos queda claro si el uso de tablas intermedias es aceptada en los dos tipos de modelos (BCNF y 3NF). O solo aplican para un cierto tipo de modelo?

Lo pregunto por la "regla" del id único que tienen los modelos BCNF, que al final nos obligan un poco a generar tablas intermedias para que eso no ocurra...
