### ISSUE TITLE
Esquema E/R: Relación entre dos relaciones

### ISSUE THREAD

**Issue by camirojasguajardo** [IIC2413/Syllabus-2021-1#233]
Hola! en el esquema E/R, es posible que dos relaciones se relaciones entre sí? Gráficamente, que haya una línea que vincule directamente dos rombos. 

Desde ya, agradezco sus respuestas, saludos!

**Comment by arpincheira** [comment]
Hola, normalmente esto no debería ocurrir, por lo que te recomiendo replantear si alguna de esas tablas es relación o una entidad. De todas formas, lo que si puedes hacer es tener dos relaciones entre entidades(por ejemplo si hacia y Desde al momento trabajar con direcciones)
