### ISSUE TITLE
Duda sobre el esquema de la entrega 2

### ISSUE THREAD

**Issue by Etienne99** [IIC2413/Syllabus-2021-1#234]
Hola, quisiera saber si podemos modificar o hacer un esquema de tablas distinto al que realizamos en la entrega 1, ya que pensamos que lo que hicimos para la entrega 1 dificulta un poco el trabajo. Saludos.

**Comment by arpincheira** [comment]
Em... pueden hacer por ejemplo esto:

Libro (<ins>identificador</ins> int, numero_paginas int, titulo varchar(100), autor varchar(100))

lo puedes escribir así

Libro  {
  - <ins>identificador</ins> int
  - numero_paginas int
  - titulo varchar(100)
  - autor varchar(100)

 }


donde identificador es la llave primaria del modelo, lo otro que puedes hacer es intentar poner colores para indicar llaves foráneas indicando lo que significa el color en alguna parte del informe. Puede que eso te facilite bastante el trabajar con el esquema, recuerda que un esquema no son tablas donde muestras los datos porque eso será considerado incorrecto, también debes tener en cuenta que Diagrama E/R **no es lo mismo** que el esquema(lo digo por si el caso nomás).

**Comment by Etienne99** [comment]
Gracias, pero mi pregunta estaba enfocada a rehacer el esquema, quiero saber si puedo hacerlo de nuevo desde cero o si debo utilizar exactamente el mismo que hice para la entrega 1.

**Comment by arpincheira** [comment]
ah... lo siento por la confusión... si, puedes hacer el esquema nuevamente desde 0. Consejo, utiliza el feedback que te dieron y revisa los datos que les entregamos, también te recomiendo revisar una que otra issue en donde se pudieron haber dado(no digo que lo hayamos hecho ni nada...) pistas sobre el modelo que deben realizar.

**Comment by Etienne99** [comment]
Ok, muchas gracias!
