### ISSUE TITLE
[ENTREGA 2][JUSTIFICACION MODELO]

### ISSUE THREAD

**Issue by Huasito-Appel** [IIC2413/Syllabus-2021-1#235]
Hola!
ando medio enredado, particularmente con el punto 2 de la entrega no me queda claro como debemos justificar el modelo, podrian darme un ejemplo de esto?
Gracias de Antemano.

**Comment by DomagojVrgoc** [comment]
Lo más directo sería: "La única dependencia qué existe es de forma llave primaria -> todo el resto. Entonces la relación está en BCNF."

Pero en general, para cada entidad deberías analizar cuales dependencias aplican, y si están metidas dentro de la tabla.

**Comment by arpincheira** [comment]
Hola, tal como dice Domagoj, la idea es que hagan un análisis para cada una de las entidades. De todas formas, aquello que **NO** queremos por nada del mudno es que nos pongan un único análisis general en el que repitan la definición de BCNF o de 3NF, pues esto se considerará incorrecto(al final de cuentas la idea es saber si tienen nociones de esto y no que nos repitan lo que podemos encontrar en las diapositivas del curso).

**Comment by Huasito-Appel** [comment]
@arpincheira quede mas enredado creo, ya que es requisito que todo nuestro modelo este en BCNF o 3NF, por lo que la justificacion de las dependencias para cada tabla seria estandarizado, como comento Domagoj,  algo asi como
en la tabla X tenemos N entidades en donde las dependencias son entidad1(PK)-> {todo lo demas}
realizar este analisis para cada tabla, se considera general? o esta correcto para la entrega.

**Comment by arpincheira** [comment]
A priori diría que está correcto el método que sugieres para el análisis,

**Comment by Huasito-Appel** [comment]
Perfect, Muchas gracias :)
