### ISSUE TITLE
[Entrega 2][Origen en despachos no es BCNF]

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2413/Syllabus-2021-1#236]
Hola! ¿Quería saber si para esta entrega es necesario seguir las instrucciones del enunciado 1 que dice que los despachos tienen un 
 atributo _origen_? Ya que el Vehículo asociado al Despacho, está asociado a una Unidad la cual tiene su _dirección_ que es la misma que el atributo _origen_ de Despacho.  
En resumen, para que Despachos esté en BCNF debemos sacar el atributo _origen_, pero eso implica contradecir el enunciado de la entrega 1. ¿Podemos hacer esto último?

Saludos y gracias!

**Comment by arpincheira** [comment]
Hola, si bien se puede dar esto, te recomiendo **no asumir**  que sucede en todos los casos, es decir, pueden existir veces en las que un despacho no se origine en la dirección de la unidad a la que corresponde. 

**NOTA:** puedes utilizar esta issue como referencia al momento de poner este supuesto en la entrega

**Comment by Huasito-Appel** [comment]
entonces es necesario dejar el atributo direccion en la tabla despachos, tal como se establece en la entrega 1?

**Comment by arpincheira** [comment]
Efectivamente

**Comment by Huasito-Appel** [comment]
perfect, gracias por las respuestas Y darte el tiempo esta semana  :smiley:
