### ISSUE TITLE
[Dependencias en esquema relacional]

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2413/Syllabus-2021-1#237]
Hola!
Pongamos como ejemplo que tenemos 2 tablas, Perro(id INT, dueño Bool) y dueño(id INT, perro_id INT). Necesitamos asociar un perro_id a su dueño si y solo si el Perro correspondiente al perro_id tiene el atributo dueño == true. 
¿Existe alguna forma de modelar a nivel del esquema relacional, que el perro_id que se pone en el Dueño corresponda necesariamente a un perro que sabemos que tiene un dueño (es decir que el atributo Perro.dueño == true)?

Saludos y gracias!

**Comment by Skablop** [comment]
Hola,

Probablemente exista una forma de hacer lo que pides de esa manera, pero te recomendaría cambiar un poco tu esquema. Lo que podrías hacer, por ejemplo, es crear una tabla Perro(pid INT) y una tabla Dueño( did INT), y una tabla EsDueño(did INT, pid INT), donde pongas como tupla todos los perros y sus respectivos dueños. 

Así, además, no generas el problema de que para crear un dueño tiene que tener perros (imagina por ejemplo que quieres agregar un dueño y luego su perro, no podrías considerando tus tablas, y en una base de datos grande eso podría ser un problema, ya que tienes que darte toda la vuelta para agregar al perro primero), o todos los cambios que tendrías que hacer para que un perro pase de no tener dueño a tener uno.
