### ISSUE TITLE
Control 1 - P3: Cómo mostrar los resultados de la consulta

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2413/Syllabus-2021-1#24]
En la consulta 3 del control se deben mostrar todas las montañas  con sus respectivos montañistas que han subido más de una vez o se debe mostrar a todos los montañista que han subido una montaña "x" mas de una vez

**Comment by JosefaPaz** [comment]
Hola! Como el enunciado dice que deben ser los nombres de todas las personas que han subido la misma montaña más de una vez, sería mostrar los nombres de todos los montañistas que han subido una montaña "x".

Si lo hicieras de la primera forma, tal como se explica en la issue #9  y #6 tendrías tuplas duplicadas y eso no es posible.

Espero esto te aclare, éxito!! 😄
