### ISSUE TITLE
[Entrega 2] productosV2.csv impares

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2413/Syllabus-2021-1#242]
Hola! Asumo que cada id de producto lleva asociado un único nombre, precio, descripción, alto, ..., fecha de caducidad. Pregunto porque hay algunas filas con el mismo id de producto, pero distinta tienda (entiendo que dos tiendas pueden vender el mismo producto).

**Comment by arpincheira** [comment]
Hola, efectivamente puede pasar que más de una tienda venda un mismo producto.
