### ISSUE TITLE
[Entrega 2] Carga de datos con llaves foráneas entre dos entidades

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2413/Syllabus-2021-1#243]
Hola! Espero estén bien, tengo la duda/problema de que al cargar nuestras bases de datos a SQL con llaves foráneas entre dos entidades. Ocurre que una entidad demanada la existencia de la otra para relaciones N:1 y 1:N que tenemos entre ellas dos. 

Por ejemplo, si tengo una relación de sedes de Veterinarias, donde se cuidan Perros, pero cada Veterinaria tiene un perro que es del guardia, entonces si modelo como Veterinarias(atr_1, atr_2, ..., id_perro_guardia FOREING KEY) pero a la vez tengo que cada perro tiene un id de la veterinaria correspondiente, es decir Perro(atr_1, atr_2, ..., id_veterinaria FOREING KEY), entonces al hacer nuestras bases de datos, SQL no permiten cargar una sin la otra 😢 .  ¿qué se podría hacer al respecto? 

Saludos y gracias de antemano!

**Comment by arpincheira** [comment]
Hola, no se si lo resolvieron pero puede que [aquí](https://www.postgresql.org/docs/9.1/sql-altertable.html) encuentren su respuesta(**hint**: les recomiendo buscar como se pueden añadir _constraint_ que hagan lo que quieren)
