### ISSUE TITLE
Pre-procesamiento de los datos

### ISSUE THREAD

**Issue by allisonaguilar** [IIC2413/Syllabus-2021-1#244]
Hola! Quisiera saber si es posible usar la librería pandas para procesar los datos.

Gracias!

**Comment by arpincheira** [comment]
Efectivamente la pueden utilizar, ojo eso si con el uso d métodos de pandas que podrían llevarlos a "perder" información(no creo que pase pero se los digo por si el caso).

**Comment by allisonaguilar** [comment]
Gracias!!
