### ISSUE TITLE
[grupos impares][entrega 2] Duda sobre stock de productos 

### ISSUE THREAD

**Issue by camirojasguajardo** [IIC2413/Syllabus-2021-1#245]
Hola! Como en los csv que se entregan no se indica el stock de productos por tienda, es posible omitir esto y asumir que los usuarios compran cantidades válidas de cada producto?

**Comment by arpincheira** [comment]
Hola, es importante tener en consideración cuantos productos compran los usuarios por lo que no pueden omitir dicho dato. Ahora, pueden asumir que las tiendas siempre tendrán producto suficiente para satisfacer todas las compras de la base de datos entregada
