### ISSUE TITLE
[Entrega 2][impar] Duda productosV2.csv

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2413/Syllabus-2021-1#246]
Supongo que el atributo duracion_sin_refrigerar está en días y siempre será un int?

**Comment by arpincheira** [comment]
Hola, efectivamente siempre va a ser un int, ahora... no creo que sea días pues un producto fresco no dura precisamente muchos días sin refrigerar(recuerda que según el enunciado las carnes y las frutas entran en dicha categoría y hay algunas de estas que no conviene dejarlas mucho tiempo guardadas sin refrigeración alguna)
