### ISSUE TITLE
Dependencia con llaves foráneas y tablas auxiliares

### ISSUE THREAD

**Issue by franciscavelascog** [IIC2413/Syllabus-2021-1#247]
Hola! Me surgió una duda para la parte 2.2 de justificar el modelo. En el caso de tener tablas auxiliares con llaves foráneas, producto de la relación entre otras dos tablas, debemos mostrar también que estas están en BCNF como el resto del modelo? Además, me gustaría saber qué pasa con las llaves foráneas al momento de justificar el modelo. Estas deben ser incluídas en la dependencia o solo debemos incluir los atributos propios de la tabla?

**Comment by arpincheira** [comment]
Hola, en lo que respecta a las tablas intermedias y la moderación en BCNF te recomiendo ver lo que mencionan en [este link](https://stackoverflow.com/questions/7840208/bcnf-table-design-multiple-values)(a modo de spoiler, en bcnf puedes tener una llave compuesta como un conjunto de llaves y va a estar bien, de todas formas visita el link pues lo explican con más profudidad).

Ahora, con lo segundo que mencionas, no es necesario poner las llaves foráneas al momento de justificar el modelo, solo deben poner atributos propios de la tabla
