### ISSUE TITLE
Diagrama E/R

### ISSUE THREAD

**Issue by Melisa96** [IIC2413/Syllabus-2021-1#248]
Hola! estoy un poco enredada con el diagrama
En el caso de tener una relación que conecte varios id, se podría tener en el esquema un rombo que una a las 4  entidades que queremos conectar?
Por ejemplo Entidades a(aid) b(bid), c(cid), d(did) y con la relacion M(aid,bid,cid,did) o estaría mal?
Gracias de antemano :D

**Comment by arpincheira** [comment]
Te recomiendo pensar que aquellos "rombos" que mencionas corresponden únicamente a relaciones, esto quiere decir que si tienes una relación que conecte una o más entidades(algo que no debería pasar normalmente), debes ponerla como un rombo que las conecte. Ahora, en el caso de que haya una entidad que esté relacionada a varias cosas y no posea a priori un atributo propio(cosa que puede pasar en problemas de este estilo cuando uno hace una moderación inicial), debes poner la entidad y conectarla a las diversas entidades a las que puede estar conectada, mediante relaciones.

Espero haber contestado tu consulta
