### ISSUE TITLE
Carpeta Sites

### ISSUE THREAD

**Issue by PDominguezW** [IIC2413/Syllabus-2021-1#249]
Ya subí los archivos de la pagina a la carpeta Sites, sin embargo, la pagina no me funciona. ¿Como puedo arreglar esto?

**Comment by benjavicente** [comment]
Para que los ayudantes te puedan ayudar más rápido, trata de añadir más información, como por ejemplo, que has probado y que error tienes (_The requested URL was not found_ o un error de php en específico). Asegúrate también que si tienes las rutas correctas:

```bash
# En el servidor
~/Sites/path/al/archivo.php
# En el url del navegador
http://codd.ing.puc.cl/~grupoXX/path/al/archivo.php
```

**Comment by PDominguezW** [comment]
Hice lo mismo que aparece en la ayudantia y tengo los paths que mencionaste arriba, pero al tratar a entrar a la pagina recibo el error 'The requested URL was not found on this server.'

**Comment by PDominguezW** [comment]
Ya encontre el error. Faltaba el signo de interrogacion despues del archivo.php en el url.

**Comment by Natydlb** [comment]
Hola! Sabes que tengo el mismo problema, pero no se soluciono agregando el signo de interrogación. Mi path al archivo es ~/Sites/index.php

**Comment by Aloncarrasco** [comment]
> Hola! Sabes que tengo el mismo problema, pero no se soluciono agregando el signo de interrogación. Mi path al archivo es ~/Sites/index.php, Que puedo hacer para solucionar este problema?

me pasa lo mismo, hay que correr algún comando aparte para que la página funcione?

**Comment by Skablop** [comment]
No debería ser necesario correr ningún comando aparte si es que los archivos php están bien construídos. 

¿Has probado subiendo el sitio web de prueba que hicimos durante la ayudantía?

**Comment by MaxWhiting** [comment]
> > Hola! Sabes que tengo el mismo problema, pero no se soluciono agregando el signo de interrogación. Mi path al archivo es ~/Sites/index.php, Que puedo hacer para solucionar este problema?
> 
> me pasa lo mismo, hay que correr algún comando aparte para que la página funcione?

Hola, pudiste solucionar eso?
