### ISSUE TITLE
Duda con diferencia

### ISSUE THREAD

**Issue by drosselot** [IIC2413/Syllabus-2021-1#25]
Hola, quería saber si una diferencia podría funcionar si las relaciones tienen diferentes nombres de atributos pero están en el mismo orden.

**Comment by arpincheira** [comment]
Hola, los nombres de los atributos de ambas tablas deben calzar entre si para poder realizar la operación de resta, tal como se muestra en las diapositivas del curso:

![image](https://user-images.githubusercontent.com/37157550/112638578-296b6800-8e1e-11eb-9ce6-b8e278263b64.png)
