### ISSUE TITLE
[Entrega 2] Pares - Duda Datos despachos.csv

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC2413/Syllabus-2021-1#250]
Hola! Al revisar los datos me surgió una duda con respecto a qué entidades están relacionados los despachos, ya que en la entrega 1 en el enunciado se nos señala que:

_**Despachos.** Cada despacho guarda un identificador y una fecha, y está asociado a
una dirección de origen, y una dirección del destino. Adicionalmente, el despacho está
asociado a un id de compra, y está realizado por un vehı́culo._

Sin embargo, en los datos entregados para importar, estos presentan una asociación también a la entidad repartidor, por lo que quería saber si es una relación que debemos considerar y agregarla a nuestras dependencias o es un error en los datos que debe ser ignorado.
Muchas gracias de antemano!

**Comment by arpincheira** [comment]
Hola, se añadió el repartidor para poder facilitar el acceso a dicha información, piensa que un repartidor está asociado a uno o más vehículos entonces no podían obtener de una manera fácil que repartidor realizó dicho despacho.

**Comment by SebaHagedorn** [comment]
Ok, muchas gracias!
