### ISSUE TITLE
Última consulta grupos impares

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2413/Syllabus-2021-1#251]
Hola. La última consulta dice:

"Seleccione un tipo de producto. Muestre las tiendas qué han registrado la venta de la mayor cantidad de productos del tipo seleccionado."

Realmente no entiendo a que se refiere :( Pienso que es mostrar las tiendas en donde el tipo de producto es el más vendido de entre todos los tipos que tienen pero no estoy seguro.

**Comment by arpincheira** [comment]
Hola, como bien sabes existen 5 tipos de productos a priori, los cuales son: 
- Comestibles
- No comestibles
- Frescos
- Congelados
- Conservas
Ahora, la idea es que, cuando yo como usuario seleccione uno de estos tipos, ustedes muestren las tiendas que han vendido la mayor cantidad de productos de este tipo(con su respectiva cantidad). Ahora, el número de tiendas a mostrar no está definido(pueden mostrar las mejores 3 o las mejores 10, pues este es un rango razonable), la idea al final de cuentas es que no muestren absolutamente todas las tiendas ordenadas según este criterio.

**Comment by fran-gl** [comment]
Hola! Aquí las ventas de productos frescos, congelados y conservas cuentan también como ventas de productos comestibles cierto? (Porque los productos comestibles se dividen en esos tres?)

**Comment by arpincheira** [comment]
Hola, lamento la demora, si esos tipos de productos cuentan como comestibles también

**Comment by fran-gl** [comment]
Oka, muchas gracias!

**Comment by raimundomartinez** [comment]
Hola! Según yo arpincheira está equivocado. No pueden haber 5 distintos tipos de productos, porque existen productos que son 'comestibles' y 'frescos' a la vez, pero uno no puede representar eso en un sólo atributo. Según yo, existen dos opciones de comestibilidad:
- Comestible
- No Comestible
Y por otro lado hay 3 tipos de comestibles:
- Frescos
- Congelados
- Conservas
Otra posible opción, que no sale en el enunciado pero podría ser posible, es que los 'No Comestibles' tengan como tipo 'No Comestible', en cuyo caso habrían 4 tipos de productos:
- Frescos
- Congelados
- Conservas
- No Comestibles
¿Algún ayudante me podría confirmar si estoy en lo correcto?

**Comment by arpincheira** [comment]
Hola, es bastante curioso pues soy ayudante jajajaja, de todas formas lo voy a explicar de mejor forma.

2 macrogrupos de productos
- Comestibles
- No Comestibles

3 Subgrupos de comestibles:
- Frescos
- Conservas
- Congelados

Ahora, se considera como tipo de producto a todo conjunto de productos que pueda ser diferenciado a partir de una o más características. Según esta definición existen 5 grupos de productos(como mencioné anteriormente) y no solo 4. De todas formas ya habíamos anticipado la interpretación que propones y fue considerado al momento de hacer la pauta así que considerar 4, 2 o 5 tipos de productos sería igualmente correcto

**Comment by felipefuentesporras** [comment]
Hola!!
Una duda respecto a las consulta que hay que hacer. ¿Es necesario manejar todos los casos (de categorías posibles) en una sola consulta o se puede tener una consulta en particular dependiendo de la categoría que se pida?
