### ISSUE TITLE
Modelo relacional Entrega 2 

### ISSUE THREAD

**Issue by Fercho19** [IIC2413/Syllabus-2021-1#253]
Hola, tengo una duda en el funcionamiento de un modelo relacional con tablas, ya que en clases solo vimos como funcionaban las relaciones de este modelo en SQT. En este entrega tenemos que adaptar el modelo E/R a uno relacional y no sabemos como funcionan las relaciones en este modelo. 

Saludos

**Comment by arpincheira** [comment]
Hola, en clases se les ensañó como crear diversas tablas. Ahora, cuando hablamos del modelo relacional nos referimos a un modelo compuesto principalmente por entidades y relaciones, los cuales pueden ser ambos representados por tablas. Un claro ejemplo de esto lo puedes ver en el control 1, en donde les entregamos una tabla con usuarios(entidad), montañas(entidad) y subió(tabla que indica si un usuario subió una determinada montaña). 

Ahondando un poco más en el ejemplo, podemos notar que este representa una relación entre montañas y usuario que requiere a su vez de cierta información adicional(que corresponde al año en el que un usuario sube una montaña), además podemos notar relación existente es N a N, pues un usuario puede subir una o muchas montañas y a su vez una montaña puede ser escalada por uno o más usuarios.

Ahora, no siempre vas a tener relaciones del tipo N es a N, sino que vas a tener relaciones del tipo 1 es a 1, 1 es a N o N es a 1. En estos casos la modelación no va a tener la obligación de crear una tabla intermedia pues lo puedes manejar a partir de las denominadas llaves foráneas, un ejemplo de esto es aquel presentado en la issue #254, en donde se puede notar que existe una relación entre el libro y su editorial sin utilizar una tabla, pues un libro puede pertenecer a una editorial y a su vez una editorial puede tener varios libros que pertenezcan a ella. Aquí, al momento de hacer relaciones a nivel de código puedes hacer algo como

```sql
SELECT libro.*
FROM editorial, libros
WHERE editorial.id = libro.editorial_id AND
editorial.id = 1;
```

lo que relacionaría los libros con las editoriales y te permitiría obtener entonces los libros que pertenezcan a la editorial de id 1 en este caso.
