### ISSUE TITLE
Relaciones solo con id y una relación

### ISSUE THREAD

**Issue by drosselot** [IIC2413/Syllabus-2021-1#254]
Hola! Quería saber si está mal que una tabla posea solo un id y otra relación x. En una parte de la entrega  veía esto como útil pero pareciera que podría ser redundante. Como ejemplo sería tener la relación "a", "b" y "c". Donde la a necesita almacenar id y nombre, la "b" igual y la "c" es una relación entre a y b. También es necesario que "a" se relacione con otra relación "d", pero no con "b", por eso pensé en hacer este tipo de relación.

**Comment by arpincheira** [comment]
Hola, efectivamente puede pasar que una entidad como tal posea solo el id que la define y llaves foráneas que la conectan con otras entidades, un ejemplo podría ser este

Editorial: id, ubicación_id, jefe_id
Libro: id, editorial_id, titulo, número_de_páginas

Aquí por ejemplo, se da a entender que existe una tabla con ubicaciones de estas editoriales(que por ahora no tienen nombre pero podrían eventualmente llegar a tenerlo) y una tabla con personas que trabajan para dicha editorial. Adicionalmente están los libros los cuales, como puedes ver en el ejemplo, pertenecen a una editorial y no dependen necesariamente de los trabajadores de esta ni de la ubicación de la misma.
