### ISSUE TITLE
[Entrega 2]  Primary Key

### ISSUE THREAD

**Issue by Melisa96** [IIC2413/Syllabus-2021-1#255]
Hola! tengo una duda acerca de la definición de Primary Key de una tabla que relaciona dos entidades N:N. Se supone que cuando hay una Primary Key esta no se repite, pero cuando hay dos ej. PRIMARY KEY(aid, bid) significa que la tupla completa aid,bid no se repite cierto? porque o sino no se respetaría la relación N:N (como en la ayudantía)
Muchas Gracias de antemano :D

**Comment by arpincheira** [comment]
Efectivamente, si pones como Primary Key a dos atributos esto quiere decir que la tupla compuesta por ellos no se puede repetir al interior de la tabla
