### ISSUE TITLE
[Entrega 2][Pares] Atributo jefe

### ISSUE THREAD

**Issue by mc-cari** [IIC2413/Syllabus-2021-1#256]
Hola, se puede asumir que el atributo jefe de las Unidades es único? Ya que solo se especifica que existe uno por unidad.

**Comment by arpincheira** [comment]
Hola, efectivamente cada unidad tiene un único jefe y, dado que un trabajador administrativo solo puede trabajar en una unidad, debería ser único

**Comment by mc-cari** [comment]
Ya gracias
