### ISSUE TITLE
[Entrega 2][Pares][Consulta 6]

### ISSUE THREAD

**Issue by Huasito-Appel** [IIC2413/Syllabus-2021-1#257]
Hola! en la consulta 6 se indica que se deje a la unidad que tenga mas vehiculos del tipo, en caso de existir empate, estoy dejando todas las unidades que empaten, esto tengo que ponerlo como supuesto en el informe? o debo cambiarlo.
gracias de antemano y saludos.

**Comment by arpincheira** [comment]
Hola, en el caso en que empaten puedes retornarlas todas sin la necesidad de añadir ningún supuesto. El supuesto lo deberías poner en el caso de que limites el número de respuestas, ahí deberías explicar el motivo por el cual limitas el número de respuestas.
