### ISSUE TITLE
Uso de operador Rho

### ISSUE THREAD

**Issue by Gustav2000** [IIC2413/Syllabus-2021-1#26]
Hola quería saber si es que cuando yo ya tengo una tabla de este tipo:

| X.uid | X.mid | Y.uid | Y.mid |
|-      |-      |-      |-      |
|...    |...    |...    |...    |

Y le aplico el operador Rho a la tabla anterior y le pongo como nombre TablaNueva. Cuando yo quiera llamar a un atributo de la TablaNueva tendré que hacer por ejemplo: _TablaNueva.X.uid_ ?

**Comment by zaertis0** [comment]
Pasaría a ser TablaNueva.uid ya que se cambio de X.uid

**Comment by Gustav2000** [comment]
Perfecto, muchas gracias.
