### ISSUE TITLE
[Entrega 2] Diagrama E/R

### ISSUE THREAD

**Issue by catalina-ramirez** [IIC2413/Syllabus-2021-1#262]
Hola!
Para el diagrama entidad relación, en el caso de que queramos hacer más tablas para dividir tipos de una misma entidad, ¿podemos asociarlas a esa entidad con un "IsA"? ¿O debe existir una relación específica entre ellos?
Espero que se entienda la pregunta,
Saludos!

**Comment by sehe4** [comment]
o usamos algo de este estilo https://josesalasasir.wordpress.com/2016/10/15/relaciones-jerarquicas-en-el-modelo-relacional/#:~:text=Las%20relaciones%20jer%C3%A1rquicas%20se%20dan,representa%20con%20un%20tri%C3%A1ngulo%20invertido. ??

**Comment by arpincheira** [comment]
Hola, recuerda que IsA se utiliza principalmente para indicar la relación del tipo herencia. Por lo que logro entender, es ese el tipo de relación que ustedes desean crear por lo que sí estaría permitido usarlo en ese caso
