### ISSUE TITLE
Duda herencia y sus keys

### ISSUE THREAD

**Issue by drosselot** [IIC2413/Syllabus-2021-1#264]
Hola! Como en clases no mostraron un ejemplo concreto de como modelar la herencia con tablas múltiples quedé con la duda de si para hacer esto esta bien modelar de la forma:
1. Tabla padre con xid como primary key + atributos generales
2. Tablas hijas con xid como foreign key que referencia a la tabla padre y primary key + atributos específicos

**Comment by DomagojVrgoc** [comment]
Lo qué planteas es correcto.

Incluso lo puedes ver en los slides sobre isA.

**Comment by drosselot** [comment]
Gracias!
