### ISSUE TITLE
[Entrega 2] Repetición de direcciones

### ISSUE THREAD

**Issue by drosselot** [IIC2413/Syllabus-2021-1#265]
Hola! Podemos asumir que dos direcciones no son completamente iguales? Es decir que una dirección sea "aaaa" comuna santiago y otra "aaaa" comuna san joaquin.

**Comment by arpincheira** [comment]
Em... efectivamente no se repiten dos direcciones en la misma comuna, pero recomiendo de todas formas utilizar los ids numéricos con los que fueron entregadas en los csv
