### ISSUE TITLE
[Entrega 2] Duda con link de ruta relativa

### ISSUE THREAD

**Issue by nicogrecod18** [IIC2413/Syllabus-2021-1#266]
Hola, ya tenemos nuestro sitio funcionando bien, solo nos queda un detalle. Nos falta cumplir con la nota 5 del enunciado: 
"Por ejemplo, link a /resultado1.php y no link a http://codd.ing.puc.cl/ grupoXX/resultado1.php"
Nos podrían dar algún tip de como lograr esto, ya que nos queda justo como NO debiese ser.
Gracias de antemano.

**Comment by arpincheira** [comment]
Hola, aquello a lo que apunta el enunciado es a que sus consultas no lleven al usuario directamente a un link del tipo ```http://codd.ing.puc.cl/ grupoXX/resultado1.php```, pues esto podría llegar a generar problemas al momento de corregir. Te recomiendo ver la[ aplicación de ejemplo de la ayudantía](https://github.com/IIC2413/Syllabus-2021-1/tree/main/Ayudantias/Ayudantia2/example-app) en el caso de que quieras un ejemplo de como manejar correctamente las consultas
