### ISSUE TITLE
Modelo de la P1 y P2 son el mismo? (Proyecto - Entrega 2)

### ISSUE THREAD

**Issue by JoseAlvarez123** [IIC2413/Syllabus-2021-1#268]
Hola buenas, tenia una consulta en las preguntas 1 y 2 de la segunda entrega del proyecto. En la que tenemos que realizar el diagrama E/R, es al modelo de la entrega 1 (mas sus modificaciones según el feedback) y el que me piden en la 2 es el resultante, luego de arreglarlo según sus dependencias? O hay que realizarle el diagrama E/R al modelo YA justificado?

Espero que se entienda la preguntaaa. Saludos!

**Comment by arpincheira** [comment]
Hola, la idea de esta entrega es que modifiquen el esquema que tenían de la entrega1 de tal forma que quede en BCNF o 3NF y que se adapte a los datos que se les entregaron para esta entrega (ojo que el feedback busca de cierta forma guiarlos a esto pero no incluye necesariamente todas las modificaciones que deben hacer). 

Luego, deben generar un diagrama entidad relación(basándose en su nuevo esquema)  y luego simplemente deben añadir dicho esquema y el diagrama a su informe para poder posteriormente justificarlo.

Notar que, aunque el enunciado indique de cierta forma un orden distinto de acción, yo encuentro mucho más práctico realizarlo en el orden en que se los acabo de explicar, dado que lo otro sería hacer el diagrama entidad relación según los datos, luego crear un esquema a partir de este(modificando el diagrama entidad relación en el caso de que sientan que algo no les quedó normalizado inicialmente) y finalmente justificarlo

**Comment by JoseAlvarez123** [comment]
Yaa perfecto, muchas gracias!
