### ISSUE TITLE
Formato de restricciones de integridad en el esquema

### ISSUE THREAD

**Issue by tcouso** [IIC2413/Syllabus-2021-1#269]
Hola,

Tenía dudas sobre si nos recomiendan usar algún formato en particular para indicar las restricciones de integridad en el esquema relacional. Revisando las diapos enontré información sobre el esquema ER, pero no sobre el esquema relacional, de modo que me entró la duda.

Saludos!

**Comment by DomagojVrgoc** [comment]
Principalmente tienen qué especificar bien llaves foránes/primarias en SQL. También tienen qué elegir un formato de datos adecuado.

Forzar restriciones de tipo de relación (1:N, 1:1) hay qué hacer cómo especificamos en las clases.

Igual para su justificación del modelo, hay qué especificar bien dependencias, y otras llaves qué no sean primarias.

**Comment by tcouso** [comment]
Perfecto, me queda más claro.

Saludos!
