### ISSUE TITLE
Surrogate Keys V/s Natural Keys

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2413/Syllabus-2021-1#270]
Hola! para la entrega 2 es espera que el  desarrollo del modelo sea  a partir de surrogate keys o natural keys. 
Para mí justificar las dependencias es más fácil haciéndolo con natural keys. En el caso que sea con surrogate keys me complica justificar las dependencias dado que solo el surrogate keys sería la llave primaria

Saludos

**Comment by DomagojVrgoc** [comment]
Lo qué elijen ustedes.

Si tienen surrogate keys, lo único qué necesitan para justificar qué la cosa sea en BCNF es listar otros keys (los naturales).
