### ISSUE TITLE
dependencias funcionales y bcnf

### ISSUE THREAD

**Issue by flobianchi** [IIC2413/Syllabus-2021-1#271]
Hola! Para la entrega 2 en la parte de justificar el modelo hay que enlistar las dependencias funcionales de cada tabla. 

En algunas tablas me ocurre que hay mas de una llave candidata a PRIMARY KEY, por lo que a la hora de enlistar las dependencias no se si deberia hacer solo las PRIMARY KEY -> Atributo o tambien las llavecandidata2 -> atributo. 

Tampoco me queda claro si tengo que elinstar todas las relaciones a->b, a->c, a->d y a->b,c,d o basta solo con la ultima (puesto que las demas se deducen de esta con la materia vista en clase).

Por ultimo tengo una pregunta respecto a bcnf: en ciertas bibliografias vi que si una tabla tiene mas de un candidato a primary key igual esta en bcnf, mientras que en otras partes senalan que esto no deberia ocurrir porque es redundante. Construi mis modelos basandome en lo primero, pero igual queria preguntar para salir de dudas.

Muchas gracias :)

**Comment by DomagojVrgoc** [comment]
> En algunas tablas me ocurre que hay mas de una llave candidata a PRIMARY KEY, por lo que a la hora de enlistar las dependencias no se si deberia hacer solo las PRIMARY KEY -> Atributo o tambien las llavecandidata2 -> atributo.

Se requiere listar todas. Con esto tienes tu justificación.

> Tampoco me queda claro si tengo que elinstar todas las relaciones a->b, a->c, a->d y a->b,c,d o basta solo con la ultima (puesto que las demas se deducen de esta con la materia vista en clase).

Basta con la última.

> Por ultimo tengo una pregunta respecto a bcnf: en ciertas bibliografias vi que si una tabla tiene mas de un candidato a primary key igual esta en bcnf, mientras que en otras partes senalan que esto no deberia ocurrir porque es redundante. Construi mis modelos basandome en lo primero, pero igual queria preguntar para salir de dudas.

Te deberías basar en la clase de depencdencias. Para aclarar estas dudas agregamos nuevos slides en esta clase (58-61), y un ejemplo en la slide 100.

**Comment by flobianchi** [comment]
Me surgio otra pregunta! hay ciertos atributos en la instancia que nos dieron que son unicos (como los nombres) y por ende podrian ser candidatos a llave, pero en otra instancia estos podian eventualmente repetirse (como que dos personas se llamen juan soto por ejemplo). Como en esta instancia son unicos los deberiamos considerar como candidatos a llave? o ya que sabemos que mas adelante se podrian repetir no los consideramos?

**Comment by arpincheira** [comment]
Efectivamente pueden asumir que más adelante los atributos se pueden repetir, por lo que es ideal considerar como llave algún atributo más confiable o que ustedes sepan que siempre va a ser único (proyectando su aplicación a futuro).
