### ISSUE TITLE
Foreign Keys y BCNF 

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2413/Syllabus-2021-1#272]
Hola tengo una duda respecto a como justificar una foreing key en un modelo BCNF. 
Por ejemplo, tengo una tabla de restaurantes que contiene los siguientes atributos restaurantes(RID, dirección, comuna_id) y una tabla de comunas(CID, nombre_comuna). El atributo de comuna_id de los restaurantes es una foreign_key de la tabla comunas. Para justificarlo en BCNF. El RID -> dirección, comuna_id y CID -> comuna. Por lo tanto, RID -> direccion, Cid. 
Sin embargo, tengo la duda si solo con poner dicha lógica esta correcto para respaldar el BCNF. Tampoco estoy seguro si lo que hice está en BCNF. ¿Cuáles son los pasos para evaluar si lo que estoy haciendo está en BCNF,  3NF o simplemente esta todo incorrecto?

**Comment by DomagojVrgoc** [comment]
Foreign key es una cosa aparte. BCNF se justifica al nivel una tabla sola.
