### ISSUE TITLE
[Entrega 2][Diagrama grupo par] ¿Como representar un aitributo?

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2413/Syllabus-2021-1#273]
Hola. Tengo la intención de poner en el diagrama del modelo que un atributo de las `unidades` es su `jefe`. En los csv que nos entregan sale este atributo indicado con el id del jefe, y tengo pensado colocarlo así mismo en el esquema (Unidad(id, jefe,...)). Mi pregunta es si, en el diagrama, en el elipse hay que colocar solo _jefe_ e indicar en el informe que este está representado en el esquema mediante su id, o si hay que colocar explícitamente _id jefe_.

Gracias por su tiempo

**Comment by DomagojVrgoc** [comment]
Tienes qué distinguir entre el diagrama E/R y el esquema relacional qué se genera en base de este ER.

En particular, y esto ya vieron en clases, para este tipo de relaciones jefe si puede ir a la **tabla** de unidades, pero en terminos del diseño E/R, tienen qué especificr en base de qué se genra esta asociación. 

Por si preguntas solo por el nombre del atributo, puedes poner cualquiera, pero especificar bien desde dónde viene. De nuevo, cuando se modelan cosas correctamente en E/R no hay este tipo de confusiones.
