### ISSUE TITLE
Tabla personal y atributo clasificación

### ISSUE THREAD

**Issue by fbouchon** [IIC2413/Syllabus-2021-1#274]
Hola! La tabla personal la repartimos en tres tablas distintas, una que contiene la informacion personal (id,nombre, edad, rut, sexo, clasificacion) otra que es de administrativos (id, clasificacion) y otra para repartidores (id, tipo de licencia). Resulta que los repartidores tiene el atributo clasificacion vacío entonces al momento de poblar las tablas me esta ocurriendo una error. Queria saber si sería posible eliminar el atributo clasificacion de la tabla  que contiene infomracion personal, ya que como ya hicimos la separación previa, ese dato es redundante porque se puede saber la clasificación con el id de la persona solamente.

Muchas gracias!

**Comment by arpincheira** [comment]
Hola, estás seguro de que dicho atributo va en esa tabla y no en otra? Creo que lo mejor es que sigas tu intuición y veas como evitar tener datos nulos y eso
