### ISSUE TITLE
Cuestionario Control Bonus

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2413/Syllabus-2021-1#275]
Hola! ¿Podrían por casualidad habilitar el cuestionario para el control bonus por favor? Para así poder aprovechar el fin de semana largo más tranquilo. Y si también pudieran subir la clase del miércoles 19 de mayo también se los agradecería mucho.

**Comment by DomagojVrgoc** [comment]
Ya están. Disculpen la demora.
