### ISSUE TITLE
[Entrega 2][Impares] Duda con comprasV2.csv

### ISSUE THREAD

**Issue by fran-gl** [IIC2413/Syllabus-2021-1#276]
Hola! En el archivo comprasV2.csv está la fila "223,26,607,393,3,8" y la fila "223,26,607,393,4,8". ¿Esto significa que en la compra con id 223 la cantidad total comprada del producto con id 393 es 7 (4+3)? Pregunto porque ambas hacen referencia a la misma compra y al mismo producto, pero tienen cantidades diferentes, y no me queda claro si para obtener la cantidad total del producto en esa compra habría que sumar las cantidades de cada fila o no. Muchas gracias de antemano.

**Comment by arpincheira** [comment]
Hola, efectivamente se espera  que ustedes sumen dichos valores, quedando entonces "223,26,607,393,7,8" en su archivo de compras resultante

**Comment by fran-gl** [comment]
Perfecto, muchas gracias!
