### ISSUE TITLE
[Entrega 2] Duda Diagrama E/R

### ISSUE THREAD

**Issue by Nicobuzeta** [IIC2413/Syllabus-2021-1#277]
Hola, tenemos una duda sobre el diagrama relacion que se debe realizar.

<img src='https://user-images.githubusercontent.com/11426247/119077162-cb907200-b9c1-11eb-892d-add407b7699c.png' width=500 />

Como podriamos describir esta misma relacion, pero donde Vino no tiene su propia tabla. Por ejemplo, tenemos nuestra tabla de Tours y una tabla de ToursVinos, pero sin la tabla de Vinos. Donde solo guardamos el nombre del vino en la tabla de ToursVinos.

Se representaria como solo la tabla (Tours) junto a la relacion (ToursVinos) o existe alguna forma especial para este tipo de relacion?

Saludos

**Comment by DomagojVrgoc** [comment]
No entieno porqué quieren algo así, pero pueden tener una entidad Vino con solo el vid cómo su atributo. Después crean la tabla ToursVinos(tid,vid), dónde tid es la llave de tours, y vid de Vino. En este caso igual sería bueno tener una tabla para Vino, pero si no la quieren OK.
