### ISSUE TITLE
[Entrega 2] [Pares] Duda BCNF

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC2413/Syllabus-2021-1#278]
Hola! No entiendo muy bien cómo crear la tabla de relación para una relacion N - N, en clases solo se vió como dejarlo en 3NF y no me queda muy claro cómo debiésemos estructurarlo para que esté en BCNF. Tampoco he encontrado material en internet que lo explique por si podrían hacer una breve explicación o guiarme por favor :smiley:

**Comment by DomagojVrgoc** [comment]
Por defecto te queda en bcnf.

Piensa en el ejempo de: Viñas(vid,..), Tours(tid,...), y su relación ViñasTours. Llave de Viñas es vid, de Tours es tid. Le mostramos qué la tabla de la relación ViñasTours es ViñasTours(vid,tid). La única llave de esta tabla es (vid,tid), y está en BCNF.

**Comment by SebaHagedorn** [comment]
Ok, ahora me quedó mas claro. Gracias! :smiley:
