### ISSUE TITLE
Natural Join

### ISSUE THREAD

**Issue by pilarjimenez** [IIC2413/Syllabus-2021-1#28]
Hola! 
Al momento de usar natural join y tener un segundo atributo en común (en el caso de los ejemplos de la guía "nombre"), ¿es válido que, en lugar de agregar la condición del join, utilice un rho para renombrar el atributo extra y utilice un natural join sin condiciones? (En el caso de la guía cambiar el atributo "nombre" de Tours por "toursnombre" y hacer natural join entre las 3 tablas, por ejemplo) Más que nada porque se me sale la consulta de la página en overleaf.

**Comment by ValentinaAlvarezG** [comment]
Hola! sí, es válido lo que planteas.
