### ISSUE TITLE
Matching Parcial

### ISSUE THREAD

**Issue by DomingoCarvajal** [IIC2413/Syllabus-2021-1#283]
Hola! Se nos pide que las consultas sean con matching parcial. En el enunciado se muestra un ejemplo pero no una definición.

Que significa específicamente matching parcial? que contenga al string? que si tiene o no tiene una "s" al final da lo mismo? No me queda claro con el ejemplo.

**Comment by arpincheira** [comment]
Hola, con matching parcial se refiere a que se debe admitir que el input sea un substring del atributo.

Ahora, como ejemplo, imagina una base de  datos con países de Europa. Si me pidieran ingresar en una consulta el nombre de un país, yo debería ser  capaz de entregar como input fran, ancia o francia y en los tres debería retornar los mismos resultados.

**Comment by mpbosnic** [comment]
Hola!

En tu ejemplo, si el input fuera "f" deberíamos entregar todos los países que contienen una f en su nombre?

Saludos!

**Comment by arpincheira** [comment]
Hola, efectivamente sería así.

**Comment by fedezang** [comment]
si el input es vacio, "", debería entregar a todos los paises o ninguno?
