### ISSUE TITLE
Dudas consulta impar y Justificación BCNF  Entrega 2 

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2413/Syllabus-2021-1#284]
Hola! Espero estén bien, tengo dudas variadas de la entrega 2 y agradecería mucho si me pueden ayudar:

1.  En la cosulta 2 de los impares, al pedirnos el los jefes de una comuna, ¿el resultado tienen que ser una instancia de jefe (con su rut, edad, etc...), o puede bastar con un identificador y el lugar donde trabaja? ¿esto se aplica también cuando nos piden tiendas por ejemplo? si hay que mostrar la instancia entera o basta tener un identificador.
2.  En cuanto a BCNF tengo algunas dudas con la actualización del PDF que se hizo:
2.1. Si tengo A(aid, atr1,atr2, atr3), donde  aid es llave primaria y atr1, atr2 son candidatas a llave, me motiva decir que (aid, atr1,atr2) es superllave, luego cuando nos piden listar las dependencias ¿basta con poner (aid, atr1,atr2) -> atr3 cierto? no tengo que descomponer por cada elemento de la superllave.
2.2.  Cuando tengo una tabla de relación N:N, que tiene una llave primaria de dos atributos aid, bid, digamos C(aid, bid), acá para justificar que está en BCNF basta con que diga que la única dependencia es (aid, bid) -> (aid, bid) no?, pero en el caso en que tuviese  C(aid, bid, atr1), tendría que poner que (aid, bid) -> (aid, bid)  y (aid, bid) -> atr1 o sólo la segunda?

Muchas gracias de antemano!

**Comment by DomagojVrgoc** [comment]
1. Si, con todos los datos. Esto puede implicar hacer un join más, dependiendo de cómo modelan sus datos.
2.1 Si las llaves son aid, atr1, atr2 basta con decir qué esto son las llaves, y no hay más dependencias no triviales. En estricto rigor, si aid es llave, entonces, tabién (aid,atr1), (aid,atr2), (aid,atr3), (aid,atr1,atr2),... etc. son superllaves, y implican todo, pero para justificar su modelo, basta decir qué aid, atr1, y atr2 son llaves, y qué no hay ningúna dependencia dónde el lado iyquierdo no es una superllave. En la práctica, lo único en dependencias qué nos interesa son: (a) con llave al lado izquierdo; (b) con algo qué no es una superllave, ni una llave al lado izquierdo.
2.2 En los dos casos basta con decir qué (aid,bid) es la única llave, y qué no hay dependencias qué no contienen esta llave.

**Comment by Jamesmoreno21** [comment]
Muchas gracias profe!
