### ISSUE TITLE
BCNF: Dependencias con solo una  superllave 

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2413/Syllabus-2021-1#285]
Hola, me gustaria saber en el caso que solo todos los atributos  en su conjunto es la unica superllave estaría en BCNF o 3NF
En el ejemplo del siguiente Stackflow https://stackoverflow.com/questions/7840208/bcnf-table-design-multiple-values
La tabla ProductCategory(ProductID, CategoryID) tiene una sola  superllave la cual es ProductID, CategoryID debido a que es la unica combinacion de atributos que determinan todos los atributos de la tabla. 
Sin embargo, resulta extraño que la unica superllave sea justamente la que tiene todos sus atributos. Es decir, ProductID, CategoryID --> ProductID, CategoryID
En dicho caso, la tabla estaría normalizada bajo 3NF o bajo BCNF. 
Por un lado está en BCNF debido a que solo el conjunto ProductID, CategoryID --> todos los atributos
Pero también puede ser 3NF debido a que no existen otras dependencias. 
¿Están bien planteada la justificación de ambos? o me estoy enredando en algo que no debería

**Comment by DomagojVrgoc** [comment]
Cada BCNF es 3NF también (pero no vice versa).

En tu caso, la tabla está en BCNF. No hay nada raro de qué todos los atributos sean la llave. En tu caso, esto ocurre porqué se trata de una tabla qué modela asociación entre dos entidades en una modelación ER.
