### ISSUE TITLE
Licencias

### ISSUE THREAD

**Issue by drosselot** [IIC2413/Syllabus-2021-1#286]
Hola! En la entrega 1 dijeron que se podía asumir que los repartidores tenían una sola licencia, pero ahora esto cambia con los datos que nos entregan. Esto no es una relación ya que solo depende de la persona, pero no sabría presentarlo en el diagrama, porque tampoco es un solo atributo. ¿Puedo asumir que si el repartidor tiene una licencia es porque está designado a este tipo de vehículo? Si no ¿podría ser que un atributo del diagrama sea una tabla completamente nueva dentro de la base de datos?

**Comment by arpincheira** [comment]
Dado que ese es un problema con los datos se va a tomar en consideración eso al momento de revisar los modelos que entreguen, de todas formas es válido crear una tabla de licencias repartidores(a modo de relación 1 es a N) y que asocie al personal con los tipos de licencia que posee e incluso pueden crear una relación N es a N entre ambos(licencia y personal).

Ojo que, aunque sea válido hacerlo, depende de ustedes poder justificar que esté o no en BCNF o 3NF
