### ISSUE TITLE
[Entrega 2] [Grupo Impar] Duda consulta 6

### ISSUE THREAD

**Issue by margavicunas** [IIC2413/Syllabus-2021-1#287]
Hola!
Hice la consulta 6 sin problemas pero quería confirmar si la entendí bien. 
Dice: "Muestre las tiendas que han registrado la venta de la mayor cantidad de productos del tipo seleccionado". Asumí que venta no es venta total (suma de cantidades vendidas de ese producto) entonces la pensé como "para cada tienda se debe buscar entre sus ventas la que haya comprado la mayor cantidad de un tipo de producto, y luego ordenar las tiendas según esa cantidad" 
Tipo:
Tienda 1 en su mayor venta vendió cant 10 de tipo_producto
Tienda 3  en su mayor venta vendió cant 8 de tipo_producto
Tienda 2  en su mayor venta vendió 3 de tipo_producto
(Entiendo que al final sólo debo mostrar la tienda pero para ejemplificar la lógica por la cual deben ordenarse)

¿La entendí bien? ¿o implícitamente se trata de la cantidad vendida total de un tipo de producto?

Espero que se entienda jeje.
Saludos y muchas gracias!

Pd. Creo que ya habían respondido esto pero no logré encontrar la issue :c Si es así mil disculpas por el duplicado.

**Comment by arpincheira** [comment]
Hola, efectivamente se contestó en una issue(#251 para ser exactos). Ahora, la idea es que sea  la cantidad total vendida de un cierto tipo de producto. Sería como: "De todas las tiendas que se tienen, ¿Cuáles fueron las que vendieron más productos de dicho tipo?".

Lo otro, al igual como se mencionó en la issue anterior, la cantidad de tiendas a mostrar(dado que dice tiendas y no tienda) queda a su elección, yo recomiendo mostrar las primeras 10.(pero pueden mostrar menos también si lo encuentran necesario)

**Comment by margavicunas** [comment]
Yaa bacán. Millones de gracias :D
