### ISSUE TITLE
database "grupoXXe2" does not exist

### ISSUE THREAD

**Issue by clementevalladares** [IIC2413/Syllabus-2021-1#288]
Hola, al utilizar el comando \c dentro de la consola de psql me tira error diciendo que la base de datos de mi grupo (10) para esta entrega no existe. Tampoco puedo crear esta base de datos puesto que no tengo los permisos. Tengo otra forma de crearla? O ya debería estar creada?
![image](https://user-images.githubusercontent.com/69611854/119270423-a1f66700-bbca-11eb-86ad-d7b4f0d9f616.png)

**Comment by arpincheira** [comment]
Acabo de creárselas, aunque es peculiar que no estuviera creada

**Comment by clementevalladares** [comment]
Gracias!
