### ISSUE TITLE
Problemas servidor

### ISSUE THREAD

**Issue by mpbosnic** [IIC2413/Syllabus-2021-1#289]
Hola!

Al intentar conectarnos al servidor a veces se demora mucho para ingresar y ejecutar comandos básicos. Por ejemplo, al conectarme con el comando ssh se demora a veces muchísimo para responder. A veces cuando logramos conectarnos el servidor deja de responder completamente. Nos pasa en distintos computadores ¿Saben a qué se puede deber? 

Saludos y gracias!

**Comment by arpincheira** [comment]
Hola, probablemente se debe a la alta demanda que está teniendo el servidor actualmente, de todas formas vamos a estar analizando el servidor, de todas formas, en el caso de que se caiga agradecería que avisaran por aquí para tratar de restaurarlo lo antes posible.

**Comment by chineseJack564** [comment]
Hola, parece que se cayo el servidor ahora, si pueden revisarlo , gracias!

**Comment by Gsalinas1506** [comment]
iba a comentar lo mismo, llevo esperando un rato para conectarme al server y no reacciona

**Comment by Gsalinas1506** [comment]
Iba a comentar lo mismo. Yo tampoco puedo ingresar

**Comment by arpincheira** [comment]
Hola, aparentemente el servidor está funcionando.
