### ISSUE TITLE
Duda consulta 5 Control 1

### ISSUE THREAD

**Issue by Julius9** [IIC2413/Syllabus-2021-1#29]
Tengo una duda con la pregunta 5 específicamente la condición de haber subido un Munro, ¿esto significa que el usuario ha subido exactamente solo un Munro o puede que haya subido más de una montaña tipo Munro ?

**Comment by ValentinaAlvarezG** [comment]
Hola! no, con "haber subido un Munro" nos referimos a **al menos un munro**

**Comment by Julius9** [comment]
gracias :D

**Comment by jnbaltra** [comment]
> Hola! no, con "haber subido un Munro" nos referimos a **al menos un munro**

¿Habrá algún problema si lo consideré como exactamente un Munro? 
Recién vi esta issue y ya tengo listo el control :(

**Comment by ValentinaAlvarezG** [comment]
Hola! @jnbaltra no hay problema, te lo consideraremos igual, pero tiene que efectivamente estar buena la consulta para  lo que planteas.
