### ISSUE TITLE
consulta 2 y 5 [Entrega 2][Proyecto][Impar]

### ISSUE THREAD

**Issue by CamilaArgomedo** [IIC2413/Syllabus-2021-1#290]
¿A qué se refieren con comuna en las consultas 2 y 5? en los datos solo veo que den las comunas de cobertura y no la de ubicación de la tienda, pero la redacción de la consulta me hace pensar que se refieren a la ubicación.

**Comment by arpincheira** [comment]
Hola, efectivamente se refiere a la comuna en la que se ubica la tienda. Ahora, la información de esto si se encuentra en los datos entregados y no te puedo indicar como obtener lo solicitado pues es lo que se les pide contestar(como pista: cobertura != ubicación).

**Comment by CamilaArgomedo** [comment]
Oka! no había cachado que la carpeta general de los datos también se tenia que usar! ahora la vi:)
