### ISSUE TITLE
Mover documentos dentro del servidor

### ISSUE THREAD

**Issue by drosselot** [IIC2413/Syllabus-2021-1#291]
Hola! Estoy tratando de mover documentos a mi carpeta Sites pero no se el comando que puedo usar para esto. Para la entrega 1 era simplemente hacer pull desde git, pero ahora como la carpeta no es del repositorio, no puedo hacer esto directamente.

**Comment by arpincheira** [comment]
Hola, podrías crear un archivo `.gitkeep` en la carpeta Sites de tu grupo al interior del servidor con el comando `touch .gitkeep`, luego hacer un push desde el servidor a tu repositorio para añadir la carpeta de Sites a este. Posteriormente haces un pull desde tu computadora y deberías tener la carpeta Sites

**Comment by drosselot** [comment]
Gracias! Eso me sirvió!
