### ISSUE TITLE
Duda consulta 3 impares

### ISSUE THREAD

**Issue by sreitze** [IIC2413/Syllabus-2021-1#292]
Hola, en la consulta 3, al decir "Muestre todas las tiendas que venden al menos un producto de dicha categoría", no me queda claro a que se refiere con categoría. ¿Se refiere solamente a Comestibles o No Comestibles? o se refiere a todos los tipos de comestibles, junto a No comestibles. 
Gracias de antemano.

**Comment by arpincheira** [comment]
Hola, te recomiendo ver la issue #251, ahí se habla mucho más del tema.
