### ISSUE TITLE
[Entrega 2][Matching Parcial][Impar]

### ISSUE THREAD

**Issue by DomingoCarvajal** [IIC2413/Syllabus-2021-1#293]
Hola! Se respondió en la issue #283 que la búsqueda debía contener al string de input. Esto llevaría a que hayan mas casos que solo uno para buscar. Por ejemplo buscar una comuna que contenga "la", puede ser "la ligua" o "la serena". Asumo que hay que mostrar para ambas comunas. 

El problema es que en las consultas no se pide el nombre de la comuna, por lo que no sabrías por cual de las 2 comunas hizo match una tupla. Por ejemplo, los promedios de trabajadores darían 2 números sin ninguna comuna asociada.

Es por esto que encontramos que lo mejor era mostrar la comuna para que se pueda diferenciar. Aplicamos esto para las consultas 2, 4 y 5. Es válido hacer esto? El enunciado no lo pide entonces no estábamos seguros si es que se podía implementar de esta manera.

Gracias!

**Comment by arpincheira** [comment]
Hola, efectivamente es válido y se agradece mucho que lo hagan

**Comment by mc-cari** [comment]
Hola, se puede omitir este dato en casos que complejice mucho la consulta? (grupo Par)
