### ISSUE TITLE
[Entrega 2][Diagrama E/R] Plataformas para realizarlo y dudas de estilo

### ISSUE THREAD

**Issue by jagaldames** [IIC2413/Syllabus-2021-1#294]
¡Hola! Primera duda, dónde se recomienda realizar el diagrama E/R. ¿Draw.io u otras plataformas? Digo esto porque he encontrado un par de herramientas online para diseñar los diagramas y se puede exportar al código SQL pero las que he visto no usan el mismo "estilo gráfico" que vimos en clases o que aparece en la solución de la guía de diseño. ¿Hay un estándar que seguir o basta con que se entienda? Mis otras dudas son: ¿Se pueden usar tablas con detalles en vez de los rectángulos y burbujas? Si tengo un rombo (relación) que tiene un atributo extra, ¿se le debe poner una burbuja al rombo? (Caso montañistas y montaña, en que la tabla de relación agregaba el año que se había subido) 
Dejo pantallazos para ejemplificar.
![image](https://user-images.githubusercontent.com/17708598/119389924-472c4080-bc9a-11eb-9b99-4f2bf4043177.png)

![image](https://user-images.githubusercontent.com/17708598/119389984-5ca16a80-bc9a-11eb-98ff-6f46c3716cb7.png)

![image](https://user-images.githubusercontent.com/17708598/119390020-67f49600-bc9a-11eb-822b-21fef4e977c9.png)

**Comment by arpincheira** [comment]
Hola, en lo que respecta al tipo de herramienta a utilizar para poder realizar el diagrama, yo te recomiendo utilizar únicamente aquella que más te acomode. Ahora, en lo que respecta al estilo, lo ideal siempre va a ser que ocupen aquella que se les indicó en clases y, en el caso de que prefieran tomar alguna otra alternativa, les recomiendo poner una mini leyenda en donde indiquen a los ayudantes el como funciona la simbología de esta.

Ahora, con respecto a la otra pregunta,   sí, pueden existir casos en los que se deba asignar un atributo adicional a una relación
