### ISSUE TITLE
[Entrega 2] [Par]Consulta 4

### ISSUE THREAD

**Issue by chineseJack564** [IIC2413/Syllabus-2021-1#295]
Hola,
En la 4 nos pide ingresar un tipo de vehiculo, eso se refiere tipos como 'auto', 'camnion', etc?
O es como 'fresco', 'fria', etc.

Tengo 2 dudas respecto a la entrega en general:

1. Queda a nuestro criterio que cosa mostrar en cada consulta?
2. Cual es el formato esperado de esquema relacional?

**Comment by arpincheira** [comment]
Hola, en el caso de los vehículos estos poseen un atributo tipo así que se refiere a eso. Ahora, lo ideal es mostrar datos con tal de que se pueda identificar a que corresponde la respuesta entregada y, en el caso de que no se indique exactamente que atributo debes mostrar de una entidad en específico, recomiendo fuertemente mostrar todos los atributos base de estos.
