### ISSUE TITLE
Foreign Key sobre un valor nulo, referenciado a una primary key

### ISSUE THREAD

**Issue by dedmu5** [IIC2413/Syllabus-2021-1#296]
Hola, tengo una relacion1(id,b,c) cuya estructura es la siguiente: 

|  id  |  b   |  c   |
|-----|------|------|
|   1 | 2    | Null |
|   2 | Null | 1    |
|   3 | 4    | Null |
|   4 | 5    | Null |
|   5 | Null | 2    |
| ... | ...  | ...  |

Notar que cuando b es Null c no lo es. Quiero hacer una foreign key sobre b y c referenciada a dos valores de dos tablas distintas, respectivamente. Ambos de estos valores son primary key. Cuando intento hacer esto sql me tira el error:
null value in column "b" violates not-null constraint
y el error:
null value in column "c" violates not-null constraint

No sé como solucionar este error, ya que me gustaría solo crear la foreign key para valores no nulos de b y c. Es decir, que cuando se borre un elemento de una de las dos tablas referenciadas solo se borre un elemento de relacion1 si el valor de b o c no son nulos y uno de los dos es igual al valor referenciado borrado.  ¿Es posible hacer esto o tengo que buscar otra forma de implementarlo?
Pensé en colocar un valor -1 "simbolizando" el valor Null, pero para eso tendría que ingresar un valor -1 en las tablas referenciadas, y no sé si eso es una mala práctica, ya que estaría ingresando un "dato auxiliar" solo para saltarme este error.

Saludos!

**Comment by arpincheira** [comment]
Hola, te recomiendo fuertemente pensar en como modelar aquello que propones. A modo de consejo, un indicador de que tu modelo está correctamente implementado es el que tus tablas no posean valores nulos(estos a veces se pueden llegar a dar en distintos tipos de bases de datos, pero en las relacionales lo ideal es que no suceda).
