### ISSUE TITLE
[Entrega 2] [impares] [Consulta 1] 

### ISSUE THREAD

**Issue by RMMURUA** [IIC2413/Syllabus-2021-1#298]
Hola! Para la consulta 1 se pueden mostrar las tiendas con las comunas sin agrupar las tiendas? es decir, que se vea como la tabla de arriba en vez de la de abajo en la foto adjunta. Mil gracias de antemano
![Captura de Pantalla 2021-05-24 a la(s) 20 53 01](https://user-images.githubusercontent.com/48321595/119432562-8b433380-bce2-11eb-903c-8b6993644458.png)

**Comment by arpincheira** [comment]
Hola, en esta entrega si se puede.
