### ISSUE TITLE
Duda Consulta 5 Guía 1

### ISSUE THREAD

**Issue by sebastian-contreras-r** [IIC2413/Syllabus-2021-1#3]
De acuerdo con la solución de la guía 1, la consulta 5 es Tour - ToursV, pero Tour y ToursV tienen distintas cantidades de atributos (Tour contiene tid, nombre, duración y precio, mientras que ToursV solo contiene nombre). No se debería poder hacer la diferencia Tour - ToursV, ¿o sí?

**Comment by JosefaPaz** [comment]
¡Hola!

Por definición, para utilizar **diferencia** las relaciones deben tener los mismos atributos, por lo que en este caso no sería posible hacer la diferencia.

Espero quede claro! 😄
