### ISSUE TITLE
DUDA CON SELF- JOIN Y EJERCICIO  DE LA GUIA 

### ISSUE THREAD

**Issue by betolguin** [IIC2413/Syllabus-2021-1#30]
Hola! tengo una pregunta con como funciona el self join, ya que por lo que entendí al hacer un join con la misma tabla te va a crear 2 distintas, pero que al final tendrán los mismos atributos, por lo que no logro entender bien su utilidad. Felíz si alguien me puede explicar un poco mejor :). 

La segunda pregunta es que en el ejercicio de la siguiente imágen: 

![image](https://user-images.githubusercontent.com/69482524/112654699-6ccdd280-8e2e-11eb-8f7b-25516ae8b074.png)

No me queda claro como es el filtro que va haciendo que solo se quede con los más baratos, es decir, qué es lo que se pregunta el algoritmo al realizar la consulta? nose si se entiende bien mi pregunta, ojalá que si..

muchas gracias de antemano y cualquier cosa quedo atento! 

saludos

**Comment by DomagojVrgoc** [comment]
Pregunta 1:
Cómo planteas en tu pregunta el self join es un join de la tabla consigo misma, pero bajo algunas condiciones. Si uno realmente hace un join natural de la tabla consigo misma se queda con la misma tabla cómo el resultado.

Cuando hablamos de self join, uno normalemnte piensa en el join de la tabla consigo misma, pero no sobre todos los atributos. Normalmente uno pone un alias a la tabla para poder especificas esto. Por ejemplo: si tengo T(a,b) y quiero hacer el self join sobre el a no más, hago un renombramiento del estilo T->T1, T->T2, y despues se hace el join T1 x_{T1.a=T2.a} T2.

Pregunta 2:
No es un filtro directo. En realidad la cosa se filtra en la última linea, dónde vas a sacar las filas de la tabla Tours qué corresponden a un tour qué no es el más caro.

**Comment by betolguin** [comment]
Claro, pero en este mismo ejemplo que mencionó ud "si tengo T(a,b) y quiero hacer que el uno mismo se una sobre el no más, hago un renombramiento del estilo T->T1, T->T2, y despues se hace la unión T1 x_{T1.a=T2.a} T2." no entiendo finalmente que es lo que obtendría con eso? de verdad me confunde :o 

y en la pregunta 2, la duda es que no me queda clara esta parte especificamente como va comparando los numeros, ya que me imagino que va "mapeando" los datos que estan en la misma posición, por lo que siempre estaria comparando numeros iguales o nada que ver? por ejemplo si tengo
![image](https://user-images.githubusercontent.com/69482524/112661694-90484b80-8e35-11eb-9611-000e8079f5af.png)

como va comparando los numeros, luego de hacer el producto cruz ya que me imagino que va "mapeando" los datos que estan en la misma posición, por lo que siempre estaría comparando números iguales o nada que ver?

quedo atento!

**Comment by DomagojVrgoc** [comment]
Ojo: T1 x T2 tiene cuatro atributos (es un producto cruz).

En T1 x T2 tienes cosas como: (tour1,precio1,tour2,precio2) (y mas cosas).
