### ISSUE TITLE
[Entrega 2] [E/R] Duda sobre relaciones entre tablas padres - hijas y externas 

### ISSUE THREAD

**Issue by pedroriosg** [IIC2413/Syllabus-2021-1#301]
Hola, tengo la siguiente duda!

Tengo una tabla A, la cual es padre de B. Ambas se relacionan a través de la PRIMARY KEY  de A.
Por otro lado, tengo una tabla X que se relaciona con B a través de la PRIMARY KEY de X. 
Mi duda es si para el esquema E/R, la flecha desde X va hacia la tabla A o hacia la tabla B.

Saludos y muchas gracias de antemano

**Comment by DomagojVrgoc** [comment]
Hacia B.
