### ISSUE TITLE
[Entrega 2] Duda Foreign Keys en Esquemas.

### ISSUE THREAD

**Issue by ssoliva** [IIC2413/Syllabus-2021-1#303]
Hola! Tengo la duda si hay alguna notación para representar las *Foreign Keys* en los esquemas, o si simplemente se agrega al final de los atributos algo de la siguiente forma: `Foreign Key (atributo) References Tabla(atributo_referenciado)` (similar a *SQL*).

Saludos y gracias de antemano.

**Comment by arpincheira** [comment]
Hola, queda a su criterio como mostrar las llaves foráneas al interior del esquema, lo importante es que se entienda y se entienda y se mantenga el formato del esquema(un ejemplo podría ser indicándolo explícitamente tal y como mencionas en esta issue). Ojo eso si que las primar y keys si poseen un indicador establecido(se subrayan).
