### ISSUE TITLE
Consulta dependiendo del input (consulta 3)

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2413/Syllabus-2021-1#308]
Hola!!
Una duda respecto a las consulta que hay que hacer. ¿Es necesario manejar todos los casos (de categorías posibles) en una sola consulta o se puede tener varias consultas y que se utilice una en particular dependiendo de la categoría que se pida?

**Comment by arpincheira** [comment]
Hola, efectivamente puedes utilizar diversas consultas para abarcar este problema. Lo que no puedes hacer es indicar a la persona que ingrese un input en distintos campos según el input a ingresar. Te recomiendo fuertemente buscar información sobre condicionales que se permitan cambiar la consulta según el input ingresado.

**Comment by felipefuentesporras** [comment]
Ya gracias!!
Eso si me quedo una duda respecto a esto mismo. Entonces en el pdf tendriamos que poner, por ejemplo:
Consulta 3:
Si se pregunta por categoria 1:
Select.......
Si se pregunta por categoria 2:
Select....
Si se pregunta por categoria 3:
Select.....
etc
¿Eso estaría bien?
