### ISSUE TITLE
Consulta 3 Grupo par: Fecha en las consultas

### ISSUE THREAD

**Issue by mzigm** [IIC2413/Syllabus-2021-1#309]
Hola! 

En la consulta 3 es necesario que se adapte el dropdown si se meten fechas nuevas? O en el dropdown podemos poner solo nuestras opciones.

Gracias!

**Comment by arpincheira** [comment]
Hola, la idea es que el año se genere según los datos que tienen y que no sea hardcodeado(ingresado a partir únicamente sus opciones). Es decir, si ingresas un dato con un año que no haya estado en los datos anteriores, este debería aparecer
