### ISSUE TITLE
Consultas - Control 1

### ISSUE THREAD

**Issue by BelenSilva1204** [IIC2413/Syllabus-2021-1#31]
¿Es necesario explicar/describir con palabras cada consulta? O puedo dejar sólo la expresión?

**Comment by bpardobravo** [comment]
Si crees que la dejaste muy compleja, nunca va mal una explicación para ayudar la correción, pero lo único que es obligatorio es la expresión

**Comment by BelenSilva1204** [comment]
Ok, gracias!
