### ISSUE TITLE
Consultas en página php grupo impar

### ISSUE THREAD

**Issue by francoschiaffino** [IIC2413/Syllabus-2021-1#310]
Hola. Si en una consulta nos piden los usuarios, es necesario que se muestren en la página todos los datos de los usuarios o basta con solo el nombre? Gracias!!

**Comment by arpincheira** [comment]
Hola, deben mostrar información que permita identificar al usuario. Recomiendo fuertemente mostrar toda la información que puedes encontrar normalmente en los usuarios(independiente de su posible tipo)
