### ISSUE TITLE
[Entrega 2]-Pares: Identificación despachos

### ISSUE THREAD

**Issue by cristobal-larach** [IIC2413/Syllabus-2021-1#311]
Hola, tengo una duda sobre el csv entregado para los despachos: ¿Cual es la diferencia entre "id" e "id_compra"?

**Comment by arpincheira** [comment]
id corresponde al identificador del despacho, id_compra corresponde al id de la compra asociada a dicho proceso de despacho

**Comment by cristobal-larach** [comment]
Ok, pero cual de las dos sirve como llave para un despacho? Revisando los valores de ambas columnas, ninguno se duplica
