### ISSUE TITLE
Matching Parcial y  Case-Insensitive manejado fuera de de la consulta

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2413/Syllabus-2021-1#312]
Hola!
¿El matching parcial y  case-insensitive tiene que ser manejado dentro de la consulta de SQL?¿O yo puedo procesar primero el input de tal forma de hacerlo matching parcial y  case-insensitive por otro medio?
Gracias!

**Comment by arpincheira** [comment]
Hola, la idea es que la query utilizada deba soportar el matching parcial y el case-insensitive. Ahora, hay un par de consultas cuyo input es recomendable manejarlo fuera de la query pero eso ya es un tema particular de algunas consultas
