### ISSUE TITLE
Entrega 2 [Datos] [impares]

### ISSUE THREAD

**Issue by pablomaizag** [IIC2413/Syllabus-2021-1#313]
Hola! En el excel productosV2 no existe un atributo que defina el tipo de producto, por lo que se nos hace imposible hacer la consulta 3 y 6. ¿Esta bien que lo agreguemos nosotros?

**Comment by pbyoma** [comment]
el tipo de producto se puede obtener por los atributos que tienen los productos, es decir, si tiene fecha de caducidad y peso, es producto comestible congelado, los demás atributos del producto en este caso están vacíos
