### ISSUE TITLE
Matching Parcial [Impar]

### ISSUE THREAD

**Issue by fedezang** [IIC2413/Syllabus-2021-1#314]
Hola! Tengo las siguientes dudas:
- Al hacer matching parcial, entiendo que al ingresar un sub-string, de una comuna por ejemplo, la consulta debe realizarse para el nombre de esa comuna. En el caso que yo ingrese un input vacío, debería entregar un resultado o no? ya que el string vacío será un sub-string de cualquier comuna.
- Si mi input es un sub-string de dos o más nombres de comunas, debo entregar (en el caso de la consulta 5) la edad promedio de todos los trabajadores en esas comunas, o la edad promedio en cada comuna?
Gracias!

**Comment by arpincheira** [comment]
Hola, a continuación contesto tus dudas:
- Dado que en el enunciado no se explicita que deben hacer cuando les entregamos un input vacío, queda bajo su criterio decidir que entregar. Lo importante es que lo añadan en el informe como supuesto.
- Hola, deberían entregar la edad promedio de cada comuna en ese caso
