### ISSUE TITLE
Problemas con el servidor

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2413/Syllabus-2021-1#315]
Hola, llevo mucho rato intentando usar el servidor pero se me desconecta y cuando logra conectarse anda muy lento.

**Comment by arpincheira** [comment]
Hola, me podrías indicar tu número de grupo por favor? He estado probando el servidor con 3 usuarios distintos y otro ayudante me ayudó también probándolo y todo funciona correctamente.

**Comment by mariovaldesa** [comment]
Ahora me funciona perfecto, fue ayer el problema nomás. Gracias.
