### ISSUE TITLE
Duda entre "Seleccione" y "Ingresar"  Grupos Impares

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2413/Syllabus-2021-1#317]
Hola!
Tengo una duda en el manejo del input de las consultas, dependiendo de si te dicen "Ingresar" o "Seleccionar". Cuando en la consulta 2 me dicen que se ingrese una comuna, yo entiendo que se debe tener un input de texto para poder buscar la comuna. Pero en el caso de "seleccionar", por ejemplo, en la consulta 3 cuando nos pidem seleccionar un tipo de producto, yo entiendo que debería mostrar una lista desplegable o tener distintos botones para cada producto, en vez de manejarlo por texto. Pregunto esto porque yo entendía lo ultimo en relación a las consulta tipo "seleccionar", pero issues que he leído respecto a este tipo de consultas me han hecho dudar si se refiere a esto.
Gracias de antemano.

**Comment by arpincheira** [comment]
Hola, te recomiendo ver la ayudantía, ahí se presentan los tipos de input esperados (de selección y de ingreso de texto).
