### ISSUE TITLE
Problema con imagen de fondo en index

### ISSUE THREAD

**Issue by Julius9** [IIC2413/Syllabus-2021-1#322]
Hola! tengo un problema, lo que sucede es que en index (y en todas las demás paginas) fije un background image, pero el problema es que cuando lo subo al servidor me aparece así.

<img width="1440" alt="Captura de Pantalla 2021-05-28 a la(s) 02 07 07" src="https://user-images.githubusercontent.com/26386517/119938169-fc405080-bf59-11eb-98c0-3000078261e5.png">

Pero cuando corro el servidor de php con ```php -S localhost:8000```  se ve así (como debería)

<img width="1440" alt="Captura de Pantalla 2021-05-28 a la(s) 02 07 53" src="https://user-images.githubusercontent.com/26386517/119938254-1c700f80-bf5a-11eb-9fec-b79551f4c609.png">

Cabe destacar que cuando se realiza una consulta en la pagina del servidor (codd) la imagen si se muestra, por lo que el problema solo existe en la pagina index. He intentado arreglar esto de muchas formas pero no encuentro solución, si alguien sabe por que sucede y como lo puedo resolver sería bacan. 

También en preguntar que ¿en el caso de que no lo pueda arreglar, esto implicaría no poder optar al bonus por el diseño?¿o en estos casos serán más permisivos ?

**Comment by benjavicente** [comment]
Yo tuve un problema similar, puede ocurrir que el path no es el mismo en el servidor:

```bash
# el index local
localhost:8000/index.php
# el index en el servidor
http://codd.ing.puc.cl/~grupoXX/index.php
# path 1 (relativo al directorio de arriba)
../path/archivo1.png
# path 2 (absoluto)
/path/archivo2.png

# Resultado de local + path 1
# los .. tratan de subir un directorio, *pero no hay!* se queda en localhost:8000/
localhost:8000/path/archivo1.png

# Resultado de servidor + path 1
# los .. hacen que suba a un directorio, quedando en codd.ing.puc.cl/ y no en http://codd.ing.puc.cl/~grupoXX/
http://codd.ing.puc.cl/path/archivo1.png

# Resultado de local + path 2
# queda al principio del url base:  localhost:8000
localhost:8000/path/archivo2.png

# Resultado de servidor + path 2
# queda al principio del url base: codd.ing.puc.cl/ y no en http://codd.ing.puc.cl/~grupoXX/
http://codd.ing.puc.cl/path/archivo2.png
```

Los path absolutos (los que parten con `/`) no van a funcionar bien en el servidor, pero los relativos (ej `consultas/` o `../imagen.png`) van a funcionar si es que **no ocurre que tratan de subir un directorio que no existe** en el url.

Para que funcione el path 1 en el ejemplo, tendría que ser `path/archivo1.png` en vez de `../path/archivo1.png`.

Puedes ver si esta ese problema en el servidor si hay un error de tipo `Failed to load resource: the server responded with a status of 404 (Not Found)` en la consola del navegador.
