### ISSUE TITLE
Diferencia entre Esquema y Diagrama

### ISSUE THREAD

**Issue by tvallotton** [IIC2413/Syllabus-2021-1#323]
Hola, en el enunciado dice que hay que subir al pdf un "diagrama de E/R" y un "esquema relacional". No tenemos claro cual es la diferencia. El esquema seria nuestro modelo en sql?

**Comment by DomagojVrgoc** [comment]
E/R es el dibujo con rectangulos, triangulos, etc.

Esquema relacional es la especificación de sus relaciones en SQL (o en papel). Algo tipa:
 Alumnos(aid int PRIMARY KEY, 
                 nombre varchar(20), 
                 universidad FOREIGN KEY References Universidades(uid)).
