### ISSUE TITLE
No se muestran cambios de estilo en la página web

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2413/Syllabus-2021-1#325]
Hola!
Estaba trabajando en la página para darle unos cambios de estilo y ganarme el bonus con mi compañera, sin embargo al hacer pull al servidor remoto desde git, la página ya no me muestra cambios, como solía hacerlo con cada actualización (los pulls siguen realizándose de manera correcta). No se bien que cual podría ser el problema, pensé que podría estar relacionado con branches entonces chequeé la branch en la que estaba con git branch y me muestra (HEAD detached from origin/master), no recuerdo si una detached HEAD estaba correcto o si tiene que estar attached para que funcione, porque la verdad no se muy bien lo que eso implica jaja
¿Alguna idea de que podría estar causando la desactualización de la página respecto al servidor?
Gracias de antemano c:

**Comment by benjavicente** [comment]
A varios nos paso algo así, ve que esta pasando al mostrar la consola al inspeccionar en el navegador. Puede ser [algo sobre los paths](https://github.com/IIC2413/Syllabus-2021-1/issues/322#issuecomment-850403528) (error 404) o que se guarde css en el cache (se puede hacer click derecho en el botón para recargar la página para borrarlo, con devtools abierto).

**Comment by Sofia-Arratia** [comment]
Gracias! Cómo puedo correr el php de manera local? Pasa que desde siempre estuve trabajando con el servidor directamente, así que no sé cómo comparar si efectivamente es un error de path. También, debería descargarme devtools para esto? No se bien cómo funciona 😅 Tampoco entendí bien que significa mostrar la consola al inspeccionar en el navegador, perdón lo lenta, es mi primera página web u.u Muchas gracias!

**Comment by benjavicente** [comment]
> Cómo puedo correr el php de manera local?

Pensé que a los cambios te referías a local vs servidor 😅 , tal vez no valga la pena instalarlo a estas alturas de la entrega.
[Está guía tiene links a instrucciones](https://phptherightway.com/#getting_started) para instalarlo en diferentes sistemas operativos
En ubuntu (o en wsl) se puede instalar con `sudo apt-install php7.4-cli` si no me equivoco.

> También, debería descargarme devtools para esto?

Al hacer click derecho (en chome y firefox por lo menos) hay una opción para inspeccionar la página. Eso abre _DevTools_ (o herramientas de desarrollo). Ahí uno puede ir al menu de la consola (o console) y ver si hay errores.

> (HEAD detached from origin/master)

Me salté esto y parece que eso debe ser el error. Eso quiere decir que el repositorio [no está en el último commit](https://stackoverflow.com/a/5772882).
Debería arreglarse al ir al inicia de la rama, con `git checkout <branch principal>`.

**Comment by Sofia-Arratia** [comment]
Ok! Muchas gracias! c: de todas maneras descargué php y logré cachar como correr el servidor localmente, y definitivamente hay una incongruencia entre ambos, así que revisaré lo del git y lo del path, gracias denuevo c:

**Comment by Sofia-Arratia** [comment]
Muchas gracias por todo! Resultó que tenía ambos problemas al mismo tiempo jajaj 😅
