### ISSUE TITLE
Seguridad de contraseñas en el servidor

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2413/Syllabus-2021-1#327]
Hola, me surge una duda, si inicio sesión de mi github en el servidor mi contraseña se queda guardada allí pues luego no me pide mis datos para hacer alguna acción en github, esto es seguro? alguien podría sacar mi contraseña desde algún archivo que este en el server?

**Comment by arpincheira** [comment]
Hola, efectivamente se guarda al interior del servidor dentro de un archivo al que solo tienen acceso tu y aquellos usuarios con permisos de administrador del servidor. Ahora, existen diversas maneras de poder asegurar de mejor manera la información e incluso creo que puedes habilitar otros métodos de validación de cuentas o de almacenamiento seguro de credenciales, como el que puedes encontrar [aquí](https://docs.github.com/en/github/getting-started-with-github/getting-started-with-git/caching-your-github-credentials-in-git)

**Comment by Lord-Kelsier** [comment]
muchas gracias
