### ISSUE TITLE
Símbolos en Latex

### ISSUE THREAD

**Issue by sbvillalobosm** [IIC2413/Syllabus-2021-1#33]
Hola, tengo un problema con las letras con tildes y la ñ cuando escribo las consultas en Latex. Copié la configuración que aparece en la imagen, que encontré en un archivo pero no sé qué hacen cada uno y creo que en uno de esos "packages" está el origen del problema de que no se escriban bien las letras. ¿Qué tendría que cambiar para que aparezcan las letras? En el texto simplemente no aparecen las letras, por ejemplo "Subió" aparece como "Subi" o "año" como "ao".

![image](https://user-images.githubusercontent.com/62085874/112689353-eb3f6a00-8e58-11eb-96cb-9817a18091c7.png)

**Comment by miguel-mrtnez** [comment]
Hola, intenta agregando ```\usepackage[spanish]{babel}``` y cuéntanos si se soluciona.

**Comment by sbvillalobosm** [comment]
Lo intenté y sigue igual :(

**Comment by arpincheira** [comment]
y si pruebas con:
```
\~{n}
```

**Comment by sbvillalobosm** [comment]
Tampoco funciona :((

**Comment by miguel-mrtnez** [comment]
Estoy viendo que también recomiendan ```\usepackage[T1]{fontenc}```. También puede ser que el problema no esté ahí, probé con exactamente el mismo meta y sí se me muestran los acentos. Trata iniciando con un documento completamente en blanco. En todo caso, por honor al tiempo, no te preocupes tanto por los acentos 😄

**Comment by sbvillalobosm** [comment]
Caché que el problema era solo en las ecuaciones y con lo que aparece en este link https://es.wikibooks.org/wiki/Manual_de_LaTeX/Textos_t%C3%A9cnicos/Matem%C3%A1ticas/Acentuaci%C3%B3n_en_modo_matem%C3%A1tico lo pude solucionar :D Muchas gracias por su ayuda!
