### ISSUE TITLE
Acceso ayudantía 1

### ISSUE THREAD

**Issue by Tvergara** [IIC2413/Syllabus-2021-1#34]
Hola, me pide solicitar acceso para ver la ayudantía 1. Estoy ingresado con mi cuenta UC, así que ese no debería ser el problema.

**Comment by arpincheira** [comment]
Hola, el problema era que el drive que teníamos estaba con la organización de la escuela de ingeniería, entonces solo podían ingresar personas con mail ing.puc.cl. 

De todas formas ahora debería estar solucionado el problema y el link debería seguir siendo el mismo.

Muchas Gracias por avisar.
