### ISSUE TITLE
Jefe de unidad en pagina principal

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2413/Syllabus-2021-1#348]
Hola, una pregunta. El jefe de una unidad debe ver solo la dirección de la unidad y los administrativos trabajando en ella o debe ver también su historial de pedidos e información personal?

**Comment by arpincheira** [comment]
Hola, todos los usuarios deben ver la información personal y su historial de pedido. Ahora, la única diferencia es que el jefe de una unidad debe **adicionalmente** ver la dirección de su unidad y los administrativos trabajando en ella

**Comment by Lord-Kelsier** [comment]
Muchas gracias
