### ISSUE TITLE
Fecha Entrega 1

### ISSUE THREAD

**Issue by usdonoso** [IIC2413/Syllabus-2021-1#35]
En el mail enviado hoy 29 de marzo, se especifica que la fecha de entrega del proyecto 1 es el 16 de abril, sin embargo, en las fechas de Github dice que es el 14. ¿Cuál es la correcta?

**Comment by arpincheira** [comment]
Hola, la fecha correcta es el 16 de abril, decidimos alargar el plazo de entrega del proyecto. 

Vamos a realizar los cambios en el calendario ahora.
