### ISSUE TITLE
Direcciones de usuarios al registrarse

### ISSUE THREAD

**Issue by domingo2000** [IIC2413/Syllabus-2021-1#351]
Hola, tengo una duda, los usuarios al registrarse y poner su direccion, ponen el id de la direccion, ponen el nombre y la comuna, o que ingresan, puesto que no se si la tabla de direcciones que dieron para la entrega pasada tiene todas las direcciones "posibles" o el usuario podría dar una direccion nueva, en ese caso debemos nosotros crear un registro de dicha nueva direccion (Ademas de linkearlo al usuario me refiero).

**Comment by arpincheira** [comment]
Hola, te recomiendo ver la issue que se encuentra pineada en el repositorio. ([link a esta issue](https://github.com/IIC2413/Syllabus-2021-1/issues/334))
