### ISSUE TITLE
Conexión SSH al servidor de la U

### ISSUE THREAD

**Issue by tsmatus** [IIC2413/Syllabus-2021-1#36]
Hola buenas tardes. 

He intentado conectarme por SSH al servidor que se menciono en la ayudantía pero no puedo, no se si aún no esta habilitado o tengo problemas yo para conectarme.

**Comment by arpincheira** [comment]
Hola, efectivamente hay un problema con el servidor de la U, voy a contestar por esta misma issue a penas se solucione dicho problema

**Comment by arpincheira** [comment]
Arreglado
