### ISSUE TITLE
Tablas de igual nombre en distintas bases de datos

### ISSUE THREAD

**Issue by Gabowo** [IIC2413/Syllabus-2021-1#365]
Hola,
Teniamos la duda de como difernciar en plpgsql (Procesos almacendados) entre dos tablas de distintas bases de datos e igual nombre, se hace de igual manera que en php?
Saludos

**Comment by arpincheira** [comment]
Hola, a que te refieres exactamente? Si te refieres a renombrarlas al interior del procedimiento efectivamente puedes hacerlo.

**Comment by Gabowo** [comment]
Perdon, al final mi duda se soluciono sola, pero es bueno saber que puedo renombrar igual

El tema es que inicialmente nos habiamos olvidado de que cada procedimiento almacenado se carga a la db que le corresponde, lamento el inconveniente :c
