### ISSUE TITLE
Guía 2 (2.8)

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2413/Syllabus-2021-1#37]
![image](https://user-images.githubusercontent.com/53887845/113214624-20c8c680-9250-11eb-9762-2e7451e13ad6.png)
Hola!
Si un capitán eligió en distintas fechas un barco del mismo color, es válido que su nombre me salga repetido?

**Comment by fjlopez7** [comment]
La idea es que los nombres no salgan repetidos. Debes ocupar algún estamento para eligir los nombres distintos.
