### ISSUE TITLE
Terminal para servidor 

### ISSUE THREAD

**Issue by sreitze** [IIC2413/Syllabus-2021-1#38]
Hola, quería saber si nos recomiendan entrar al servidor del curso a través de alguna terminal en específico como git bash (windows) o puede ser en cualquiera. Tengo Ubuntu, windows terminal, etc. Gracias!

**Comment by arpincheira** [comment]
Hola, lo importante es que la terminal que estés usando soporte ssh, según tengo entendido las terminales por defecto de linux(esto incluye la terminal de macos) como ubuntu no tendrían problema alguno. En el caso de windows deberían conectarse por powerShell que es una terminal que viene integrada desde windows 10 en adelante si no me equivoco

**Comment by sreitze** [comment]
Buenísimo, muchas gracias.
