### ISSUE TITLE
[Control3] Duda con total transado

### ISSUE THREAD

**Issue by tvallotton** [IIC2413/Syllabus-2021-1#387]
Para la 2.1.1.2 dice que tenemos que el volumen total transado cada dia. Para eso tenemos que hacer alguna conversión? O el volumen esta medidio en dolares?

En caso de que si se tenga que hacer una conversion, cual de todos los precios tenemos que usar, `open`, `close`, `high`, o `low`? Supongo que es el precio de cierre, porque los datos se toman a las 00:00 horas.

**Comment by ironcadiz** [comment]
No tienen que convertir nada.
Pueden usar el valor que viene en la tabla
