### ISSUE TITLE
Solución Guía 2

### ISSUE THREAD

**Issue by camirojasguajardo** [IIC2413/Syllabus-2021-1#39]
Hola! Una consulta, se subirá el solucionario de la guía 2 para poder chequear nuestras respuestas? :o 
De antemano, agradezco su respuesta y que tengan un buen finde!

Saludos, 
Camila Rojas.

**Comment by ValentinaAlvarezG** [comment]
Hola! esta vez no subiremos la solución pq igual la guía los va acompañando harto. Pero si tienes dudas sobre tus respuestas  puedes preguntar por las issues.
