### ISSUE TITLE
Duda Entrega Control 1

### ISSUE THREAD

**Issue by Cristofernandez** [IIC2413/Syllabus-2021-1#4]
Hola, despues de la sesion de ayuda por Discord me quede familiarizandome con el programa de Relax hasta el punto que avance un poco más de la mitad del control 1 alli. 
¿Mi duda es si puedo completar todas las consultas del control en Relax y subir el archivo descargado como solucion o debo pasarlo en limpio a otro programa para usar la notacion vista en clases de operadores?

**Comment by bpardobravo** [comment]
Hola, como dice el enunciado, la entrega debe ser en formato pdf. La descarga desde Relax queda en txt, por lo que como mínimo debes asegurarte de que al pasarlo a pdf se lea bien (los símbolos en particular).
En resumen, toma el camino que quieras para entregar un pdf con las consultas.

**Comment by Cristofernandez** [comment]
Perfecto, no hacia cachado que generaba un .txt, muchas gracias
