### ISSUE TITLE
Error guía 2

### ISSUE THREAD

**Issue by sreitze** [IIC2413/Syllabus-2021-1#40]
Hola, tengo este error al insertar las tuplas en la tabla Capitanes. Quiero agregar varias en un mismo comando. Que tendría que cambiar? Gracias
![image](https://user-images.githubusercontent.com/69603335/113319484-d85ce780-92e7-11eb-9843-5ea77a8e0e8b.png)

**Comment by nbarriav** [comment]
Hola!, debes eliminar el comentario "#LLenar tabla Capitanes" y debería funcionarte

**Comment by sreitze** [comment]
Al parecer no influye, pero lo que quiero es poder agregar mas de una fila a la vez, ahí es donde me tira error también.

**Comment by nbarriav** [comment]
El principal problema que existía cuando tiraba ese error era por los  comentarios puestos al principio (los cuales deben ser eliminados). Además de eso, no olvides finalizar con ";" despues de cada bloque de comando.
Te tira otro error aparte del que pusiste arriba?

**Comment by sreitze** [comment]
Ahí lo arregle, gracias.
