### ISSUE TITLE
Error al intentar conectar a BDD locales vía PHP

### ISSUE THREAD

**Issue by tcouso** [IIC2413/Syllabus-2021-1#411]
Hola! Estoy intentando conectar a dos copias locales de las BDD para hacer la migración de admins a usuarios, pero estoy teniendo un error que no he logrado entender pese a investigarlo: 
```PDOException: could not find driver in /home/tcouso/bd/IIC2413/db/migrations/admin_migration.php:11```
¿Saben qué podría estar fallando aquí? 
Gracias de antemano, y saludos!

**Comment by tcouso** [comment]
Me ayudó un compalero y lo resolví, saludos!

**Comment by DanoUC** [comment]
como lo arreglaste? me sale lo mismo :C

**Comment by tcouso** [comment]
Es este driver: ```php7.4-pgsql``` que me faltaba instalar.
En ubuntu el comando es ```sudo apt-get install php7.4-pgsql```.
