### ISSUE TITLE
Enunciado Grupos Par

### ISSUE THREAD

**Issue by felipe-stuardo** [IIC2413/Syllabus-2021-1#42]
A que se en la sección de Despachos con la dirección de destino, es solo la comuna? o una dirección específica?
Muchas gracias!

**Comment by arpincheira** [comment]
Hola, se refiere a una dirección específica. A modo de pista te puedo recomendar que recuerdes que las direcciones están asociadas a las comunas.

**Comment by felipe-stuardo** [comment]
Muchas graciaas!
