### ISSUE TITLE
Carpeta de entrega

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2413/Syllabus-2021-1#43]
Hola, cuando dicen que se deben entregar los PDF en la carpeta **grupoxx/Entregax** La carpeta grupo es la que nos encontramos apena entramos en el servidor o debemos crear una carpeta llamada **grupoxx**

**Comment by arpincheira** [comment]
Hola, solo deben crear una carpeta Entrega1. La idea es que apenas entren al servidor y utilicen el comando ```ls``` vean lo siguiente:
```sh
Sites Entrega1
```

**Comment by Lord-Kelsier** [comment]
Gracias
