### ISSUE TITLE
Cargar Datos desde .csv en codd.ing.puc.cl

### ISSUE THREAD

**Issue by Francisco5674** [IIC2413/Syllabus-2021-1#44]
Hola Mundo!

Tengo una duda, ya he creado suficientes datos a mano para las tablas y poder hacer las consultas, pero ya con los csv dentro del servidor del dcc este no me deja ver el directorio para poder poner correctamente el path y así leer los datos para llenar las tablas, alguna solución? 

Tengo todo el esquema listo, solo falta que las tablas se llenen automáticamente con mis csv, me tarde unas dos horas en hacerlos así que espero que la solución que me den no sea ingresar cada fila del csv a mano por medio de INSERT INTO, pq eso me tomará horas de mi vida de forma muy innecesaria.

**Comment by cmp831** [comment]
Hola, no está muy clara en tu descripción, pero espero que ya seguiste el paso de subir los archivos al servidor de la [pagina ](https://github.com/IIC2413/Syllabus-2021-1/wiki/Tutorial-Servidor-y-Base-de-Datos-Postgresql#subir-archivos-al-servidor)de wiki. Si fuese así, podrás ejecutar el comando `ls` en la terminal para listar los archivos y directorios dentro de tu ruta actual. O podrás usar el comando `pwd` para obtener la ruta absoluta en donde encuentras ahora. Otro comando útil sería el `cd NOMBRE_DEL_DIRECTORIO`, la cual cambiará el directorio en que estés trabajando en la consola. 

Con estos comandos podrás navegar y obtener las rutas de los archivos, recomiendo ver este [tutorial ](https://www.digitalocean.com/community/tutorials/how-to-use-cd-pwd-and-ls-to-explore-the-file-system-on-a-linux-server)para familiarizarse con dichos comandos. 

También está instalado el programa `tree` en el servidor, corriendo ese comando, mostrará la estructura de los archivos de una manera más gráfica en la consola.

**Comment by arpincheira** [comment]
Complementando el comentario de @cmp831, puedes tambier ver la [ayudantía de la entrega 1](https://drive.google.com/file/d/1F3moKiABRVSUb54gTLsLNS_IcPWKrfe_/view?usp=sharing), desde el 48:50 hablan sobre como completar las tablas con el archivo csv que subieron.

Ojo que la organización de los archivos en ese caso al utilizar el comando ```ls``` es:
```sh
Sites Entrega1 data.csv
```
lo que quiere decir que todos los archivos se encuentran en el mismo nivel

**Comment by Francisco5674** [comment]
Ya esta listo!!!, muchas gracias a ambos por la ayuda, pude solucionarlo por fin
