### ISSUE TITLE
Primer git pull

### ISSUE THREAD

**Issue by fedezang** [IIC2413/Syllabus-2021-1#45]
Hola!
Tengo una duda respecto al primer git pull que realizo desde el servidor
la terminal pide lo siguiente:
Username for 'https://github.com':
Que debo poner en este caso?

**Comment by arpincheira** [comment]
Hola, lo que deberías poner en ese caso son tus credenciales de GitHub, eso te permitirá realmente conectar tu repositorio personal con aquel que se encuentra en el servidor.
