### ISSUE TITLE
Clave psql

### ISSUE THREAD

**Issue by PDominguezW** [IIC2413/Syllabus-2021-1#46]
¿Cual es la clave para ingresar a psql en el servidor? Intente con grupo(numero de mi grupo) pero no funciono.

**Comment by arpincheira** [comment]
Hola, estás seguro de que ingresaste bien la contraseña? acabo de probar utilizando la cuenta de su grupo y funciona correctamente con la clave por defecto(grupoXX con XX= número de grupo)

**Comment by PDominguezW** [comment]
Mala mia, ya funciono. Gracias :)

**Comment by nicogrecod18** [comment]
Hola, soy del grupo 46 y tengo problemas para acceder a psql, intenté utilizando la clave predeterminada (grupo46) , así como la nueva de nosotros para acceder a nuestra cuenta del grupo
