### ISSUE TITLE
Duda con error en collab

### ISSUE THREAD

**Issue by Natydlb** [IIC2413/Syllabus-2021-1#47]
hola, tuve un problema al intentar agregar una tabla en google collab, me salió el siguiente error:

"ResourceClosedError: This result object does not return rows. It has been closed automatically"

![Captura de Pantalla 2021-04-03 a la(s) 17 04 26](https://user-images.githubusercontent.com/62019255/113490160-c4a7b180-949e-11eb-8e9c-27ca7800e887.png)

no se cómo solucionar ese error, cualquier ayuda se las agradecería, muchas gracias!

**Comment by arpincheira** [comment]
Ese problema creo que tiene relación con la versión de sqlacademy que estás utilizando, recuerda descomentar (quitar el #) de las líneas de código ubicadas en la parte superior del archivo correspondientes al método que estás ocupando para correrlo(en tu caso googlecolab), en este caso tendrías que descomentar esto(segunda celda de código):
![image](https://user-images.githubusercontent.com/37157550/113492841-fcb7f000-94b0-11eb-80aa-8259b9671f6e.png)
