### ISSUE TITLE
Vehículos grupos par

### ISSUE THREAD

**Issue by Lewisboi** [IIC2413/Syllabus-2021-1#48]
Se puede asumir que cada vehículo está asociado a solo una unidad?

**Comment by arpincheira** [comment]
Hola, efectivamente puedes decir que un vehículo está asociado a una unidad, de todas formas te recomiendo escribir los supuestos de tu modelo en el documento para que quede más claro a los ayudantes en que estabas pensando al realizar tu modelo (y así te podemos dar un mejor feedback para la próxima entrega)
