### ISSUE TITLE
Fecha grupos par

### ISSUE THREAD

**Issue by mleon17** [IIC2413/Syllabus-2021-1#49]
Hola, queria saber si la fecha de los despachos es en el formado "dia-mes-año" o solo año. Ya que en la pregunta 3 me preguntar por el año 2021. Gracias

**Comment by arpincheira** [comment]
Hola, la fecha va a ser del tipo "día-mes-año", si quieres más información puedes buscar [aquí](https://www.w3schools.com/sql/sql_dates.asp) por más información sobre los tipos de datos del tipo fecha que puedes encontrar en sql

**Comment by mleon17** [comment]
Es que preguntan solo por el año en la 3, entonces en el álgebra relaciónala se complica. Hay alguna manera de hacerlo?

**Comment by arpincheira** [comment]
No te puedo decir la manera exacta con la que puedes hacerlo, pero puedes pensar que en álgebra relacional se puede definir un "rango" de restricción, espero que eso ayude un poco a tu problema.
