### ISSUE TITLE
Duda diferencia guía 1

### ISSUE THREAD

**Issue by drosselot** [IIC2413/Syllabus-2021-1#5]
Hola, en la última consulta de la guía 1 se hace una sustracción de esta forma:
![image](https://user-images.githubusercontent.com/61997707/112406894-d4333780-8cf3-11eb-9d49-67d595eae030.png)

Mi duda es que en clases no nos mostraron que los atributos quedaban en formato "relacion.atributo", entonces cual debemos usar?

**Comment by benjavicente** [comment]
Esa forma de atributos la vimos cuando se usa el producto cruz ([52:25](https://drive.google.com/file/d/19VyDiwOOH6vR3OlQSgwVy0sMIRw-tLX0/view)).
Yo tengo una duda muy similar: porque se usa `Tours.nombre` y no `nombre`?
`ToursNoMasCaro` pareciera tener los atributos `T1.tid`, `T1.nombre`, `T1.duracion` y  `T1.precio` mientras que `Tours` los atributos `tid`, `nombre`, `duración` y `precio`. No entiendo que pasa con los atributos en esa resta que queda un _`T1`_ al principio.

**Comment by bpardobravo** [comment]
@drosselot como ambas tablas tienen los mismos nombres de columnas, en verdad no es necesario poner πTours.nombre, con πnombre basta (como puedes ver en el ejemplo de las slides, o en 1:23:41 en la clase).

@benjavicente como puse arriba, con nombre hubiese funcionado igual, lo importante al restar es que la cantidad de columnas de ambas tablas sean las mismas, y que los datos de cada columna con su par sean del mismo tipo. Luego puedes usar πTours.nombre o bien πnombre, dado que "nombre" es el título de la columna de la tabla a la cual le estás restando tuplas.

Puedes probar en Relax hacer **π Vinas.nombre (Vinas - Vinas2)** y **π nombre (Vinas - Vinas2)** con los datos de la guía (haciendo una segunda tabla de viñas con algunas filas repetidas y otras no) y verás que dan lo mismo.
