### ISSUE TITLE
Duda Algebra Relacional

### ISSUE THREAD

**Issue by DanoUC** [IIC2413/Syllabus-2021-1#50]
Hola, el profesor mostró en clases que en SQL era posible filtrar mediante el comando LIKE datos  que  contengan en algún lugar X string dando como ejemplo LIKE '%spiderman%'.
Mi pregunta es si existe algo en al algebra relacional que cumpla esta misma función.

**Comment by arpincheira** [comment]
Hola, en álgebra relacional no existe nada parecido a la función LIKE de sql, de todas formas podría existir una forma de hacer esto con álgebra relacional con los operadores que vieron en clases aunque, de existir, debe ser muy complicado de aplicar(o eso creo), por lo que te recomendaría buscar otra forma de hacer aquello que quieres.
