### ISSUE TITLE
Enunciado grupos pares - Duda dirección origen 

### ISSUE THREAD

**Issue by Natydlb** [IIC2413/Syllabus-2021-1#51]
Hola! Quisiera saber si se puede asumir que en despachos la dirección de origen es la misma que la dirección de la unidad?  En otras palabras podemos asumir que los despachos comienzan/salen desde una unidad? 

Y también otra pregunta, la dirección de origen, destino y la de unidad contienen la comuna?

**Comment by arpincheira** [comment]
Hola, no, la dirección de origen debería ser la dirección de la tienda, aunque en esta entrega no se debe preocupar tanto de eso, de todas formas te recomiendo poner tus supuestos en el documento para poder entregarte un feedback más detallado y que no tengas problemas en la entrega 2.

Con respecto a las direcciones, todas están relacionadas con una comuna(esto es un "hint").

**Comment by chineseJack564** [comment]
Hola,
Al decir que los direcciones son solo los nombres de comunas? Por ejemplo, "Providencia"?
O quiere decir que es un direccion especifico relacionado con comuna? Por ejemplo, "Tobalaba 1900", "Providencia"?

**Comment by arpincheira** [comment]
Hola, es lo segundo que dices
