### ISSUE TITLE
Enunciado grupos pares: Duda con categorías de vehículos

### ISSUE THREAD

**Issue by allisonaguilar** [IIC2413/Syllabus-2021-1#52]
Hola! Tengo una duda, es posible asumir que por ejemplo un vehículo de carga tiene alcance 0 y compartimientos 0? Es decir, si es posible asumir que un vehículo tiene 0 de las características que no son propias de él?.

Espero que se entienda, Gracias!

**Comment by arpincheira** [comment]
Hola, em.... no, deberían tener un valor aunque sea muy pequeño, aquellos vehículos que no posean dicho valor simplemente van a tener un NaN o "" como valor. De todas formas puedes poner aquello que dices como supuesto, aunque pronto van a ver en clases como se debería modelar la base de datos para que aquellos casos no ocurran. 

Espero haber contestado tu duda.
