### ISSUE TITLE
Instalación de PostgreSQL en MacOs: clave superusuario

### ISSUE THREAD

**Issue by pedroriosg** [IIC2413/Syllabus-2021-1#53]
Hola! Descargué PostgreSQL en mi computador, todo funcionó bien. Sin embargo en ningún minuto se me pidió crear una contraseña para mi superusuario de PostgreSQL, no sé como hacerlo y si es requisito. Feliz si alguien me puede ayudar con eso.

Saludos y muchas gracias

**Comment by arpincheira** [comment]
Hola, no es necesario ponerle contraseña a tu super usuario, pero en el caso de que quieras hacerlo lo que debes hacer es ingresar a postgress con dicho superusuario y poner ```\password```, una vez hecho esto te va a pedir tu contraseña y luego confirmarla. Luego de esto ya estarías listo
