### ISSUE TITLE
Enunciado Grupo Par

### ISSUE THREAD

**Issue by felipe-stuardo** [IIC2413/Syllabus-2021-1#54]
Holaa! En item de Personal nos dice que se debe especificar el tipo de licencia que tiene el repartidor, ¿se puede asumir que solo tiene un tipo de licencia? O puede tener más de una? Muchas gracias por la ayuda!

**Comment by arpincheira** [comment]
Hola, efectivamente puedes asumir que tiene solo un tipo de licencia
