### ISSUE TITLE
Fechas RelaX

### ISSUE THREAD

**Issue by mleon17** [IIC2413/Syllabus-2021-1#55]
Hoa, cuando anoto fechas del tipo "año-mes-dia" en relax me los arroja como storing y no como "date". Como es el formato para fecha? Gracias

**Comment by arpincheira** [comment]
Hola, recuerda que relax es una herramienta complementaria y no representa los tipos de datos reales con los que trabajaremos a lo largo del proyecto. En este caso te recomiendo ver la issue #49 en donde se habla del como trabajar con las fechas en álgebra relacional y en postgreSQL
