### ISSUE TITLE
Preguntas sobre el servidor

### ISSUE THREAD

**Issue by pedroriosg** [IIC2413/Syllabus-2021-1#56]
Hola! Tengo un par de preguntas sobre la conexión con el servidor:

- En la ayudantía dijeron que el día de la entrega, cuando esté todo listo se haga un pull al servidor. Mi pregunta es si se puede hacer pull no solo el día de la entrega sino cada vez que se haga un avance importante. El servidor guarda el último pull?
- Ignoré de forma incorrecta los archivos
   .bash_logout
  .bashrc
  .cache/
  .gitconfig
  .gitignore
  .profile
  .ssh/
  y se me copiaron en mi repositorio personal, hay alguna manera de eliminarlos para que no molesten?

Saludos y muchas gracias!

**Comment by miguel-mrtnez** [comment]
Hola. Respecto a lo primero, sí, de todas maneras, así vas asegurando tu trabajo poco a poco; en el fondo lo que les quisimos transmitir era que es importante que la totalidad de su trabajo quede guardado en el servidor antes de la hora de entrega, y sí, la versión del último pull registrado será la que veremos nosotros, como en cualquier repositorio de GitHub. 

Respecto a lo segundo, si estás utilizando un archivo `.gitignore` para ignorar archivos, no debes agregarlo al mismo `.gitignore` (archivo número 5). Una vez solucionado lo anterior, puedes sacar los archivos a ignorar de tu repositorio local, luego commitear y pushear este cambio, y finalmente volver a moverlos donde estaban.

Mucho éxito, si el problema con los archivos era otro, por favor háznoslo saber.

**Comment by cmp831** [comment]
Complementando la respuesta de Miguel, para eliminar los archivos que fueron ingresados al repo, manteniendo el archivo en local, puedes probar la solución propuesta es este [link](https://stackoverflow.com/a/1139797)

**Comment by Gustav2000** [comment]
Respecto a esto mismo, dónde hay que crear el .gitignore? En el servidor mismo que está funcionando como un repositorio local?

**Comment by miguel-mrtnez** [comment]
Depende mucho de qué estés haciendo y de la dinámica de trabajo de tu grupo @Gustav2000. Si estás trabajando en tu repositorio local, y agregas cambios al repositorio remoto sobre los que tendrá que trabajar tu compañero, y que será pulleado también por el repositorio local del servidor, te convendría tener un `.gitignore` para, por ejemplo, archivos autogenerados por tu editor de texto. Si haces cambios directamente en el repositorio del server, pero a tu grupo no le interesa pullearlos en sus computadores, convendría otro `.gitignore` en el servidor.

El `.gitignore` no es un requerimiento en ningún caso, pero sí una muy buena práctica. ¡Cuidado con agregar al `.gitignore` archivos que sí tienen que subir!

**Comment by Gustav2000** [comment]
Muchas gracias

**Comment by nicolaszanni** [comment]
Hola, tengo una duda con hacer el git push desde el servidor. En la ayudantía mostraron que tenían una clave para el repositorio, la cual era necesaria para hacer el git push.
Cual sería esa?
Muchas gracias

**Comment by miguel-mrtnez** [comment]
Debería pedirte el nombre de usuario y contraseña de tu **cuenta de GitHub**.
