### ISSUE TITLE
Enunciado Grupos Pares: formato direccion

### ISSUE THREAD

**Issue by pedroriosg** [IIC2413/Syllabus-2021-1#58]
Hola, quería saber si hay algún formato establecido para la dirección de las unidades. Por ejemplo si es solo el nombre y número de la calle o además viene con la comuna. Pregunto por si se puede hacer una columna extra en la tabla de unidades que indique la comuna.

Muchas gracias

**Comment by miguel-mrtnez** [comment]
Hola, el enunciado indica que las unidades tienen "*identificador, la dirección de la unidad, y distintas comunas*". Notar que dirección y comunas aparecen separadas. No se indica un formato específico para la dirección, puedes asumir el que gustes, mientras sea consistente con el enunciado, con la estructura de tu esquema, y anotes todos tus supuestos en el documento de entrega.

**Comment by kalarconvl** [comment]
Hola! Quería saber si la dirección de origen y de destino de un despacho tiene que ser la dirección de una unidad como para ue el despacho sea de una unidad a otra? O pueden ser direcciones como por ejemplo: unidad 1 está en la comuna de san joaquin y esta unidad satisface a macul y providencia. Entonces un despacho puede ser desde macul a Providencia?

**Comment by miguel-mrtnez** [comment]
Si no se especifica en el enunciado, modelen como a ustedes les parezca, respetando la estructura de su esquema, e indicando estos supuestos en el documento de entrega.
