### ISSUE TITLE
Duda Enunciado Grupos Impares

### ISSUE THREAD

**Issue by camirojasguajardo** [IIC2413/Syllabus-2021-1#62]
Hola! En mi grupo tenemos algunas dudas con respecto a la primera entrega: 
1) ¿Se puede pedir más información de la que se indica en el enunciado? En específico, me refiero a agregar atributos que requieran de información que no está en los atributos que se plantean en el enunciado. 
2) En el atributo 'nombre' de la tabla 'Tiendas', ¿es posible asumir que los nombres serán únicos? o más bien indicarán algo más general como una marca por ejemplo. 

De antemanos, agradecemos su respuesta :)
Saludos!

**Comment by arpincheira** [comment]
Hola,
con respecto a la primera pregunta, podrían añadir atributos adicionales siempre y cuando crean y expliquen el motivo por el cual ustedes creen que pueden ayudar en la moderación del problema o en la forma en la que pueden contestar las preguntas solicitadas en el enunciado. De todas formas te aviso que para la entrega2 contarán con el feedback de su modelo de la entrega 1 y con diversos archivos con información que les podrían ser útiles al momento de replantear su esquema.

Con respecto a lo segundo, nuevamente puedes realizar los supuestos que estimes convenientes para poder contestar lo solicitado(ojo que debes justificarlos), de todas formas yo recomendaría más asignar un identificador único a las tiendas pues así aseguran que, aunque se repitan los nombres de estas(considerando el caso de franquicias y eso), saben que el id tanto sería para x tienda y no dependerían tanto del nombre.
