### ISSUE TITLE
base de datos servidor

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2413/Syllabus-2021-1#63]
Hola,
el servidor usa postgresql?
sino cual?
este ya viene instalado?

**Comment by arpincheira** [comment]
Hola, efectivamente utilizamos PostgreSQL, más específicamente la versión  10.16.  y si, este ya viene instalado en el servidor, para poder acceder a la base de datos de su grupo deben ingresar:
```
psql
```
y la contraseña debería ser ```grupoXX``` siendo XX su número de grupo

**Comment by Aloncarrasco** [comment]
1 millón de gracias
