### ISSUE TITLE
Creación de .gitignore en el repositorio local del servidor

### ISSUE THREAD

**Issue by Gustav2000** [IIC2413/Syllabus-2021-1#64]
Hola, tenía una pregunta sobre como crear el archivo .gitignore desde el repositorio local del servidor. Hay que hacerlo por la terminal en este caso?

Pd: ya hice el _git init_ desde el servidor para convertirlo en repositorio local, y lo enlacé con el repositorio remoto de GitHub.

**Comment by cmp831** [comment]
Hola, el archivo .gitignore es como cualquier otro archivo, lo puedes crear en la consola usando `touch .gitignore` en linux, o `ni .gitignore` en PowerShell. O tambien lo puedes crear dentro de tu editor de texto como un nuevo archivo.

**Comment by Gustav2000** [comment]
Ya perfecto. Pero hay algo que aún no me queda muy claro, porque al final la lógica es que yo solo uso el repositorio local del servidor para hacer pull antes de las entregas importantes. Pero aquí en este repositorio hay unos cuantos archivos que no me interesan y que se recomendaban colocar en un .gitignore y no entiendo como hacer esto desde el repositorio del servidor.

![image](https://user-images.githubusercontent.com/62355739/113734069-04ea7800-96c9-11eb-950e-c1c862dbbc98.png)
A este paso me refiero.

**Comment by cmp831** [comment]
Ahh perfecto, sorry entendi mal tu pregunta, la idea de los archivos gitignore es un archivo para omitir algunos archivos que no quieres que se suban al repositorio origen. Estos pueden contener archivos de configuracion de tu IDE, configuraciones de la consola etc. Entonces este archivo lo puedes crear en el ambiente de desarrollo en tu computador para no subir los archivos extras al origen, y por extension, que no sean descargadas en el servidor durante el pull. 

Entonces, como el ejemplo del wiki incluyo el `.gitignore` en el mismo `.gitignore`, tendran que crear un `.gitignore` en cada repositorio local si es que lo necesitan. Para el caso del repositorio local en el servidor, es menos importante tener uno, dado que va a ser menos probable que tengan que hacer push desde ahi. 
Si quieres crear y editar el  `.gitignore` dentro del servidor, puedes usar un editor de texto dentro de la consola cuando se conectan via SSH, por ej. `nano .gitignore` u otros. 

Tambien lo que usualmente se hace es hacer commit al mismo archivo  `.gitignore`, de esta manera tendras el  `.gitignore` en todos los repositorios locales cuando haces un Pull.

**Comment by Gustav2000** [comment]
Perfecto, muchas gracias.
