### ISSUE TITLE
Duda Tablas 

### ISSUE THREAD

**Issue by nicolaszanni** [IIC2413/Syllabus-2021-1#65]
Hola, quería preguntar si al crear una tabla con varios atributos que dependen de otros, es mejor crear una tabla grande y en ciertos casos poner valores por defecto como NULL o es mejor separar en más tablas?
Saludos

**Comment by arpincheira** [comment]
Hola, esa es una muy buena pregunta. Tal como verán próximamente en clases, lo ideal siempre va a ser tratar de "atomizar"  el problema, subdividiendo en este caso los datos en distintas tablas que posean cierto tipo de información para poder evitar entonces poseer valores nulos al interior de la base de datos.
