### ISSUE TITLE
Problema creando repositorio en servidor

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2413/Syllabus-2021-1#66]
Hola, viendo el tutorial de servidor + GitHub, cometi el error de no crear el repositorio como master (que era lo recomendado por el ayudante). Entonces me di cuenta e hice otro repositorio, pero cuando trate de iniciarlo nuevamente me tira este error:

![Captura de Pantalla 2021-04-05 a la(s) 7 57 10 p  m](https://user-images.githubusercontent.com/62023649/113640441-6a971f80-9649-11eb-9591-0c04b149573f.png)

El repositorio de antes ya lo borre de mi GitHub, solo tengo el nuevo.

**Comment by arpincheira** [comment]
Hola, en ese caso te recomiendo utilizar el comando 
```
rm -r -f .git
```

este comando debería remover aquellos datos que evitan que puedas definir un nuevo origen dentro de su usuario del servidor

**Comment by pabloalvarez67** [comment]
> Hola, en ese caso te recomiendo utilizar el comando
> 
> ```
> rm -r -f .git
> ```
> 
> este comando debería remover aquellos datos que evitan que puedas definir un nuevo origen dentro de su usuario del servidor

Me sirvió! muchas gracias.
Eso sí, tengo otro problema ahora:

![Captura de Pantalla 2021-04-05 a la(s) 9 11 57 p  m](https://user-images.githubusercontent.com/62023649/113644827-9f0fd900-9653-11eb-9aaf-1ef1bcb18e54.png)

que debo hacer exactamente en este caso?

**Comment by arpincheira** [comment]
Puedes seguir lo que te están indicando, decirle tu identidad a GitHub utilizando los comandos de git config --global que te aparecen en consola. En el caso de que no quieras hacerlo [aquí](https://stackoverflow.com/questions/11656761/git-please-tell-me-who-you-are-error) hay un link a un foro en donde discuten distintas soluciones a lo que aparece en ese mensaje
