### ISSUE TITLE
Duda entidad Despachos: ¿identificador e id de compra son lo mismo?

### ISSUE THREAD

**Issue by AAVP** [IIC2413/Syllabus-2021-1#67]
Buenas!

En el enunciado de la Entrega 1 se menciona que (aquí cito textual): "Cada despacho guarda un **identificador** y una fecha, y está asociado a una dirección de origen, y una dirección del destino. Adicionalmente, el despacho está asociado a un **id de compra**, y está realizado por un vehículo".

Nuestra pregunta es si esos dos atributos que están en negrita son el mismo atributo o tenemos que reservar ese id para una futura unión de bases de datos de los grupos pares e impares? Si la segunda opción es la correcta entonces qué valores podemos ingresar?

**Comment by miguel-mrtnez** [comment]
Hola, corresponden a atributos **distintos**. Para esta entrega, todas las tuplas que ingresen a sus tablas serán para probar consultas, no se preocupen por migraciones todavía. En cuanto al tipo de dato, queda a tu criterio, trata de que sea consistente y recuerda anotar todos tus supuestos en el documento de entrega.
