### ISSUE TITLE
Duda Enunciado Par sobre vehiculo y unidad

### ISSUE THREAD

**Issue by chineseJack564** [IIC2413/Syllabus-2021-1#68]
Hola,
Tenemos una duda si cada vehiculo solo pertenece a una unidad? O puede pertenecer a mas de una unidad? En el enunciado solo dice que cada unidad tiene una flota de vehiculos para realizar los despachos, eso esta diciendo que una unidad tiene una lista de vehiculos definidos pero no dice nada sobre la realcion reversa.
Saludos!

**Comment by arpincheira** [comment]
Hola, yo recomendaría tomar aquello que dijiste al principio como correcto, pues cada unidad mantiene finalmente dichos vehículos. De todas formas te recomiendo añadir un apartado en donde expliques un poco el o los supuestos que tomaste en consideración para poder realizar el esquema de una forma y no de otra, especialmente para aquellas cosas que pueden quedar poco claras del enunciado
