### ISSUE TITLE
Primary Key 

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2413/Syllabus-2021-1#69]
Hola tengo una duda si todas las tablas deben tener por obligación un primary key o es solo una buena práctica? 
Si todas las tablas deben tener un primary key, cuando es necesario o conveniente tener dos o más primare key. 
Por ejemplo en el control, es lógico que los usuarios y montañas tengan un primary key que es el id. Sin embargo, la relacion de subió tiene 3 primary keys, pero porque fue mejor tener 3 primary key y no solo un primary key que fuera subio_id.

**Comment by arpincheira** [comment]
Hola, el añadir una primary key en todas las tablas es una buena práctica y muy recomendada. Además, pueden existir casos en los que sea necesario tener más de una primary key y más adelante verán en clases la existencia de las foreing keys, las cuales les pueden ayudar mucho al momento de modelar. 

De todas formas, en lo que respecta a esta entrega, lo ideal es que añadas primary keys en tus tablas y, en el caso de no añadirlas, justificar el motivo por el cual crees que es correcto esto. 

Espero haberte ayudado
