### ISSUE TITLE
Control 1 pregunta 5

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2413/Syllabus-2021-1#7]
Hola! Cuando hablan de buscar a las personas que hayan subido un Munro, ¿se refiere a que subió una única vez un Munro o que ha subido al menos una vez un Munro? Saludos!

**Comment by bpardobravo** [comment]
Por lo menos un Munro. Por lo general si no dice "exactamente uno" o "solamente uno", nos referimos a por lo menos uno.
