### ISSUE TITLE
Proyecciones de tablas con join sin atributos especificados

### ISSUE THREAD

**Issue by flobianchi** [IIC2413/Syllabus-2021-1#70]
Hola! Si para un requisito de una consulta consulta hago un join de dos tablas y no me especifica que atributo proyectar, deberia proyectar toda la fila de esta union igual? (el enunciado dice "si no se especifica que atributo proyectar entregar la entidad entera") o solo proyectar los atributos que corresponden a la tabla relacionada a lo consulta? (ejemplo me pide los vehiculos que cumplen ciertas caracteristicas y hago el cruce con otra tabla para verificar las caracteristicas, luego deberia proyectar las filas completas incluidos los atributos de esa tabla nueva o solo la correspondiente a vehiculos?)

**Comment by arpincheira** [comment]
Hola, idealmente intenta mostrar solamente los datos solicitados, en el caso de los vehículos efectivamente recomendaría proyectar solo los datos correspondientes a dicha entidad o datos que consideres de importancia al momento de responder dicha consulta.

De todas formas, en el caso de que quieras mostrar los datos de ambas tablas te recomiendo justificar el motivo por el cual crees que es ideal mostrar todos los datos y no solo aquello solicitado.
