### ISSUE TITLE
Problemas con PostgreSQL

### ISSUE THREAD

**Issue by Flvilches** [IIC2413/Syllabus-2021-1#71]
Hola!
Estoy intentando probar PostgreSQL con los comandos que fueron entregados en el Wiki, pero cada vez que intento hacer 
_createdb exampleDB_
Me pide una contraseña, pero no se si esa se refiere a la contraseña que debía ser ingresada al momento de la instalación o si es otra contraseña. 
Gracias de antemano.

**Comment by arpincheira** [comment]
Hola, dentro del servidor ustedes no poseen los permisos para poder crear una base de datos. Con lo que ustedes cuentan es con un usuario llamado grupoXX que tiene acceso a la base de datos grupoXX y en la cual ustedes pueden crear distintas tablas.

En el caso de que quieras probar más cosas de PostgreSQL te recomiendo fuertemente descargarlo en tu computador y probar de manera local los diversos comandos.
