### ISSUE TITLE
Delay Servidor?

### ISSUE THREAD

**Issue by Huasito-Appel** [IIC2413/Syllabus-2021-1#73]
Hola, estabamos dejando seteado el servidor para el proyecto y nos surgio una duda, es posible que el server tenga delay entre 2 usuarios?
lo que nos paso en concreto es que ambos tenemos abierta una terminal con el sv, yo agrege el .gitignore a travez de github, es decir lo pushee a nuestro repo y le hice un pull desde la consola del sv, que ya esta seteada con nuestro repo. Mientras que el genero el gitignore a travez del bash del sv unos minutos antes de que yo, el podia ver los cambios de manera local en su consola del sv pero a mi no me salian.

**Comment by JosefaPaz** [comment]
Hola!

Puede haberse debido a que muchos hubieran estado conectados al servidor, por lo que la subida de archivos andaba un poco lenta y por eso los cambios se vieron reflejados después. Normalmente, quizá si lo intentan en un horario con menor flujo, deberían ver los cambios casi al mismo tiempo.

Éxito! :)
