### ISSUE TITLE
Problema al clonar repositorio-Operation not permitted fatal: could not set 'core.filemode' to 'false'

### ISSUE THREAD

**Issue by Emiliax16** [IIC2413/Syllabus-2021-1#74]
Hola! ya está creado mi repo y seguí todos los pasos del video, pero cuando intenté clonar el repositorio en mi computador, me sale este error. 
![error_bd](https://user-images.githubusercontent.com/69869381/113920339-a4376a00-97b2-11eb-9dff-49a155b9dd50.png)

**Comment by cmp831** [comment]
Hola, lo más probable es que estás tratando de clonar el repositorio usando WSL dentro de la carpeta users de Windows. Te recomiendo cambiar de directorio para clonar el repo, por ejemplo usando el comando `cd ~` te llevará a la carpeta "home" del usuario de Linux. 

Otra manera de hacerlo sería simplemente usar el git de Windows para clonar el repo dentro de la carpeta de usuarios.

**Comment by Emiliax16** [comment]
Gracias!! me funcionó usando el git de Windows c:
