### ISSUE TITLE
Duda enunciado: Relacion personal administrativo-unidades

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2413/Syllabus-2021-1#75]
Hola, nos surgió la dudad si el enunciado dice que una unidad puede tener **varios personales administrativos pero un solo jefe** o **solo un personal administrativo que es el jefe**

**Comment by DomagojVrgoc** [comment]
Es la primera opción. E.g. una unidad puede tener 50 personas trabajando allá cómo el personal administrativo, y un jefe de la unidad. No pueden tener 2 jefes.

**Comment by Lord-Kelsier** [comment]
Muchas gracias
