### ISSUE TITLE
Como saber que repartidor llevo que pedido?

### ISSUE THREAD

**Issue by flobianchi** [IIC2413/Syllabus-2021-1#76]
Hola! queria saber como puedo saber que repartidor llevo que pedido. Esto lo pregunto porque los pedidos estan asociados a un vehiculo particular, pero en el enunciado dice que un vehiculo puede estar asociado a mas de un repartidor. Puedo agregar deliveradamente una columna a pedidos que indique el repartidor?

**Comment by arpincheira** [comment]
`Hola, efectivamente pueden añadir dicha columna a pedidos.
