### ISSUE TITLE
Tablas por categoria de vehiculos

### ISSUE THREAD

**Issue by flobianchi** [IIC2413/Syllabus-2021-1#77]
Hola! En un principio creamos nuestra tabla de vehiculos con todos los datos  y todos los vehiculos, pero luego de la clase nos dimos cuenta de que era mejor evitar los null. En vista de esto, queriamos saber como es mas conveniente para separar la tabla de vehiculos (pensando mas a futuro) si es mejor tener una tabla con todos los vehiculos y sus atributos hasta categoria y luego una tabla para caracteristicas_frescos, caracterisiticas_carga y asi? o si es mejor dividir la tabla original de vehiculos derechamente en 3 y tener como tabla vehiculos_carga, vehiculos_frescos y vehiculos_cfria con todos sus respectivos datos juntos en una misma tabla.

**Comment by arpincheira** [comment]
Hola, dentro de todo pueden pensar en investigar lo que viene siendo herencia, si bien esto se verá hipotéticamente la próxima clase, les permitirá modelar mejor aquello que quieren hacer. De todas formas (y a modo de pista), aquello que están haciendo de tener 3 tablas para cada tipo de vehículos y los datos comunes en la misma tabla es un muy buen acercamiento para lo que vendría siendo la modelación ideal ante este problema.
