### ISSUE TITLE
Duda item 1.2.1

### ISSUE THREAD

**Issue by LukasGuthrie** [IIC2413/Syllabus-2021-1#79]
Hola! No entendí bien lo que pide la consulta, pide entregar una tabla que tenga una columna nombre, donde cada nombre de tienda debe ser único,  y varias columnas comuna o pide entregar una tabla con una columna nombre, donde los nombres de tiendas se pueden repetir, y una sola columna comuna. Pido disculpas anticipadas por lo enredado de mi pregunta pero hice lo mejor posible para explayarme xd.

**Comment by fjlopez7** [comment]
Es la segunda opción. en una tabla mostrar la columna nombre de la tienda, a pesar de que estén repetidos, y en otra el nombre de la comuna.

**Comment by LukasGuthrie** [comment]
Gracias crack
