### ISSUE TITLE
Actividad 1, pregunta 5

### ISSUE THREAD

**Issue by Gustav2000** [IIC2413/Syllabus-2021-1#8]
Hola, en la pregunta 5 de la actividad 1 (guía 1) nos piden encontrar los tours que no visitan ninguna viña de la quinta región, y para esto usan una **diferencia**. Mi pregunta es si es que se puede hacer una _selección_ de todas las regiones diferentes a "v" (con un signo de desigualdad) y de esta forma no tener que usar una diferencia.

**Comment by ValentinaAlvarezG** [comment]
Hola! te voy a dar un ejemplo de por qué lo que propones no daría la respuesta correcta para que se entienda mejor.

Imagina que al hacer join de SeVisita con Viñas te quede algo así:

tid | vid | region 
----|----|---------
2    | 1   |  V
2    | 3   |  X

Que en este caso significaría que el Tour 2 visita la viña 1 que está en la V región y visita la viña 3 que está en la región X. Si a esa tabla le haces una selección de las regiones diferentes a V, te quedaría la segunda fila, ya que la región X != V. Entonces tu respuesta sería el tour 2. Pero el tour 2 no es una respuesta correcta ya que sí visita una viña en la V región. 

En cambio si primero seleccionas de aquí a los que sí visitan la V, te quedas con el tour 2, y luego de todos los tour lo restas, entonces el tour 2 ya no va a ser tu respuesta.

Espero se entienda.

Saludos!

**Comment by Gustav2000** [comment]
Perfectoo, muchas gracias, y con respecto a esa misma diferencia que se realiza en la pauta, creo que deberíamos restar 2 tablas que tengan la misma cantidad de atributos, porque en la tabla **ToursV** solo tengo nombres y en la tabla **Tours** tengo 4 atributos.
![image](https://user-images.githubusercontent.com/62355739/112484778-01660100-8d59-11eb-94ed-4acd2d89f753.png)

**Comment by ValentinaAlvarezG** [comment]
Sii! se nos debe haber pasado ahí en la pauta, pero es solo mover el pi a la resta o agregarle un pi a Tour antes de hacer la resta.

**Comment by Gustav2000** [comment]
Yaa, graciass!!!
