### ISSUE TITLE
Guía de ejercicios 3 (Consultas anidadas ej 11)

### ISSUE THREAD

**Issue by IgnaciaJ** [IIC2413/Syllabus-2021-1#80]
Hola! Tengo dudas con la consulta anidada 11 que piden encontrar todos los barcos que no fueron reservados por el capitán de peor rating este es el código de lo que tengo, pero me tira el siguiente error:(
<img width="743" alt="Captura de Pantalla 2021-04-07 a la(s) 18 41 51" src="https://user-images.githubusercontent.com/69643709/113943717-39e1f200-97d1-11eb-872e-d2615eb42f29.png">

gracias!!!

**Comment by Skablop** [comment]
Al decir ```...FROM (Reservas, Capitanes, Botes) AS joins...``` estás dandole el nombre joins al producto cruz entre esas tres tablas, por lo que individualmente dejan de existir y al pedir condiciones como ```WHERE Reservas.cid = Capitanes.cid``` tu programa ya no sabe qué hacer, porque solo tiene la tabla joins y no las tablas Reservas y Capitanes.

Además, cometes otro error cuando dices ```AND Botes.bid EXCEPT (SELECT....)``` porque no estás especificando ninguna condición sobre Botes.bid.

**Comment by IgnaciaJ** [comment]
Muchas gracias!!!!
