### ISSUE TITLE
Consulta 2.2.2 Enunciado Par

### ISSUE THREAD

**Issue by festelle** [IIC2413/Syllabus-2021-1#81]
Cuando se pide mostrar a "todos los vehículos", debemos entregar una tabla que muestre cada atributo de cada vehículo que cumplan las condiciones o podemos solo mostrar la patente de los vehículos?

**Comment by Skablop** [comment]
Si no se explicita qué atributo proyectar, debes mostrar la cantidad entera. En este caso, como dices tú, sería cada atributo de cada vehículo que cumpla lo pedido.
