### ISSUE TITLE
Dudas varias enunciado grupos impares

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2413/Syllabus-2021-1#82]
- ¿Pueden dos productos tener el mismo nombre? Por ejemplo, dos productos de nombre 'Carne' con distinta descripción.
- ¿Dos tiendas pueden vender el mismo producto a distinto precio?
- En la descripción de Compras del enunciado: "Cada compra es realizada por un único usuario, y permite comprar productos de **una tiendas**". ¿Lo destacado en negro se refiere a unas tiendas o una tienda? Pregunto por si una compra puede incluir productos de distintas tiendas. 
- En el enunciado se pide crear datos tal que cada consulta en SQL arroje al menos un resultado. ¿Eso para las tres primeras consultas o todas?

**Comment by arpincheira** [comment]
Hola,
-  efectivamente podría llegar a pasar eso, por lo que te recomiendo utilizar ids numéricos e irrepetibles en tus datos como primary keys
- Puedes suponer que eso no va a pasar, más que nada por simplicidad y que, en el caso de que pase, los productos tendrán un id diferente asignado(siendo considerados en la práctica como productos distintos)
- Cada compra corresponde a **una tienda**, ahora el usuario puede realizar múltiples compras a la misma o distintas tiendas(hay veces en las que ni el usuario se decide bien lo que quiere)
- La idea es que sea para todas, o que por lo menos agregues datos a todas las tablas y que las tablas de las consultas tengan datos que te permitan contestarlas.
