### ISSUE TITLE
Duda enunciado entrega 1 impar comunas asociadas a tiendas

### ISSUE THREAD

**Issue by francoschiaffino** [IIC2413/Syllabus-2021-1#83]
Hola!! No entendí si las tiendas pueden despachar a una cantidad limitada de comunas (lo que implicaría la existencia de un listado de comunas a las cuales se les puede despachar asociado a la tienda) o pueden despachar a cualquier comuna. Muchas gracias de antemano.

**Comment by arpincheira** [comment]
Hola, puedes asumir que una tienda idealmente va a despachar solo a las comunas que posee. Para la entrega dos, en donde nosotros les entregamos los datos a manejar, van a poder suponer que una tienda solo puede despachar a comunas a las que "históricamente" haya despachado. 

De todas formas recuerda que es ideal que añadas tus supuestos al informe, para que al ayudante corrector le queden claras tus decisiones de diseño
