### ISSUE TITLE
Formato esquema

### ISSUE THREAD

**Issue by nicogrecod18** [IIC2413/Syllabus-2021-1#84]
Hola, quería saber en que formato les entregamos los esquemas en el pdf. Por ejemplo, esto estaría correcto ?
Personal(RUT, NOMBRE, ....)
O también hay que escribir si cada dato es int, float, etc ?
Gracias de antemano !!

**Comment by arpincheira** [comment]
Hola, a modo de **hint** te presento un formato de esquema típico:

Barcos: <ins>barco_id</ins> int, nombre varchar, patente varchar, capitan_id int, descripción varchar

tal y como puedes notar la idea es que las llaves primarias queden subrayadas y que cada dato posea su tipo al lado.

Espero que te sea de ayuda

**Comment by nicogrecod18** [comment]
Gracias !!

**Comment by OrregoSilva** [comment]
Hola!
En caso de que la Primary Key sea la tupla completa, por ejemplo, la tabla Subió del Control 1, seria algo del estilo:
Subió(𝚞̲𝚒̲𝚍̲ INT, 𝚖̲𝚒̲𝚍̲, INT, 𝚊̲𝚗̲𝚘̲ INT)?

**Comment by arpincheira** [comment]
Hola, efectivamente deberían hacer algo así en el caso e que la tabla tenga más de una primary key. De todas formas en clases pronto verán las _foreing keys_, que son otro tipo de llaves  que podrían servir para entregas posteriores(**hint Entrega2?**)

**Comment by fran-gl** [comment]
> Hola, a modo de **hint** te presento un formato de esquema típico:
> 
> Barcos: barco_id int, nombre varchar, patente varchar, capitan_id int, descripción varchar
> 
> tal y como puedes notar la idea es que las llaves primarias queden subrayadas y que cada dato posea su tipo al lado.
> 
> Espero que te sea de ayuda

Hola! Dos dudas con respecto a esto.
1. Entonces, ¿no se deberían poner paréntesis al escribir los esquemas en el pdf? Como Barco(barco_id int, ...), etc.
2. ¿Hay que escribir el largo de los varchar? Por ejemplo, varchar(50).

**Comment by arpincheira** [comment]
Hola, tanto poner los paréntesis como los 2 puntos son opciones válidas al momento de escribir el esquema de datos

Em... no es necesario en el reporte, pueden hacer referencia a esta issue en el caso de que les descuenten por no indicarlo al momento de hacer la corrección.

**Comment by fran-gl** [comment]
Ok, muchas gracias!
