### ISSUE TITLE
Problema de uso postgresql

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2413/Syllabus-2021-1#85]
Hola estoy tratado de usar postgres ql (ya lo instale), pero cuando pongo en la consola linux:
$  sudo -i -u postgres
$  psql

me aparece lo siguiente: 
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

que significa?

**Comment by arpincheira** [comment]
Si estas tratando de correr postgreSQL en local lo más probable es que no hayas iniciado el servicio, te recomiendo en ese caso utilizar el comando

```
sudo service postgresql start
```

**Comment by Aloncarrasco** [comment]
Obrigado, voce e um amigo :)
