### ISSUE TITLE
Duda compras de un mismo usuario

### ISSUE THREAD

**Issue by totaurt** [IIC2413/Syllabus-2021-1#86]
Hola! Tengo unas preguntas con respecto a las compras, en el enunciado de grupos impares. 
¿Sería incorrecto asumir que un usuario solo realiza una compra? Y si fuera así, ¿este usuario puede comprar exactamente lo mismo, a la misma tienda y con la misma dirección de despacho? De manera que necesariamente haya que identificar ambas compras con un ID.
Gracias de antemano por la respuesta.

**Comment by amparostevens** [comment]
Hola! Claro, uno esperaría que un usuario pueda hacer más de una compra sin importar qué cosas está comprando, tal como pasa en la vida real. 
Espero haya quedado claro!
