### ISSUE TITLE
nombre del pdf

### ISSUE THREAD

**Issue by nicogrecod18** [IIC2413/Syllabus-2021-1#87]
Hola !! Es media tonta la pregunta, pero da lo mismo el nombre del archivo del pdf ? o se tiene que llamar 'Informe.pdf', por ejemplo nosotros le pusimos 'Entrega1Grupo46.pdf'. Pregunto porque me fijé que quizás para corregir, puede que descarguen de manera directa por scp y con un nombre común no tendrían que meterse al server a revisar el nombre del archivo de cada grupo.
Gracias de antemano.

**Comment by amparostevens** [comment]
Hola! No importa el nombre que le des mientras esté en la carpeta ```grupoXX/Entrega1``` , aunque siempre es buena idea darle nombre descriptivo a los archivos 😉
