### ISSUE TITLE
Como ver la base de datos

### ISSUE THREAD

**Issue by Gustav2000** [IIC2413/Syllabus-2021-1#88]
Hola, por lo que logré entender leyendo una issue, la base de datos para que la poblemos con nuestras tablas ya nos la entregan, pero no se como poder visualizarla o cómo saber como se llama para así poder trabajar en ella. Además algo que no entiendo es si cuando creo una tabla esta automáticamente se creará en mi base de datos, o yo tengo que decirle en que base de datos quiero que se cree?

**Comment by arpincheira** [comment]
Hola, para poder ingresar a la base de datos que se utiliza para esta entrega solamente debes utilizar el comando ```psql``` al interior del servidor y luego digitar tu clave. Una vez realizado esto ya estarás al interior de la base de datos grupoxx.

Ahora, para poder visualizar los contenidos al interior de esta te recomiendo utilizar el comando ```\dt```, el que te entregará una lista de todas las tablas existentes al interior de dicha base de datos.

Lo que se les pide en esta entrega entonces es realizar el informe y luego ingresar a la base de datos(utilizando el procedimiento anteriormente descrito) para poder crear y poblar las tablas que ustedes describieron con su entrega.

Con respecto a lo último, efectivamente con el simple hecho de estar al interior de una base de datos(que por defecto será la tuya) e ingresar el comando CREATE TABLE ...(aquí debes poner la info de tu tabla), crearás una tabla en esa base de datos y no en otra.

**Comment by Gustav2000** [comment]
Muchas gracias!!!
