### ISSUE TITLE
Control 1, pregunta 3

### ISSUE THREAD

**Issue by dedmu5** [IIC2413/Syllabus-2021-1#9]
Hola, ¿en la base de datos puede pasar que una misma persona suba una misma montaña en un mismo año? Sé que la base de datos que nos entregan no considera ese caso, pero necesito saber si necesito también resolver el problema para cualquier tupla que pudiese existir.

**Comment by ValentinaAlvarezG** [comment]
Hola! en álgebra relacional no hay duplicados y si consideraras que una misma persona sube una misma montaña en un mismo año, tendrías duplicados en ``Subió``.
