### ISSUE TITLE
Ruta de la entrega 1

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2413/Syllabus-2021-1#91]
Hola entre al servidor con mi clave y la consola muestra:
`grupo122@codd:~$`
Dentro de esa carpeta creo la carpeta que se llame 'Entrega1' ?
O debo crear una carpeta 'grupo122' primero y ahí hacer la carpeta 'entrega1'?

**Comment by arpincheira** [comment]
Hola, debes crear la carpeta Entrega1 directamente en esa ubicación. Si tienes dudas puedes revisar [la rúbrica general de la entrega 1](https://github.com/IIC2413/Syllabus-2021-1/tree/main/Proyecto/Entrega%201) en donde añadimos una imagen que te podría servir para aclarar tu duda
