### ISSUE TITLE
Archivos csv y readme

### ISSUE THREAD

**Issue by fedezang** [IIC2413/Syllabus-2021-1#92]
Hola!
Quería saber si puedo dejar los archivos csv con los que puse lo datos dentro de la carpeta Entrega1, o habría algún problema con dejarlos ahí.
También quería saber si está bien que el servidor tenga las carpetas/archivos:
Entrega1, readme.md, Sites.
Ya que al iniciar un repositorio de git hay un readme.md.

**Comment by arpincheira** [comment]
Hola, no hay ningún problema en dejarlos ahí. Lo importante por ahora es que tengas una carpeta Entrega1 y una carpeta Sites, no hay problema en que añadas un readme o un gitignore al servidor pues estos archivos no influyen en las entregas del proyecto
