### ISSUE TITLE
Respuesta consulta 1.2.2 y 1.2.3

### ISSUE THREAD

**Issue by MTSuarezS** [IIC2413/Syllabus-2021-1#93]
Hola, quería saber qué datos quieren que se muestren en las preguntas 1.2.2 y 1.2.3. Ya que se pide los jefes de las tiendas, pero quieren toda la información de los jefes (rut, edad, sexo, etc) o solo nombre? Lo mismo para cuando piden las tiendas que venden productos no comestibles, quieren solo el nombre de la tienda o más detalle (comuna, dirección, etc)?

**Comment by arpincheira** [comment]
Hola, tal y como mencionas, en ambos casos deben mostrar la entidad entera, es decir, en la 1.2.2 deben poner rut, edad, sexo, tienda en la que trabaja, etc.... y en la 1.2.3 deben poner nombre de la tienda, comuna, dirección, etc ....

**Comment by margavicunas** [comment]
Hola! Entonces es requisito agregar un esquema con la información de los jefes de local aparte de la del personal? O queda a criterio de cada grupo? Con los esquemas y atributos pedidos en el enunciado sólo están los nombres de los jefes de cada empleado (en el esquema Personal) pero no su rut, edad o sexo.
 Gracias!

**Comment by arpincheira** [comment]
Hola, queda a criterio de cada grupo, aunque prefiero que no se compliquen por eso, 

Lo que yo les recomiendo hacer (**hint**) es algo parecido a lo de la issue #84 .... en una de esas, como ya saben que los jefes forman parte del personal de la tienda (~al igual que los capitanes forman parte de la tripulación de un barco~) podrían encontrar alguna semejanza entre mi ejemplo y aquél que puse en dicha issue

**Comment by margavicunas** [comment]
Gracias!! 🌻
