### ISSUE TITLE
Duda consultas y entidades enteras

### ISSUE THREAD

**Issue by mpbosnic** [IIC2413/Syllabus-2021-1#94]
Hola! 

Cuando en las consultas se refiere a que se debe retornar la entidad entera, ¿a qué se refiere con entidad? En un caso hipotético, si mi tabla para tiendas no tuviera el atributo comuna, sino que comuna_id, ¿estaría correcto retornar este atributo como parte de la entidad Tienda? ¿o se refieren a "entidad del enunciado" donde tendría que retornar el nombre de la comuna? 

Saludos y gracias!

**Comment by JosefaPaz** [comment]
¡Hola!

Por ejemplo, si tenemos la base de datos de un taller mecánico, los coches o empleados serían entidades, y estas entidades tienen atributos (color, id, nombre, etcétera), por lo que cuando te dicen que debe retornar la entidad entera, en este ejemplo sería el coche junto con todos sus atributos :smiley_cat: 

Espero esto lo aclare, si no, en la clase de modelo relacional hay más información sobre esto.

¡Éxito!!

**Comment by mpbosnic** [comment]
Gracias!

**Comment by mpbosnic** [comment]
Hola denuevo! 

Disculpa que insista pero sigo con la duda. Si en el ejemplo que mencionas el coche se relacionara con la fábrica que lo creó (por lo que tendría un atributo que indica el id de esta fábrica). Al retornar la entidad, ¿tendría que entregar el "nombre" de dicha fábrica, o basta con este id? Me refiero a si la entidad se debe retornar en formato "interpretable" o en el formato en que existe en la base de datos nomás.

**Comment by JosefaPaz** [comment]
Hola! 

Disculpa la demora, si en el ejemplo te estuvieran pidiendo la información de la fábrica que creó X coche, como no especifican, es mejor entregar el id, nombre, dirección, etcétera, etcétera, es decir, todos los atributos de la fábrica.

Si llegase a pasar que son demasiados atributos, la mejor buena práctica es entrega el id ya que es único y como extra el nombre para que sea interpretable.

Espero que con esto quede claro!

**Comment by mpbosnic** [comment]
Gracias!
