### ISSUE TITLE
Duda consultas requeridas

### ISSUE THREAD

**Issue by Francisco5674** [IIC2413/Syllabus-2021-1#98]
Hola mundo

Seré breve, en esta entrega 1, ¿las 6 consultas pedidas deben retornar al menos un resultado, o solo las primeras tres?

Saludos

**Comment by arpincheira** [comment]
Hola, la idea es que sean capaces de **poblar todas las tablas de su esquema**. Ahora, ustedes solo deben asegurar el correcto funcionamiento de las primeras 3 consultas, por lo que, en lo que respecta a datos específicos o consideraciones a tomar al momento de poblarlas.
