### ISSUE TITLE
Duda duplicados en postgresql

### ISSUE THREAD

**Issue by domingo2000** [IIC2413/Syllabus-2021-1#99]
Hola, tengo la duda de si hay alguna manera de hacer que al crear la tabla el id sea unico, por elemplo, si en una tabla
Personas(id, nombre), ingreso dos veces una persona con el mismo id, entonces tendre dos filas con un id igual. ¿Existe alguna forma de que no me deje insertar una fila si se tiene el mismo id?. Y dentro de lo mismo 
¿Existe alguna forma de que se ingrese automaticamente un id y que este sea unico sin ponerlo explicito en la consulta?

**Comment by Skablop** [comment]
Sí, recuerda que al crear una tabla puedes definir un atributo como PRIMARY KEY, que cumple justo la función que necesitas.
